### PR TITLE
Validate `--from-schedule` flag in create backup command

### LINKED ISSUE #8214: Velero command not throwing and error when schedule hasn't been correctly defined
**What steps did you take and what happened:**

When running the command `velero create backup --from-schedule= test` I would suspect the command to fail, because there is a space between the **=** character and the name of the schedule. However, when I run this command Velero just creates a back-up with the name of the schedule as the name of the back-up. This is undesirable in my situation, because it will cause Velero to back-up items that have been excluded in my schedule.

**What did you expect to happen:**
I would suspect the command to fail, because there is a space between the **=** character and the name of the schedule.
**The following information will help us better understand what's going on**:

**Environment:**

- Velero version (use `velero version`): 
Client: v1.14.1
Server: v1.13.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by aj-2000**
Thank you for contributing to Velero!

# Please add a summary of your change
- **Added validation** for the `--from-schedule` flag to ensure non-empty, trimmed values.
- **Added tests** for different `--from-schedule` scenarios (empty, space-only, valid, and trimmed).

**Old behaviour**
image

**New behaviour**
image

**Unit tests**
image

# Does your change fix a particular issue?

Fixes #8214 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/cmd/cli/backup/create.go [hunk 1]
```diff
@@ -215,6 +220,23 @@ func (o *CreateOptions) Validate(c *cobra.Command, args []string, f client.Facto
 	return nil
 }
 
+func (o *CreateOptions) validateFromScheduleFlag(c *cobra.Command) error {
+	fromSchedule, err := c.Flags().GetString("from-schedule")
```
Comment (blackpiglet) [inline pkg/cmd/cli/backup/create.go:224]: What will happen if the `from-schedule` parameter is not present in the `velero backup create` CLI?
Please ensure no error will be reported in this case, because there are many cases backups are not created from scheduel.

Comment (aj-2000) [reply pkg/cmd/cli/backup/create.go:224]: If --from-schedule is not passed, command will require a backup name.
`velero create backup test` will work fine.

**Comment by blackpiglet** [comment]
Please resolve the error reported in the E2E test GitHub actions.
```
velero cmd =/home/runner/work/velero/velero/test/../_output/bin/linux/amd64/velero --namespace velero create schedule schedule-ordered-resources-29553521 --schedule @every 1m --include-namespaces ordered-resources-29553521-29553521 --default-volumes-to-fs-backup --ordered-resources deployments=deploy-ordered-resources-29553521;secrets=secret-ordered-resources-29553521;configmaps=configmap-ordered-resources-29553521
An error occurred: flag accessed but not defined: from-schedule
```

It seems the error was reported by the `velero schedule create` CLI.

File: pkg/cmd/cli/backup/create.go [hunk 2]
```diff
@@ -215,6 +220,23 @@ func (o *CreateOptions) Validate(c *cobra.Command, args []string, f client.Facto
...
+	if err != nil {
+		return err
+	}
+
+	trimmed := strings.TrimSpace(fromSchedule)
+	if c.Flags().Changed("from-schedule") && trimmed == "" {
```
Comment (reasonerjt) [inline pkg/cmd/cli/backup/create.go:230]: Thanks, but I believe you can use `o.FromSchedule` directly and add the code to `Validate` func?

Comment (aj-2000) [reply pkg/cmd/cli/backup/create.go:230]: Yeah, I should have used `o.FromSchedule` there. But for the second part, I have added some unit tests, which require a separate `validateFromScheduleFlag` function. If you feel that the unit tests specific to my changes are unnecessary, I can remove them and move the entire logic to the Validate function.

I believe they are good to have, and a separate `validateFromScheduleFlag` function should be fine.

**Review by blackpiglet — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]
