### PR TITLE
Fix inconsistent behavior of Backup and Restore hook execution

### LINKED ISSUE #6721: Different behavior of Backup and Restore hook execution.
**What steps did you take and what happened:**
***Issue 1***
Backup Hook Execution behavior.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-IN style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

onError: Continue  | Case 1: Hooks     are executed successfully. Backup Status: Completed | Case 2: Hooks     execution failed/or has some error Backup Status: PartiallyFailed
-- | -- | --
onError: Fail | Case 1: Hooks     are executed successfully. Backup Status: Completed | Case 2: Hooks     execution failed/or has some error Backup Status: PartiallyFailed

</div>

</body>

</html>
Restore Hook Execution behavior.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-IN style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

onError: Continue  | Case 1: Hooks     are executed successfully. Restore Status: Completed | Case 2: Hooks     execution failed/or has some error Restore Status: Completed
-- | -- | --
onError: Fail | Case 1: Hooks     are executed successfully. Restore Status: Completed | Case 2: Hooks     execution failed/or has some error Restore Status: PartiallyFailed

</div>

</body>

</html>

***Issue 2***
While publishing restore result, all the errors and warning are currently pushed to Velero-level even when it is namespaced level error.
[code path](https://github.com/vmware-tanzu/velero/blob/db6784aa8138a91cc3dbcd766635bd726da78cce/pkg/restore/restore.go#L599C32-L599C32)
image

**What did you expect to happen:**
In above table we can see that tthe behaviour of restore is different when onError is set to continue and there is some error in the hooks execution. It only logs the error and shows the restore status as complete [It only returns error when onError is set to fail], where it should not be the case. It should show partially failed state and push the error/ warning in the restore result. In this way we can know that hook was executed or not.

Rather than pushing the error/warning to velero-level bucket, appending the error/warning to their respective bucket (like namespace, velero, cluster) [Code path](https://github.com/vmware-tanzu/velero/blob/db6784aa8138a91cc3dbcd766635bd726da78cce/pkg/util/results/result.go#L22C1-L22C1)
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

The behavior of backup and restore hook execution should be same (i.e., we can also return error when the restore hook execution fails when OnError is set to Continue). Also for better parsing, we can change the way we are pushing changes in the restore result. Instead of storing error on hookErrs channel {[here](https://github.com/vmware-tanzu/velero/blob/db6784aa8138a91cc3dbcd766635bd726da78cce/pkg/restore/restore.go#L1781C1-L1781C25)}, storing error in Result will be better.
image

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by allenxu404**
Thank you for contributing to Velero!

# Please add a summary of your change
- restore returns `PartiallyFailed` when failing to execute hook with its onError set to `Continue`. This will be inconsistant with backup pattern in the same case.
- Hook errors are added to namespace-level bucket instead of velero-level bucket in result.
- Adds more info to hook errors.

# Does your change fix a particular issue?

Fixes #6721 

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by anshulahuja98** [comment]
@Shashank1306s can you review this please.
I can do another round of review post that.

File: internal/hook/wait_exec_hook_handler.go [hunk 1]
```diff
@@ -156,10 +161,10 @@ func (e *DefaultWaitExecHookHandler) HandleHooks(
 				)
 				// Check the individual hook's wait timeout is not expired
 				if hook.Hook.WaitTimeout.Duration != 0 && time.Since(waitStart) > hook.Hook.WaitTimeout.Duration {
-					err := fmt.Errorf("hook %s in container %s expired before executing", hook.HookName, hook.Hook.Container)
+					err := fmt.Errorf("hook %s in container %s expired before executing, hook commands: %+v", hook.HookName, hook.Hook.Container, hook.Hook.Command)
```
Comment (Shashank1306s) [inline internal/hook/wait_exec_hook_handler.go:164]: I think adding hook command here in log has no value add. Better message to float would be something like this `hook %s in container %s expired before execution. This occurred when the hook expired because the container did not become ready within the specified wait time.`

File: internal/hook/wait_exec_hook_handler.go [hunk 2]
```diff
@@ -50,6 +50,11 @@ type DefaultListWatchFactory struct {
 	PodsGetter cache.Getter
 }
 
+type HookErrInfo struct {
+	NameSpace string
```
Comment (Shashank1306s) [inline internal/hook/wait_exec_hook_handler.go:54]: CamelCasing `NameSpace` does not look good. `Namespace` would be better.

Comment (allenxu404) [reply internal/hook/wait_exec_hook_handler.go:54]: Yes, make sense.

File: internal/hook/wait_exec_hook_handler.go (hunk 1 above)
Comment (allenxu404) [reply internal/hook/wait_exec_hook_handler.go:164]: Adding hook command here is to let users specifically know which hook commands didn't execute correctly.  I think it's useful for pod annotation hooks since user can identify the hook by checking the hook command.

At least, Adding hook command doesn't hurt to current workflow, right?

File: internal/hook/wait_exec_hook_handler.go [hunk 3]
```diff
@@ -172,8 +177,9 @@ func (e *DefaultWaitExecHookHandler) HandleHooks(
 				}
 				if err := e.PodCommandExecutor.ExecutePodCommand(hookLog, podMap, pod.Namespace, pod.Name, hook.HookName, eh); err != nil {
 					hookLog.WithError(err).Error("Error executing hook")
+					err = fmt.Errorf("hook %s in container %s failed to execute, hook commands: %v, err: %s", hook.HookName, hook.Hook.Container, hook.Hook.Command, err)
```
[the remark this answers is not in the document]
Comment (allenxu404) [reply internal/hook/wait_exec_hook_handler.go:180]: OK, will change it.

File: internal/hook/wait_exec_hook_handler.go [hunk 4]
```diff
@@ -213,7 +219,7 @@ func (e *DefaultWaitExecHookHandler) HandleHooks(
 			if hook.executed {
 				continue
 			}
-			err := fmt.Errorf("hook %s in container %s in pod %s not executed: %v", hook.HookName, hook.Hook.Container, kube.NamespaceAndName(pod), ctx.Err())
+			err := fmt.Errorf("hook %s in container %s in pod %s not executed: %v, hook commands: %v", hook.HookName, hook.Hook.Container, kube.NamespaceAndName(pod), ctx.Err(), hook.Hook.Command)
```
[the remark this answers is not in the document]
Comment (allenxu404) [reply internal/hook/wait_exec_hook_handler.go:222]: Sure, make sense!

[the remark this answers is not in the document]
Comment (allenxu404) [reply internal/hook/wait_exec_hook_handler.go:222]: Maybe user don't have to know the specific hook command but it doesn't hurt to provide more info.

File: internal/hook/wait_exec_hook_handler.go (hunk 1 above)
Comment (Shashank1306s) [reply internal/hook/wait_exec_hook_handler.go:164]: yes makes sense.

File: internal/hook/wait_exec_hook_handler.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (Shashank1306s) [reply internal/hook/wait_exec_hook_handler.go:221]: okay

File: internal/hook/wait_exec_hook_handler.go (hunk 1 above)
Comment (anshulahuja98) [reply internal/hook/wait_exec_hook_handler.go:164]: just have 1 concern around sensitivity of the data being pushed into logs. 
The commands can have secrets for auth etc. Which might not be very wise to put in logs.

Comment (allenxu404) [reply internal/hook/wait_exec_hook_handler.go:164]: Ahh, yeah, your concern is valid, let me remove the commands from logs.

**Review by blackpiglet — APPROVED** [review]

**Review by anshulahuja98 — APPROVED** [review]
