### PR TITLE
Do not attempt restore resource with no available GVK in cluster

### LINKED ISSUE #7319: EnableAPIGroupVesions test failed due to restore hung at in-progress state with informer cache enabled
**What steps did you take and what happened:**

[APIGroupVersions E2E test case #3](https://github.com/vmware-tanzu/velero/blob/2caba3efb93c37edc73aac1301f68ba91a670a80/test/e2e/basic/api-group/enable_api_group_versions.go#L162C3-L162C3) failed when informer cache is enabled, below is some case information:

Case description: _"No common supported versions means no rockbands custom resource is restored."_.
Case test steps:

1. Install Velero with feature EnableAPIGroupVesions;
2. Create CRD with version v1 and v1alpha1 defined in, create a CR of the CRD in a namespace;
3. Backup the namespace;
4. Remove the namespace, delete the CRD;
5. Create the same CRD with version v2beta1 and v2beta2;
6. Restore namespace;
7. Restore hung there until test case timeout.

Velero pod logs as below, we got errors like `the server could not find the requested resource`, because according to the test case, the backed up CR will not be restored due to no appropriate CRD versions can be found, so this CR resource does not exist at all:

```
time="2024-01-15T02:55:25Z" level=info msg="[debug] Creating factory for music.example.io.2/v1, Resource=rockband2s in namespace rockband2s-src-v1-2" logSource="pkg/restore/restore.go:1082" restore=velero/restore-rockbands-79b415c5-948d-4032-9496-ad00cc5fdc7c-unwanted
time="2024-01-15T02:55:25Z" level=info msg="[debug] Creating factory for music.example.io.2/v1, Resource=rockband2s in namespace rockband2s-src-v1alpha1-2" logSource="pkg/restore/restore.go:1082" restore=velero/restore-rockbands-79b415c5-948d-4032-9496-ad00cc5fdc7c-unwanted
W0115 02:55:25.371990       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: failed to list *unstructured.Unstructured: the server could not find the requested resource
W0115 02:55:25.372115       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: failed to list *unstructured.Unstructured: the server could not find the requested resource
E0115 02:55:25.372154       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
E0115 02:55:25.372156       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
W0115 02:55:26.180492       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: failed to list *unstructured.Unstructured: the server could not find the requested resource
E0115 02:55:26.180523       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
W0115 02:55:26.447132       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: failed to list *unstructured.Unstructured: the server could not find the requested resource
E0115 02:55:26.447184       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
```

**What did you expect to happen:**
Restore should get PartiallyFailed result in a short time instead of stuck in in-progress state.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by kaovilai**
It is possible to end up in a situation where CRD was not restored due to an already existing CRD with a newer GVK without prior GVK. When restoring CR with older GVK, this PR causes item restore to error early and partially fail.

In the future, it might be desirable to merge CRD.spec.versions from backup with in-cluster if it can be done without conflicts but is out of scope of this PR.

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #7319 

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/restore/restore.go [hunk 1]
```diff
@@ -1507,6 +1507,22 @@ func (ctx *restoreContext) restoreItem(obj *unstructured.Unstructured, groupReso
...
+	_, _, err = ctx.discoveryHelper.KindFor(schema.GroupVersionKind{
+		Group:   groupResource.Group,
+		Version: obj.GetAPIVersion(),
+		Kind:    groupResource.Resource,
+	})
+	clusterHasKind := err == nil
+	if !clusterHasKind  {
+		ctx.log.Errorf("Cannot restore %s because GVK doesn't exist in the cluster", groupResource)
+		// Adding to errs should cause restore to partially fail
+		errs.Add(namespace, fmt.Errorf("cannot restore %s because gvk doesn't exist in the cluster", groupResource))
```
Comment (kaovilai) [inline pkg/restore/restore.go:1522]: This should cause restore to partially fail, but the error message maybe different than before. Alternatively, [another commits](https://github.com/vmware-tanzu/velero/commit/6c4bb32b8bc1bcda9ade8640593c77a248f1d782) attempts to preserve prior error message for when informer cache is disabled. Let me know which is preferred.

File: pkg/restore/restore.go [hunk 2]
```diff
@@ -1507,6 +1507,22 @@ func (ctx *restoreContext) restoreItem(obj *unstructured.Unstructured, groupReso
 		}
 	}
 
+	// Check if cluster has GVK required to restore resource, otherwise return err.
+	// Placed here because the object apiVersion might get modified by a RestorePlugin
+	// So we check for the GVK after the RestorePlugin has run.
+	_, _, err = ctx.discoveryHelper.KindFor(schema.GroupVersionKind{
```
Comment (ywk253100) [inline pkg/restore/restore.go:1513]: I'm afraid this change isn't the correct fix because the informer syncing will still stuck if the CRDs don't exist or aren't restored: https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L602

The second commit is the good one

Comment (kaovilai) [reply pkg/restore/restore.go:1513]: Thanks. So maybe hybrid of both?

Comment (ywk253100) [reply pkg/restore/restore.go:1513]: IMHO, the change in the second commit is enough. Seems the change here doesn't help resovling the issue, correct me if I'm wrong.

**Comment by kaovilai** [comment]
I think pkg/discovery and Fakes may not have been implemented fully.. will continue tomorrow

File: pkg/discovery/helper.go [hunk 3]
```diff
@@ -193,7 +196,8 @@ func (h *helper) Refresh() error {
 
 		for _, resource := range resourceGroup.APIResources {
 			gvr := gv.WithResource(resource.Name)
-			gvk := gv.WithKind(resource.Kind)
+			// gvk kind is lowercased for consistency of hits in KindFor()
+			gvk := gv.WithKind(strings.ToLower(resource.Kind))
```
Comment (kaovilai) [inline pkg/discovery/helper.go:200]: This and related changes fixed the unit tests. Will have to try a run live in a real environment to confirm everything is working.

File: pkg/discovery/helper.go [hunk 4]
```diff
@@ -117,6 +119,7 @@ func (h *helper) ResourceFor(input schema.GroupVersionResource) (schema.GroupVer
 	return gvr, apiResource, nil
 }
 
+// KindFor expects input where kind is lowercased to hit the map
```
Comment (ywk253100) [inline pkg/discovery/helper.go:122]: The reason the `Kind` doesn't match is that the test code converts the `Resource` to `Kind` incorrectly: https://github.com/vmware-tanzu/velero/blob/main/pkg/test/discovery_client.go#L79

This shouldn't happen in the real world.

So let's specify the `Kind` explicitly in the test code, I create a [PR](https://github.com/vmware-tanzu/velero/pull/7334) for this, free feel to copy the changes into your PR if it isn't merged

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by ywk253100 — APPROVED** [review]
