### PR TITLE
Descriptive restore error on timeout due to terminating namespace

### LINKED ISSUE #5697: Restore gets stuck if the destination namespace is in Terminating phase
**_What steps did you take and what happened_**

Ran a restore to a namespace where the destination namespace has a pod which was in the terminating phase. The restore did not complete or fail. The restore gets stuck in "InProgress" phase, with no errors or warnings in the logs.

**_What did you expect to happen_:**

Restore should fail due to timeout or with some descriptive error. Logs should contain the information, related to failed restores.

**_The following information will help us better understand what's going on_**:

[bundle-2022-12-15-05-05-58.tar.gz](https://github.com/vmware-tanzu/velero/files/10236833/bundle-2022-12-15-05-05-58.tar.gz)

**Environment:**

- Velero version (use `velero version`): 

        $ velero version
        Client:
                Version: v1.10.0
                Git commit: 367f563072659f0bcd809bc33507fd75cd722344
        Server:
                Version: v1.10.0

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):

        $ k version
        Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
        Kustomize Version: v4.5.4
        Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
        WARNING: version difference between client (1.24) and server (1.21) exceeds the supported minor version skew of +/-1

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

        $ cat /etc/os-release
        NAME="Ubuntu"
        VERSION="18.04.6 LTS (Bionic Beaver)"
        ID=ubuntu
        ID_LIKE=debian
        PRETTY_NAME="Ubuntu 18.04.6 LTS"
        VERSION_ID="18.04"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by kaovilai**
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change
Make restore error descriptive when namespace being restored is in terminating state.
Any user seeing this error should know that velero does not force a namespace to disappear by removing finalizers because that could be destructive to some workloads.

User should make namespace be in a state other than terminating for Velero to continue restore process.

# Does your change fix a particular issue?

Fixes #5697

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/util/kube/utils.go [hunk 1]
```diff
@@ -62,17 +62,22 @@ func NamespaceAndName(objMeta metav1.Object) string {
...
+//     for a reason other than that the namespace already exists. Note that in the case where the
+//   - an error if one occurred.
+//
+// examples:
+//
+//	namespace already exists and is not ready, this function will return (false, false, nil).
+//	If the namespace exists and is marked for deletion, this function will wait up to the timeout for it to fully delete.
+func EnsureNamespaceExistsAndIsReady(namespace *corev1api.Namespace, client corev1client.NamespaceInterface, timeout time.Duration) (ready bool, nsCreated bool, err error) {
 	// nsCreated tells whether the namespace was created by this method
 	// required for keeping track of number of restored items
```
Comment (kaovilai) [inline pkg/util/kube/utils.go:77]:
```suggestion
```

File: pkg/util/kube/utils.go [hunk 2]
```diff
@@ -97,15 +100,22 @@ func EnsureNamespaceExistsAndIsReady(namespace *corev1api.Namespace, client core
...
 		return false, nsCreated, errors.Wrapf(err, "error getting namespace %s", namespace.Name)
 	}
 
 	// In the case the namespace already exists and isn't marked for deletion, assume it's ready for use.
 	if ready {
 		return true, nsCreated, nil
 	}
-
-	clusterNS, err := client.Create(context.TODO(), namespace, metav1.CreateOptions{})
+	namespaceToCreate := namespace.DeepCopy()
```
Comment (blackpiglet) [inline pkg/util/kube/utils.go:113]: https://github.com/vmware-tanzu/velero/blob/b2f1588d2e54c6a9cfd560845394ff94bc1513e4/pkg/backup/item_backupper.go#L162C5-L165

It seems there is no need to delete the status and the DeletionTimestamp from the namespace.
The namespace in the deletion state will not be included.

Comment (kaovilai) [reply pkg/util/kube/utils.go:113]: Ok cool!. Thanks for the review, didn't know about this. Will remove this part then.

Hopefully no one has a use case for restoring an item already in deletion as new.

Comment (kaovilai) [reply pkg/util/kube/utils.go]: addressed in 4e7fd6e96d28a2cb815e9c5ac63af47c05cc2883

Comment (kaovilai) [reply pkg/util/kube/utils.go]: updated changelog in 0b36bb5e2

Comment (kaovilai) [reply pkg/util/kube/utils.go]: undo utils_test 63fb95341e416e43ca86f2cddd5ddfbe67ea7eb7

**Review by blackpiglet — APPROVED** [review]

**Review by shubham-pampattiwar — DISMISSED** [review]

**Review by blackpiglet — APPROVED** [review]

**Comment by mayankagg9722** [comment]
HI @kaovilai @blackpiglet we are seeing the Issue #7516. Please look into it once in the same method.

Problem: During restore for every resource within the namespace, we are calling the check to await on if namespace exists (wait for 10 min polling). For instance, if we have 100 resourced in a namespace that itself is in terminating state for very long then it impacts the restore flow to get stuck/halt and it too increases the time to restore.

File: pkg/util/kube/utils.go [hunk 3]
```diff
@@ -97,6 +103,9 @@ func EnsureNamespaceExistsAndIsReady(namespace *corev1api.Namespace, client core
 
 	// err will be set if we timed out or encountered issues retrieving the namespace,
 	if err != nil {
+		if terminatingNamespace {
+			return false, nsCreated, errors.Wrapf(err, "timed out waiting for terminating namespace %s to disappear before restoring", namespace.Name)
+		}
```
Comment (mayankagg9722) [inline pkg/util/kube/utils.go:108]: as this call is used during restore as well, and if such error occur for the resource during restore, can we also add this to restore warnings list?

Comment (mayankagg9722) [reply pkg/util/kube/utils.go:108]: Mention #7516

Comment (kaovilai) [reply pkg/util/kube/utils.go:108]: Is warning preferred over restore error?

Comment (kaovilai) [reply pkg/util/kube/utils.go:108]: Also per PR title, the intent is that the error are visible in restore error.

Comment (kaovilai) [reply pkg/util/kube/utils.go:108]: What changes do you see needed to be made to the PR?

Comment (mayankagg9722) [reply pkg/util/kube/utils.go:108]: Sorry on the late reply, I was awk.
Yes, overall its good to have this error that you added and its visible during restore

Comment (mayankagg9722) [reply pkg/util/kube/utils.go:108]: For reducing the time to address the issue #7516 we need to look at other options.

**Review by anshulahuja98 — APPROVED** [review]

**Comment by anshulahuja98** [comment]
@kaovilai , feel free to merge this now, approved it.

**Comment by kaovilai** [comment]
@anshulahuja98 I don't have access to merge. Not a maintainer.
