### PR TITLE
release-1.9: Use updated PVB/PVR for patching Failed Phase during startup

### LINKED ISSUE #5827: InProgress PodVolumeBackup/PodVolumeRestore are not marked as failed when node-agent restarts
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Delete node-agent pod

**What did you expect to happen:**
InProgress PVB/PVR are failed after node-agent pod start again
**The following information will help us better understand what's going on**:
PVB/PVR remains InProgress

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): main
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by kaovilai**
Use the same pvb/pvr update functions across pkg/controller and pkg/cli/nodeagent for consistency of behavior

same as #5828 for release-1.9

Fixes #5827 

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by sseago — DISMISSED** [review]

File: pkg/podvolumebackup/util.go [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package podvolumebackup
```
Comment (Lyndon-Li) [inline pkg/podvolumebackup/util.go:1]: The two UpdateStatusToFailed functions work for podvolumebackup/podvolumerestore CR only, they don't look like common functions that could be used by others in future. Therefore, I suggest we still put the two functions in the controller files. This will also make the code here compliance with main and 1.10 branch as the comment[ here](https://github.com/vmware-tanzu/velero/pull/5830/files#r1098080167)
