### PR TITLE
Data mover wrong bsl after sync

### LINKED ISSUE #6534: Backup repo snapshot is not deleted after backup sync for file system backup
The PVB CR's StorageLocation is not reset to the latest one after backup sync, as a result, when deleting the PVB, the backup deletion controller cannot delete the repo snapshot from the correct backup storage location, so there will be snapshot data leak in the repo

### PR DESCRIPTION
**Pull request by Lyndon-Li**
This PR fixes two issues:
1. The PVB CR's `StorageLocation` is not reset to the latest one after backup sync, as a result, when deleting the PVB, the backup deletion controller cannot delete the repo snapshot from the correct backup storage location, so there will be data leak in the repo
2. During data mover restore, the DataUploadResult's `StorageLocation` is retrieved from the DataUpload CR, while the value in DataUpload CR is not up to date if the BSL's name has changed in the new cluster, as a result, the data mover restore will fail

As the fixes:

- For 1, reset PVB CR's `StorageLocation` to the latest one during backup sync
- For 2, retrieve DataUploadResult's `StorageLocation` from the latest backup CR whose `StorageLocation` has been reset during backup sync

Fix #6534

### CODE REVIEW

File: pkg/restore/dataupload_retrieve_action.go [hunk 1]
```diff
@@ -29,19 +29,22 @@ import (
 
 	velerov1api "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
 	velerov2alpha1 "github.com/vmware-tanzu/velero/pkg/apis/velero/v2alpha1"
+	velerov1client "github.com/vmware-tanzu/velero/pkg/generated/clientset/versioned/typed/velero/v1"
```
Comment (ywk253100) [inline pkg/restore/dataupload_retrieve_action.go:32]: Let's use the controller runtime client instead as we are moving away from the generated clients

Comment (Lyndon-Li) [reply pkg/restore/dataupload_retrieve_action.go]: Done the changes, thanks.

**Review by ywk253100 — APPROVED** [review]

**Review by blackpiglet — APPROVED** [review]
