### PR TITLE
Restore progress reporting bug fix

### LINKED ISSUE #3571: PR 3125 Breaks API Group Versions Feature (PR 3133)
**What steps did you take and what happened:**
I'm trying to run e2e tests that ensure the API group versions features is working as intended, however, they are not passing. See the latest version of the API group versions e2e tests in PR #3564. When I try to restore Kubernetes non-preferred API group versions, I get this error:

```bash
Errors:
  Namespaces:
    rockbands-src-v2beta1:  error restoring rockbands.music.example.io/rockbands-src-v2beta1/beatles: the server could not find the requested resource
    rockbands-src-v2beta2:  error restoring rockbands.music.example.io/rockbands-src-v2beta2/beatles: the server could not find the requested resource
    rockbands-src-v1:       error restoring rockbands.music.example.io/rockbands-src-v1/beatles: the server could not find the requested resource
```

**What did you expect to happen:**
I expected all API versions that were in the backup tarball file to be restored. None of the errors above should have occurred because I verified v2beta1, v2beta2, and v1 rockband versions were in the tarball.

**More information:**
@zubron and I have found the commit that broke API group versions feature was from PR 3125. 

```git
2021-03-04 16:21 -0500 Pranav Gaikwad              o Restore progress reporting (#3125)
commit c46fe71b12ecc16786676886a64971102527d631
```

PR 3125 removed the changes that I had made in PR 3133 restore.go. See the diffs in pkg/restore/restore.go, lines 749-758: https://github.com/vmware-tanzu/velero/pull/3125/files#diff-e0498755be37b683528e2569667d67818bb676827c420aab49adc62cb6d47fe3L749-L758).

Tagging @pranavgaikwad.

**Vote on this issue!**
- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by codegold79**
# Summary of change

Fixes the bug introduced by PR #3125.

# Does your change fix a particular issue?

Fixes #3571 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by codegold79** [comment]
For reviewers, feel free to skim passed the formatting changes (all in one commit). The important changes are in the commit with the message `Update paths to include API group versions`.

Screen Shot 2021-03-12 at 4 04 26 PM

File: pkg/restore/restore.go [hunk 1]
```diff
@@ -1655,22 +1656,39 @@ func (ctx *restoreContext) getOrderedResourceCollection(backupResources map[stri
...
+	// If the APIGroupVersionsFeatureFlag is enabled, the item path will be
+	// updated to include the API group version that was chosen for restore. For
+	// example, for "horizontalpodautoscalers.autoscaling", if v2beta1 is chosen
+	// to be restored, then "horizontalpodautoscalers.autoscaling/v2beta1" will
+	// be part of item path. Different versions would only have been stored
+	// if the APIGroupVersionsFeatureFlag was enabled during backup. The
+	// chosenGrpVersToRestore map would only be populated if
+	// APIGroupVersionsFeatureFlag was enabled for restore and the minimum
+	// required backup format version has been met.
+	cgv, ok := ctx.chosenGrpVersToRestore[resrc]
```
Comment (zubron) [inline pkg/restore/restore.go:1685]: I'm trying to follow what happened in your original PR and in the restore progress one that lost this section.

In #3133 when this was added, we were using [`groupResource.String()`](https://github.com/vmware-tanzu/velero/pull/3133/files#diff-e0498755be37b683528e2569667d67818bb676827c420aab49adc62cb6d47fe3R747-R759) as the key for the map lookup, but now we're using `resrc`. I think this is okay given that this function is called with `groupResource.String()` as the first parameter but I just want to make sure I'm following this correctly as it's tricky to know what these variables represent. Is my understanding correct here?

**Comment by zubron** [comment]
This PR might require a changelog as it's a bug fix. Although, it's for a bug that hasn't been present in a released version of Velero. @carlisia, thoughts on this?

**Comment by carlisia** [comment]
> Although, it's for a bug that hasn't been present in a released version of Velero. @carlisia, thoughts on this?

This is such a good question. I would say no, no need to include it.

I will open an issue to document what deserves a changelog.

File: pkg/restore/restore.go (hunk 1 above)
Comment (codegold79) [reply pkg/restore/restore.go:1685]: It's good to make sure, because the code is difficult to follow. Yes, I believe your understanding is correct. Here are the lines and links that follow the logic you stated:

PR 3133 had [line 755](https://github.com/codegold79/velero/blob/00fd5ff738fc51c765b57393859bac01335ae535/pkg/restore/restore.go#L755). Exactly as you wrote, `groupResource.String()` is used as the key for the map lookup.

```go
groupResource := schema.ParseGroupResource(resource)

cgv, ok := ctx.chosenGrpVersToRestore[groupResource.String()]
if ok {
	resource = filepath.Join(groupResource.String(), cgv.Dir)
}
```

For this PR 3583, `resrc` is used instead. This variable was passed into the [`getSelectedRestoreableItems(...)` method](https://github.com/vmware-tanzu/velero/blob/ccbd30f450a0b332e3dfe5a721ba4fad65845801/pkg/restore/restore.go#L1659). This method was called in the `getOrderedResourceCollection(...)` method on [line 1643](https://github.com/vmware-tanzu/velero/blob/ccbd30f450a0b332e3dfe5a721ba4fad65845801/pkg/restore/restore.go#L1643).

```go
res, w, e := ctx.getSelectedRestoreableItems(groupResource.String(), targetNamespace, namespace, items)
```

When I ran the API group versions e2e tests, I was able to verify that the correct <resource>.<group> strings were being passed in and the path was being modified as intended.

Comment (zubron) [reply pkg/restore/restore.go:1685]: Thanks for the detailed explanation!

**Review by zubron — APPROVED** [review]
Thanks, @codegold79!

**Review by carlisia — CHANGES_REQUESTED** [review]
Hi @codegold79, I'm asking you to revert just a very minor change.

I verified that you have put back in all of your changes from PR #3133, and have not removed anything related to the PR #3125.

This LGTM, thank you for fixing this!

File: pkg/restore/restore.go [hunk 2]
```diff
@@ -1655,22 +1656,39 @@ func (ctx *restoreContext) getOrderedResourceCollection(backupResources map[stri
 // getSelectedRestoreableItems applies Kubernetes selectors on individual items
 // of each resource type to create a list of items which will be actually
 // restored.
-func (ctx *restoreContext) getSelectedRestoreableItems(resource, targetNamespace, originalNamespace string, items []string) (restoreableResource, Result, Result) {
-	var res restoreableResource
+func (ctx *restoreContext) getSelectedRestoreableItems(resrc, targetNamespace, originalNamespace string, items []string) (restoreableResource, Result, Result) {
```
[the remark this answers is not in the document]
Comment (codegold79) [reply pkg/restore/restore.go:1659]: I'm wondering if it would be better to go further and do `s/resrc/groupResource` because that string does include the group. What do you think @carlisia?

[the remark this answers is not in the document]
Comment (carlisia) [reply pkg/restore/restore.go:1659]: Do you think `groupResource` could signal that it is specifically only group resources? If not, go ahead and change it. I'll approve whatever you decide.

**Review by carlisia — APPROVED** [review]
🎉

**Review by zubron — APPROVED** [review]
Thanks, @codegold79! :tada:

**Comment by pranavgaikwad** [comment]
@codegold79 Thank you very much for the fix. I may have missed this in the rebase, both PRs (yours and mine) were merged around the same time. Sorry about that. I was unavailable last two weeks. Couldn't look at the issue. Thank you again!
