### PR TITLE
Fix VolumePolicy PVC phase condition filter for unbound PVCs (#9507)

### LINKED ISSUE #9507: VolumePolicy's PVC Phase condition filter doesn't work properly
**What steps did you take and what happened:**

#9166 introduced a new filter to support filtering PVC by Phase.
For the PVCs in the `Pending` phase, there are some differences from the bound PVCs.
* First, because `Pending` PVC are not ready, the only applied action is `skip`.
* Second, the `Pending` PVC doesn't have PV bound yet.

During test, I found there are some error reported for skipping the `Pending` PVCs.

First, because the PVC skip check is after the fs-backup, the fs-backup check already raised error before running skip check.
```
time="2026-01-29T07:05:50Z" level=error msg="fail to get PV for PVC nfs/pvc-nfs-pv2" backup=velero/skip-pending-pvc-02 error="PVC nfs/pvc-nfs-pv2 has no volume backing this claim" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/util/kube/pvc_pv.go:425" error.function=github.com/vmware-tanzu/velero/pkg/util/kube.GetPVForPVC logSource="internal/volumehelper/volume_policy_helper.go:235"

time="2026-01-29T07:05:50Z" level=error msg="Error backing up item" backup=velero/skip-pending-pvc-02 error="PVC nfs/pvc-nfs-pv2 has no volume backing this claim" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/util/kube/pvc_pv.go:425" error.function=github.com/vmware-tanzu/velero/pkg/util/kube.GetPVForPVC logSource="pkg/backup/backup.go:929" name=nginx-deployment-b454d4696-jhtj8
```

Second, in the skip check, the code also tries to find the PV for PVC, as a result, a waring is recorded.
```
time="2026-01-29T07:05:50Z" level=warning msg="unable to get PV name, skip tracking." backup=velero/skip-pending-pvc-02 error="PV name is not set in PVC" logSource="pkg/backup/item_backupper.go:712" name=pvc-nfs-pv2 namespace=nfs resource=persistentvolumeclaims
```

**What did you expect to happen:**
The skipping logic should work without any warning and error.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by kaovilai**
When a PVC is in Pending or Lost phase with a volume policy skip action,
errors were generated because the skip check happened AFTER GetPVForPVC()
was called. Pending/Lost PVCs have no bound PV, causing errors like:
- "fail to get PV for PVC: has no volume backing this claim"
- "unable to get PV name, skip tracking"

This fix checks PVC-only skip policies (e.g., pvcPhase) BEFORE attempting
to get the PV. The GetMatchAction() function already supports PVC-only
matching (no PV required), so we leverage this for early skip detection.

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>

Thank you for contributing to Velero!

# Please add a summary of your change
- Add checkPVCOnlySkip() helper in volume_policy_helper.go
- Modify ShouldPerformSnapshot() to check PVC-only skip before PV lookup
- Modify ShouldPerformFSBackup() to check PVC-only skip before PV lookup
- Modify getMatchAction() in item_backupper.go to try PVC-only match first
- Update trackSkippedPV/unTrackSkippedPV to log at debug level for Pending PVCs
- Add comprehensive unit tests for Pending and Lost PVC phases

# Does your change fix a particular issue?

Fixes #9507

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by kaovilai** [comment]
Alternatives:

- Lazy PV Fetching: Make VolumeFilterData accept a lazy getter instead of the PV
- Graceful PV Fetch with nil fallback: Try to get the PV upfront, but treat "unbound PVC" as a non-fatal case

**Comment by kaovilai** [comment]
For lost PVC you will see the following
```                                                                        
    time="2026-01-30T00:41:21Z" level=warning msg="Cannot find info for PV pv-to-delete" backup=openshift-adp/test-lost-pvc-backup logSource="internal     
    /volume/volumes_information.go:363"                                                                                                                    
```
Do we want to change this to debug level for skip case?                                                                                                                                                      
                                                                                                                                                           
Manual tests indicates the PR fixes prior issue.

File: pkg/backup/item_backupper.go [hunk 1]
```diff
@@ -719,6 +739,17 @@ func (ib *itemBackupper) unTrackSkippedPV(obj runtime.Unstructured, groupResourc
 	if name, err := getPVName(obj, groupResource); len(name) > 0 && err == nil {
 		ib.backupRequest.SkippedPVTracker.Untrack(name)
 	} else if err != nil {
+		// For PVCs in Pending phase, it's expected that there's no PV name.
+		// Log at debug level instead of warning to reduce noise.
+		if groupResource == kuberesource.PersistentVolumeClaims {
```
Comment (blackpiglet) [inline pkg/backup/item_backupper.go:726]: This is the paring logic as code in the function `trackSkippedPV`, but there is a possibility that the `Pending` PVC are untracked from skipped state?

File: internal/volumehelper/volume_policy_helper.go [hunk 2]
```diff
@@ -140,6 +154,16 @@ func (v *volumeHelperImpl) ShouldPerformSnapshot(obj runtime.Unstructured, group
 			return false, err
 		}
 
+		// Check PVC-only skip policies before attempting to get the PV.
+		// This prevents errors for unbound PVCs that match phase-based skip policies.
+		if shouldSkip, err := v.checkPVCOnlySkip(pvc); err != nil {
```
Comment (blackpiglet) [inline internal/volumehelper/volume_policy_helper.go]: Because we now introduced a new VolumePolicy filter for the PVC phase, we shouldn't handle this as an error case.
IMO, we should allow the PV be empty instead of reporting error. Then let the volumePolicy's matched action to decide the result.

File: internal/volumehelper/volume_policy_helper.go [hunk 3]
```diff
@@ -230,6 +254,18 @@ func (v volumeHelperImpl) ShouldPerformFSBackup(volume corev1api.Volume, pod cor
 				v.logger.WithError(err).Errorf("fail to get PVC for pod %s", pod.Namespace+"/"+pod.Name)
 				return false, err
 			}
+
+			// Check PVC-only skip policies before attempting to get the PV.
+			// This prevents errors for unbound PVCs that match phase-based skip policies.
+			if shouldSkip, err := v.checkPVCOnlySkip(pvc); err != nil {
```
Comment (blackpiglet) [inline internal/volumehelper/volume_policy_helper.go]: Because we now introduced a new VolumePolicy filter for the PVC phase, we shouldn't handle this as an error case.
IMO, we should allow the PV be empty instead of reporting error. Then let the volumePolicy's matched action to decide the result.

File: pkg/backup/item_backupper.go [hunk 4]
```diff
@@ -687,6 +687,15 @@ func (ib *itemBackupper) getMatchAction(obj runtime.Unstructured, groupResource
 			return nil, errors.WithStack(err)
 		}
 
+		// First, check PVC-only policies (e.g., phase-based skip) before attempting PV lookup.
+		// This prevents errors for unbound PVCs that match phase-based skip policies.
+		vfdPVCOnly := resourcepolicies.NewVolumeFilterData(nil, nil, pvc)
```
Comment (blackpiglet) [inline pkg/backup/item_backupper.go]: No need to add an additional check here.

File: pkg/backup/item_backupper.go
Comment (blackpiglet) [inline pkg/backup/item_backupper.go:699]: We should allow pvName is empty, and let this line decide the result.

File: pkg/backup/item_backupper.go (hunk 1 above)
Comment (kaovilai) [reply pkg/backup/item_backupper.go:726]: The function is called `trackSkippedPV` It only track PV, not PVC. So there will be no PV to track if PVC is Pending.

Comment (blackpiglet) [reply pkg/backup/item_backupper.go:726]: If I understand correctly, unTrackSkippedPV is only called when a PVC is backed up successfully by PodVolume or by CSI plugin.
An unbound PVC should never be successfully backed up.
As a result, the code should never be touched.

If the backed-up PVC really doesn't have a PV, reporting error should be the expected behavior.

File: pkg/backup/item_backupper.go [hunk 5]
```diff
@@ -687,15 +687,14 @@ func (ib *itemBackupper) getMatchAction(obj runtime.Unstructured, groupResource
...
-		if err := ib.kbClient.Get(context.Background(), kbClient.ObjectKey{Name: pvName}, pv); err != nil {
-			return nil, errors.WithStack(err)
+		var pv *corev1api.PersistentVolume
+		if pvName := pvc.Spec.VolumeName; pvName != "" {
+			pv = &corev1api.PersistentVolume{}
+			if err := ib.kbClient.Get(context.Background(), kbClient.ObjectKey{Name: pvName}, pv); err != nil {
+				return nil, errors.WithStack(err)
+			}
 		}
+		// pv is nil for unbound PVCs - policy matching will use PVC-only conditions
```
Comment (blackpiglet) [inline pkg/backup/item_backupper.go]:
```suggestion
		// If pv is nil for unbound PVCs, policy matching will use PVC-only conditions
```

**Comment by blackpiglet** [comment]
@kaovilai 
Please do verify the modification works before merging the PR.

File: internal/volumehelper/volume_policy_helper.go [hunk 6]
```diff
@@ -142,8 +143,14 @@ func (v *volumeHelperImpl) ShouldPerformSnapshot(obj runtime.Unstructured, group
 
 		pv, err = kubeutil.GetPVForPVC(pvc, v.client)
 		if err != nil {
-			v.logger.WithError(err).Errorf("fail to get PV for PVC %s", pvc.Namespace+"/"+pvc.Name)
-			return false, err
+			if !errors.Is(err, kubeutil.ErrPVNotFoundForPVC) {
```
Comment (Lyndon-Li) [inline internal/volumehelper/volume_policy_helper.go]: It doesn't seem necessary to check `ErrPVNotFoundForPVC` explicitly.
It is almost impossible that PVC is in `bound` state but PV is not found.
So as long as `GetPVForPVC` returns error, we can say PV is not found.

Moreover, the error `ErrPVNotFoundForPVC` is misleading, because even if PV is not retrieved, it is also "PV not found".

File: pkg/backup/item_backupper.go [hunk 7]
```diff
@@ -709,6 +708,17 @@ func (ib *itemBackupper) trackSkippedPV(obj runtime.Unstructured, groupResource
 	if name, err := getPVName(obj, groupResource); len(name) > 0 && err == nil {
 		ib.backupRequest.SkippedPVTracker.Track(name, approach, reason)
 	} else if err != nil {
+		// For PVCs in Pending or Lost phase, it's expected that there's no PV name.
+		// Log at debug level instead of warning to reduce noise.
+		if groupResource == kuberesource.PersistentVolumeClaims {
```
Comment (Lyndon-Li) [inline pkg/backup/item_backupper.go]: This will break the existing logic:
When pendingPVC volumePolicy is not specified
For a PVC not in `Bound` status, the warning should still be there
However, the current code suppressed the warning all the time

Comment (Lyndon-Li) [reply pkg/backup/item_backupper.go]: I think we either need to remove the warning or we have the warning there all the time. In either case, we don't need this new code. cc @blackpiglet

File: pkg/backup/item_backupper.go
Comment (blackpiglet) [inline pkg/backup/item_backupper.go:683]: https://github.com/vmware-tanzu/velero/blob/386599638f67d3b53b1eb17bdad19ecbc017186f/pkg/podvolume/backupper.go#L211-L228

This function also needs to consider the PVC doesn't have PV condition.

File: pkg/backup/item_backupper.go (hunk 7 above)
Comment (blackpiglet) [reply pkg/backup/item_backupper.go]: The skipped PV's original issue is #5834.
The point is to track volumes are not backed up. 
If the PVC doesn't have bound PV, then there is no volume to track.

As a result, it's reasonable to remove the warning for PVC without PV.

Comment (kaovilai) [reply pkg/backup/item_backupper.go]: > For a PVC not in Bound status, the warning should still be there

There is conditional PVC phase check. for Bound PVC, it will warn like before.

File: pkg/backup/item_backupper.go
Comment (kaovilai) [reply pkg/backup/item_backupper.go:683]: addressed. tested working so far.

File: pkg/backup/item_backupper.go [hunk 8]
```diff
@@ -709,6 +708,17 @@ func (ib *itemBackupper) trackSkippedPV(obj runtime.Unstructured, groupResource
...
+			pvc := new(corev1api.PersistentVolumeClaim)
+			if convErr := runtime.DefaultUnstructuredConverter.FromUnstructured(obj.UnstructuredContent(), pvc); convErr == nil {
+				if pvc.Status.Phase == corev1api.ClaimPending || pvc.Status.Phase == corev1api.ClaimLost {
+					log.WithError(err).Debugf("unable to get PV name for %s PVC, skip tracking.", pvc.Status.Phase)
+					return
+				}
+			}
+		}
 		log.WithError(err).Warnf("unable to get PV name, skip tracking.")
```
Comment (blackpiglet) [inline pkg/backup/item_backupper.go]: Please modify the log level to info.
And we don't need the exception check above. 
As long as there is no PV print, add an info level here for tracking.

Comment (kaovilai) [reply pkg/backup/item_backupper.go]: resolved!

Comment (kaovilai) [reply pkg/backup/item_backupper.go]: removing exception check

**Review by blackpiglet — APPROVED** [review]

**Comment by Lyndon-Li** [comment]
@kaovilai Please help to cherry-pick this PR.

**Comment by kaovilai** [comment]
cherry-pick: https://github.com/vmware-tanzu/velero/pull/9537
