### PR TITLE
Wait the namespace deletion completed before removing the CRDs

### LINKED ISSUE #3974: Velero uninstall command cannot clean up all resources occasionally
The `uninstall` command is implemented by the following logic:
1. delete the `velero` namespace
2. delete all the CRDs

The root cause is that the API call to delete the namespace is an asynchronous process, which means that when we deleting the CRDs the namespace delete operation is still in progress, and the CRDs are needed for the namespace to list all related resources.

This causes some of the resources inside the `velero` namespace may not be cleaned up, and when we install the `velero` again, these remaining resources may affect the velero with unexpected behavior.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by ywk253100**
Wait the namespace deletion completed before removing the CRDs when uninstalling the velero

Fixes #3974

Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: changelogs/unreleased/4007-ywk253100 [hunk 1]
```diff
@@ -0,0 +1 @@
+Wait the namespace deletion completed before removing the CRDs when uninstalling the velero. This removes the `--wait` flag of the `uninstall` command
```
Comment (dsu-igeek) [inline changelogs/unreleased/4007-ywk253100:1]: Grammar nits - 
Wait for the namespace to be deleted before removing the CRDs during uninstall.
would be better for the first sentence

Comment (jenting) [inline changelogs/unreleased/4007-ywk253100:1]: What if the user using Velero CLI as a script.
Remove the flag probably makes the script failed.

File: pkg/cmd/cli/uninstall/uninstall.go [hunk 2]
```diff
@@ -159,33 +145,57 @@ func Run(ctx context.Context, kbClient kbclient.Client, namespace string, waitTo
 		}
 	}
 
-	if waitToTerminate && len(ns.Name) != 0 {
-		fmt.Println("Waiting for Velero uninstall to complete. You may safely press ctrl-c to stop waiting - uninstall will continue in the background.")
+	if kubeerrs.NewAggregate(errs) != nil {
+		fmt.Printf("Errors while attempting to uninstall Velero: %q", kubeerrs.NewAggregate(errs))
```
Comment (dsu-igeek) [inline pkg/cmd/cli/uninstall/uninstall.go:149]: I think this needs a \n at the end

File: pkg/cmd/cli/uninstall/uninstall.go [hunk 3]
```diff
@@ -88,31 +86,19 @@ Use '--force' to skip the prompt confirming if you want to uninstall Velero.
...
-		} else {
-			if err := kbClient.Delete(ctx, ns); err != nil {
-				errs = append(errs, errors.WithStack(err))
-			}
-		}
+func Run(ctx context.Context, kbClient kbclient.Client, namespace string) error {
+	// The CRDs cannot be cleaned up before the namespace being deleted to avoid the issue https://github.com/vmware-tanzu/velero/issues/3974
+	// So we stop the deletion to continue here
+	if err := deleteNamespace(ctx, kbClient, namespace); err != nil {
+		fmt.Printf("Errors while attempting to uninstall Velero: %q", err)
```
Comment (dsu-igeek) [inline pkg/cmd/cli/uninstall/uninstall.go:93]: This needs a \n right?

File: pkg/cmd/cli/uninstall/uninstall.go [hunk 4]
```diff
@@ -88,31 +86,19 @@ Use '--force' to skip the prompt confirming if you want to uninstall Velero.
...
-	} else {
-		if ns.Status.Phase == corev1.NamespaceTerminating {
-			fmt.Printf("Velero namespace %q is terminating.\n", namespace)
-		} else {
-			if err := kbClient.Delete(ctx, ns); err != nil {
-				errs = append(errs, errors.WithStack(err))
-			}
-		}
+func Run(ctx context.Context, kbClient kbclient.Client, namespace string) error {
+	// The CRDs cannot be cleaned up before the namespace being deleted to avoid the issue https://github.com/vmware-tanzu/velero/issues/3974
```
Comment (dsu-igeek) [inline pkg/cmd/cli/uninstall/uninstall.go:90]: Grammar rewrite:
The CRDs cannot be removed until the namespace is deleted to avoid the problem in issue https://github.com/vmware-tanzu/velero/issues/3974 so if the namespace deletion fails we error out here

File: pkg/cmd/cli/uninstall/uninstall.go [hunk 5]
```diff
@@ -159,33 +145,57 @@ func Run(ctx context.Context, kbClient kbclient.Client, namespace string, waitTo
...
 		}
-
-		wait.Until(checkFunc, 5*time.Millisecond, ctx.Done())
+		fmt.Print(".")
 	}
 
-	if kubeerrs.NewAggregate(errs) != nil {
-		fmt.Printf("Errors while attempting to uninstall Velero: %q", kubeerrs.NewAggregate(errs))
-		return kubeerrs.NewAggregate(errs)
+	// Must wait until the namespace to be deleted to avoid the issue https://github.com/vmware-tanzu/velero/issues/3974
```
Comment (dsu-igeek) [inline pkg/cmd/cli/uninstall/uninstall.go:193]: Grammar rewrite
"to be deleted" -> "is deleted"

**Review by dsu-igeek — CHANGES_REQUESTED** [review]
Thanks for getting this done, some small changes, thanks!

File: changelogs/unreleased/4007-ywk253100 (hunk 1 above)
Comment (ywk253100) [reply changelogs/unreleased/4007-ywk253100]: Yes, this may break the scripts using the velero cli. But the `--wait` option is indeed useless after the changes

Comment (ywk253100) [reply changelogs/unreleased/4007-ywk253100]: cc @dsu-igeek

**Comment by ywk253100** [comment]
@dsu-igeek I have updated the PR according to the comments, please take a look again

**Review by sseago — DISMISSED** [review]

File: changelogs/unreleased/4007-ywk253100 (hunk 1 above)
Comment (jenting) [reply changelogs/unreleased/4007-ywk253100]: I think probably we could ignore the `--wait` flag (add the deprecated message in the flag help message) rather than directly removes the flag because it'll cause the command error out especially for the user running this command by a script tool.

Comment (sseago) [reply changelogs/unreleased/4007-ywk253100]: @jenting I would be OK with that. `--wait` would still result in the desired waiting, but since we're always waiting, it just becomes a no-op.

Comment (jenting) [reply changelogs/unreleased/4007-ywk253100]: Yes, so I think we could keep the flag `--wait` but ignores it since Velero always waiting.

Comment (ywk253100) [reply changelogs/unreleased/4007-ywk253100]: @jenting @sseago @dsu-igeek I have updated the PR to make the `--wait` as a no-op, please take a look again

**Review by jenting — APPROVED** [review]
LGTM, thank u.

File: pkg/cmd/cli/uninstall/uninstall.go [hunk 6]
```diff
@@ -62,11 +63,13 @@ func NewCommand(f client.Factory) *cobra.Command {
 		Long: `Uninstall Velero along with the CRDs and clusterrolebinding.
 
 The '--namespace' flag can be used to specify the namespace where velero is installed (default: velero).
-Use '--wait' to wait for the Velero uninstall to be ready before proceeding.
 Use '--force' to skip the prompt confirming if you want to uninstall Velero.
 		`,
 		Example: ` # velero uninstall --namespace staging`,
 		Run: func(c *cobra.Command, args []string) {
+			if o.wait {
+				fmt.Println("Warning: the \"--wait\" option is deprecated and will be removed in the future release. The uninstall command always waits the uninstall to be ready currently.")
```
Comment (dsu-igeek) [inline pkg/cmd/cli/uninstall/uninstall.go:71]: will be removed in the future release -> will be removed in a future release

waits the uninstall to be ready currently. -> waits for the uninstall to complete

**Review by dsu-igeek — CHANGES_REQUESTED** [review]
Looks good, please update the one area.  Thanks!

**Review by jenting — APPROVED** [review]

**Review by sseago — APPROVED** [review]

**Review by dsu-igeek — APPROVED** [review]
LGTM, thanks
