### PR TITLE
Sanitize Azure HTTP responses in BSL status messages

### LINKED ISSUE #8368: BSL status.message field shouldn't have the http response as output when bucket doesn't exist
**What steps did you take and what happened:**

Created a BSL with non existing bucket on azure platform. I noticed status.Message field has http response as output.  This issue doesn't happen in case of GCP and AWS.  Attached details below:- 

```
$ oc get bsl test -o yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  creationTimestamp: "2024-11-04T08:42:12Z"
  generation: 411
  labels:
    app.kubernetes.io/component: bsl
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: oadp-operator
    app.kubernetes.io/name: oadp-operator-velero
    openshift.io/oadp: "True"
    openshift.io/oadp-registry: "True"
  name: test
  namespace: openshift-adp
  ownerReferences:
  - apiVersion: oadp.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: DataProtectionApplication
    name: ts-dpa
    uid: 2ea57ddc-82bd-4131-a124-b0370d6f96f9
  resourceVersion: "114647"
  uid: 23759d8f-1d1d-496a-9882-c44ee56f3cc4
spec:
  config:
    resourceGroup: <resource group>
    storageAccount: oadp100711zl59k
    storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
    subscriptionId: <subscription>
  credential:
    key: cloud
    name: cloud-credentials-azure
  default: true
  objectStorage:
    bucket: oadp100711zl59k1
    prefix: velero
  provider: azure
status:
  lastSyncedTime: "2024-11-04T12:22:36Z"
  lastValidationTime: "2024-11-04T12:23:04Z"
  message: "BackupStorageLocation \"test\" is unavailable: rpc error: code = Unknown
    desc = GET https://oadp100711zl59k.blob.core.windows.net/oadp100711zl59k1\n--------------------------------------------------------------------------------\nRESPONSE
    404: 404 The specified container does not exist.\nERROR CODE: ContainerNotFound\n--------------------------------------------------------------------------------\n\uFEFF<?xml
    version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ContainerNotFound</Code><Message>The
    specified container does not exist.\nRequestId:63cf34d8-801e-0078-09b4-2e4682000000\nTime:2024-11-04T12:23:04.5623627Z</Message></Error>\n--------------------------------------------------------------------------------\n"
  phase: Unavailable
```

**What did you expect to happen:**

Status.Message shouldn't return the http response as output. 

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  velero 1.14
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): v1.29.9+5865c5b
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
## What this PR does / why we need it

Fixes the issue where Azure BackupStorageLocation status messages contain verbose HTTP response details and XML, making them difficult to read. This PR adds error sanitization to extract only the error code and meaningful message.

## Which issue(s) this PR fixes

Fixes #8368

## Before this change

When a BSL with a non-existent Azure bucket is created, the status message shows the full HTTP response:

```
BackupStorageLocation "test" is unavailable: rpc error: code = Unknown desc = GET https://oadp100711zl59k.blob.core.windows.net/oadp100711zl59k1
--------------------------------------------------------------------------------
RESPONSE 404: 404 The specified container does not exist.
ERROR CODE: ContainerNotFound
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:63cf34d8-801e-0078-09b4-2e4682000000
Time:2024-11-04T12:23:04.5623627Z</Message></Error>
--------------------------------------------------------------------------------
```

## After this change

The status message is clean and concise:

```
BackupStorageLocation "test" is unavailable: rpc error: code = Unknown desc = ContainerNotFound: The specified container does not exist.
```

## Implementation details

- Added `sanitizeStorageError()` function that detects Azure-style HTTP response errors (containing "RESPONSE" and "ERROR CODE:" patterns)
- Extracts error code and meaningful message using regex
- Preserves AWS/GCP-style errors unchanged
- Maintains the gRPC error prefix structure

## Testing

- Added comprehensive unit tests covering various scenarios:
  - Nil errors
  - Simple/AWS-style errors (passed through unchanged)
  - Azure container not found with full HTTP response
  - Azure blob not found
  - Azure errors with plain text (no XML)
  - Azure errors with error code but no XML message
- All existing tests continue to pass

## Checklist

- [x] Accepted the DCO. Commits are signed-off.
- [x] Created a changelog file or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main` (if applicable).

### CODE REVIEW

File: pkg/controller/backup_storage_location_controller.go [hunk 1]
```diff
@@ -127,7 +219,7 @@ func (r *backupStorageLocationReconciler) Reconcile(ctx context.Context, req ctr
 				err = errors.Wrapf(err, "BackupStorageLocation %q is unavailable", location.Name)
 				unavailableErrors = append(unavailableErrors, err.Error())
 				location.Status.Phase = velerov1api.BackupStorageLocationPhaseUnavailable
-				location.Status.Message = err.Error()
+				location.Status.Message = sanitizeStorageError(err)
```
Comment (ywk253100) [inline pkg/controller/backup_storage_location_controller.go:229]: How about we implement the logic on Azure plugin side? It is Azure specific logic

**Comment by priyansh17** [comment]
> func (s *objectBackupStore) IsValid() error

This return plain error object, which is used in Reconciler anonymous function.

> func (r *backupStorageLocationReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error)

I have noticed during logging in logReconciledPhase:
we log the same such as this:
```
Current BackupStorageLocations available/unavailable/unknown: 0/1/0, BackupStorageLocation "default" is unavailable: rpc error: code = Unknown desc = GET https://test01.blob.core.windows.net/az-blob-aks-test
--------------------------------------------------------------------------------
RESPONSE 403: 403 This request is not authorized to perform this operation using this permission.
ERROR CODE: AuthorizationPermissionMismatch
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:<GUID>
Time:2025-10-21T14:00:15.9852582Z</Message></Error>
--------------------------------------------------------------------------------
) :: {}
```

will these get masked as well?

File: pkg/controller/backup_storage_location_controller.go [hunk 2]
```diff
@@ -127,7 +219,7 @@ func (r *backupStorageLocationReconciler) Reconcile(ctx context.Context, req ctr
 				err = errors.Wrapf(err, "BackupStorageLocation %q is unavailable", location.Name)
 				unavailableErrors = append(unavailableErrors, err.Error())
```
Comment (priyansh17) [inline pkg/controller/backup_storage_location_controller.go]: Should we not sanitize it here itself before appending?

File: pkg/controller/backup_storage_location_controller.go [hunk 3]
```diff
@@ -46,6 +47,97 @@ const (
 	bslValidationEnqueuePeriod = 10 * time.Second
 )
 
+// sanitizeStorageError cleans up verbose HTTP responses from cloud provider errors,
+// particularly Azure which includes full HTTP response details and XML in error messages.
+// It extracts the error code and message while removing HTTP headers and response bodies.
+func sanitizeStorageError(err error) string {
```
Comment (anshulahuja98) [inline pkg/controller/backup_storage_location_controller.go:54]: can we also enhance this function to use storage sas regex and remove secrets from being shown in status/ logging.

File: pkg/controller/backup_storage_location_controller.go (hunk 1 above)
Comment (shubham-pampattiwar) [reply pkg/controller/backup_storage_location_controller.go:229]: @ywk253100 I am unsure about that. The sanitization is about cleaning user-facing messages, not Azure-specific business logic.

Comment (shubham-pampattiwar) [reply pkg/controller/backup_storage_location_controller.go:229]: I thought about this, but I think the controller is the right place for a few reasons:

- This is really about cleaning up the status message we show users, not about Azure-specific business logic. The controller owns the status field.
- The function already checks if it looks like an Azure error and passes everything else through unchanged. So it won't break other providers.
- If we put it in the plugin, we'd need to change the velero-plugin-for-microsoft-azure repo separately. And if GCP or AWS have similar issues later, we'd have to fix each plugin individually.
- This also sets us up for the secret scrubbing enhancement that @anshulahuja98 suggested - easier to do in one place.
Does that make sense, What do you think, open to hear suggestions.

File: pkg/controller/backup_storage_location_controller.go (hunk 2 above)
Comment (shubham-pampattiwar) [reply pkg/controller/backup_storage_location_controller.go]: Done

File: pkg/controller/backup_storage_location_controller.go (hunk 3 above)
Comment (shubham-pampattiwar) [reply pkg/controller/backup_storage_location_controller.go:54]: Done

File: pkg/controller/backup_storage_location_controller.go (hunk 1 above)
Comment (kaovilai) [reply pkg/controller/backup_storage_location_controller.go:229]: I think the thought is that each storage plugin should individually self-contain function/status message cleanups, since that's why we have plugin system in the first place.

But if code is heavily reusable with secret scrubbing then that's a good compromise.

**Review by kaovilai — APPROVED** [review]

**Comment by shubham-pampattiwar** [comment]
Review request reminder: @ywk253100 @priyansh17 @kaovilai

**Review by kaovilai — APPROVED** [review]

**Review by ywk253100 — APPROVED** [review]
