### PR TITLE
issue 8649: host_pods should not be mandatory to node-agent

### LINKED ISSUE #8649: host_pods should not be mandatory to node-agent after 1.15
There is a logic to check the existence of `host_pods` volume in node-agent pods when node-agent starts. If this volume is absent, node-agent pods will not start.
From 1.15, we have moved the data mover execution to dedicated pods, so data mover backup/restore don't rely on the `host_pods` volume. It is only required by fs-backup.

Therefore,  we should not fail the node-agent pods if the `host_pods` volume is not there considering users may use node-agent for data mover backup/restore only.

### LINKED ISSUE #8769: Declarative schedule fails to run
**What steps did you take and what happened:**
I am deploying velero using helm chart and ArgoCD. When I deploy velero, create a schedule, and create a backup from the schedule the backup runs fine But if I define that same schedule declartivel using helm chart values, the schedule is create but backups from them do not work. I fact they are not created at all

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
I would add a bundle but the backup does not exist.

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.15.2
- Velero features (use `velero client config get features`): features: <NOT SET> but CSI Enabled is in my config
- Kubernetes version (use `kubectl version`): 1.30.9
- Kubernetes installer & version: 1.30.9 
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by mpryc**
Fixes #8649. The host_pods path should not be mandatory for node-agent.

This update enables the node-agent to start even if the /host_pods path does not exist. If the path is present, the existing logic remains unchanged, ensuring it is readable.

This PR does not address mounting (or omitting) the /host_pods directory.

Additionally, this change specifically resolves #8649 and not #8185, which requires further design work and will be handled in a separate PR.

### CODE REVIEW

**Comment by kaovilai** [comment]
Don't be alarmed about e2e tests.. unrelated to PR https://github.com/vmware-tanzu/velero/issues/8766

File: pkg/cmd/cli/nodeagent/server.go [hunk 1]
```diff
@@ -247,7 +249,13 @@ func newNodeAgentServer(logger logrus.FieldLogger, factory client.Factory, confi
 	if err != nil {
 		return nil, err
 	}
-	if err := s.validatePodVolumesHostPath(s.kubeClient); err != nil {
+
+	exists, err := s.fileSystem.DirExists(defaultHostPodsPath)
```
[the remark this answers is not in the document]
Comment (mpryc) [reply pkg/cmd/cli/nodeagent/server.go]: I removed that part and moved the logic to check if the folder exists inside `validatePodVolumesHostPath`. The check now relies on the `ReadDir` error, comparing it against `os.ErrNotExist`. I believe this approach is still valid and necessary, as other errors, such as permission issues, could also cause failures when the user expects the fs-backup to work.

File: pkg/cmd/cli/nodeagent/server.go [hunk 2]
```diff
@@ -414,8 +416,12 @@ func (s *nodeAgentServer) waitCacheForResume() error {
 // validatePodVolumesHostPath validates that the pod volumes path contains a
 // directory for each Pod running on this node
 func (s *nodeAgentServer) validatePodVolumesHostPath(client kubernetes.Interface) error {
-	files, err := s.fileSystem.ReadDir("/host_pods/")
+	files, err := s.fileSystem.ReadDir(defaultHostPodsPath)
 	if err != nil {
+		if errors.Is(err, os.ErrNotExist) {
+			s.logger.Warnf("Could not read pod volumes host path, fs-backup disabled %s", defaultHostPodsPath)
```
Comment (Lyndon-Li) [inline pkg/cmd/cli/nodeagent/server.go:422]: How about this log to clearly tell host path doesn't exist:
`Pod volumes host path [%s] doesn't exist, fs-backup is disabled`

Comment (mpryc) [reply pkg/cmd/cli/nodeagent/server.go]: Changed, Thanks !

**Comment by mpryc** [comment]
Squashed the 3 changes to make downstream cherry-pick clean.

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

**Review by Lyndon-Li — APPROVED** [review]
