### PR TITLE
Adjust the logic for the backup_last_status metric to stop incorrectly incrementing over time

### LINKED ISSUE #7378: v1.13.0 changes velero_backup_last_status metric
**What steps did you take and what happened:**

After upgrading to velero v1.13.0, the velero_backup_last_status metric seems to have changed.

Before, the metric was constant:
Bildschirmfoto 2024-02-02 um 10 34 27

Now, it is constantly increasing until the next backup is run:
Bildschirmfoto 2024-02-02 um 10 28 21

The last backup did complete without any issues:
````
velero-my-backup-20240202020000   Completed   0        0          2024-02-02 03:00:00 +0100 CET   27d       default            <none>
`````

**What did you expect to happen:**
The metric stays the same.

**The following information will help us better understand what's going on**:
The issue occurs directly after the update, without a new backup being created.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  v1.13.0
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.28.4-eks-8cb36c9
- Cloud provider or hardware configuration: aws eks 1.28
- OS (e.g. from `/etc/os-release`): amazon_linux:2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by allenxu404**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #7378

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by blackpiglet — APPROVED** [review]

File: pkg/metrics/metrics.go [hunk 1]
```diff
@@ -468,7 +468,7 @@ func (m *ServerMetrics) InitSchedule(scheduleName string) {
 		c.WithLabelValues(scheduleName).Add(0)
 	}
 	if c, ok := m.metrics[backupLastStatus].(*prometheus.GaugeVec); ok {
-		c.WithLabelValues(scheduleName).Add(1)
+		c.WithLabelValues(scheduleName).Set(float64(1))
```
Comment (Snaipe) [inline pkg/metrics/metrics.go:471]: Found this PR when trying to figure out why the metric was increasing; if I understand correctly, this ends up running periodically (every time the schedule is reconciled), right?

If so, wouldn't this incorrectly clear a failing status? Say that the schedule created a backup that failed, the metric would become 0, and then get reset back to 1 after a couple of minutes, which seems problematic since this can hide failures.

If anything, I think lines 470-471 should be omitted entirely. This would prevent from emitting a data point until the point where we actually have one, which should still fix what #6838 was aiming for. If an accurate status must be set, it should be done as part of scheduleReconciler.Reconcile, using the status of the last backup created by the schedule.

Comment (allenxu404) [reply pkg/metrics/metrics.go:471]: @Snaipe yes, you're right.

This PR only aimed to address the specific bug caused in https://github.com/vmware-tanzu/velero/pull/6838. I will create a separate PR to resolve the issue with incorrect failure status clear and keep you posted. Thanks for highlighting this larger problem!

The purpose of setting the default value of backup_last_status to 1  was to prevent mistaken failure reports that could occur if the code exits without updating that metric. I prefer to leave that implementation unchanged. Upon further analysis, I think the true underlying issue seems to be that metrics are re-initialized each time the schedule is reconciled, instead, the metrics should be initialized only if a new backup is due to be created.  So I think the `InitSchedule`function would be better placed below, where backups are created, to avoid unnecessary reset.  what's your thought?
```
       if c.ifDue(schedule, cronSchedule) && !c.checkIfBackupInNewOrProgress(schedule) {
		if err := c.submitBackup(ctx, schedule); err != nil {
			return ctrl.Result{}, errors.Wrapf(err, "error submit backup for schedule %s", req.String())
		}
		c.metrics.InitSchedule(schedule.Name)
	}
```

Comment (Snaipe) [reply pkg/metrics/metrics.go:471]: I think it'd help, but I'm not sure it would fix the underlying problem. As far as I can tell, what this would do is that if your schedule is failing, and a new backup is created, then the schedule would be reported as "fixed" metrics-wise for the entire duration of the backup.

It's less bad than the first situation, but it would definitely confuse alerting.

I think not advertising a value for the metric up until the point where there is a data point seems slightly better in the sense that users can choose to ignore them or set it to the default value of their choice (0 or 1) in grafana/alertmanager. A better solution would be to set the initial value of the metric directly to the result of the last backup of the schedule.

Comment (allenxu404) [reply pkg/metrics/metrics.go:471]: > A better solution would be to set the initial value of the metric directly to the result of the last backup of the schedule.

I agree, will raise another issue to track it.

Comment (allenxu404) [reply pkg/metrics/metrics.go:471]: Seems we've already has the similar issue to track: https://github.com/vmware-tanzu/velero/issues/6936
