### PR TITLE
Fixed backup deletion bug related to async operations

### LINKED ISSUE #6035: [BIA V2] Backups with in progress async operation could should not be allowed to delete
There is an existing logic in Velero to prevent in progress backups from being deleted:
https://github.com/vmware-tanzu/velero/blob/1d8ca4f2efc512014c14e2e6ea5d6a7980d60fd3/pkg/controller/backup_deletion_controller.go#L160

However, this doesn't work for backups with in progress async operation since at the time of the async operation starts, the normal backup progress quits so `backupTracker` is cleared.

Actually, the backups in the `WaitingForPluginOperations` phase should not be allowed to be deleted as well, otherwise, the ongoing async operation will be orphan.

### PR DESCRIPTION
**Pull request by sseago**
Thank you for contributing to Velero!

# Please add a summary of your change
Remove backup from backup tracker in finalize rather than in backup controller.

# Does your change fix a particular issue?

Fixes #6035

# Please indicate you've done the following:

- [ x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/controller/backup_controller.go [hunk 1]
```diff
@@ -267,7 +267,6 @@ func (b *backupReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctr
 	}
 
 	b.backupTracker.Add(request.Namespace, request.Name)
-	defer b.backupTracker.Delete(request.Namespace, request.Name)
```
Comment (Lyndon-Li) [inline pkg/controller/backup_controller.go:270]: Previously, the behavior is like --- as long as the execution reaches here, and when it quits for whatever reason, the backupTracker will always be deleted.
Now, if we change like this, if someone insert some code between line 270 and 290 to return earlier, the backupTracker will not be deleted for that code. As a result, the backup will never be deletable for that case.

File: pkg/controller/backup_finalizer_controller.go [hunk 2]
```diff
@@ -165,6 +168,7 @@ func (r *backupFinalizerReconciler) Reconcile(ctx context.Context, req ctrl.Requ
 			return ctrl.Result{}, errors.WithStack(err)
 		}
 	}
+	defer r.backupTracker.Delete(backup.Namespace, backup.Name)
```
Comment (Lyndon-Li) [inline pkg/controller/backup_finalizer_controller.go:171]: This is similar to the above comment.
If the finalizer reconcile error out before here at line 171, the backupTracker will not be deleted, as a result, the backup will never be deletable.

File: pkg/controller/backup_controller.go (hunk 1 above)
Comment (Lyndon-Li) [reply pkg/controller/backup_controller.go:270]: One suggest here is that we still use the defer function, but inside it, we check the phase is not `WaitForAsyncOperation` then we delete the backupTracker.

Comment (sseago) [reply pkg/controller/backup_controller.go:270]: @Lyndon-Li That works too. I wanted to make sure we only closed it for terminal phases, but you're right -- putting that check in the defer func is cleaner. I'll update the PR.

File: pkg/controller/backup_finalizer_controller.go (hunk 2 above)
Comment (sseago) [reply pkg/controller/backup_finalizer_controller.go:171]: In this case, that is deliberate, as the backup won't be in a terminal state if the  func errors out here. However, I'll do the same here as above -- defer statement early, but check for terminal states before removing.

File: pkg/controller/backup_finalizer_controller.go [hunk 3]
```diff
@@ -102,6 +105,10 @@ func (r *backupFinalizerReconciler) Reconcile(ctx context.Context, req ctrl.Requ
 
 	original := backup.DeepCopy()
 	defer func() {
+		switch original.Status.Phase {
```
Comment (Lyndon-Li) [inline pkg/controller/backup_finalizer_controller.go:108]: I think we need to check `backup.Status.Phase`? because this one is to be updated in the code following

**Review by Lyndon-Li — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]
