### PR TITLE
Fix #6752: add namespace exclude check.

### LINKED ISSUE #6752: Velero backs up namespace resources in the exclude list
**What steps did you take and what happened:**

If you take a full cluster backup and specify some namespaces under `.spec.excludedNamespaces` those namespaces are still backed up (I'm taking about the namespaces themselves and not the resources within the namespaces).

For example, search for "kube-system" in this backup describe output: https://pastebin.com/iLyiPZhg

This was not the behavior on 1.10.3 so perhaps a regression.

**What did you expect to happen:**

Excluded namespaces not to be backed up.

**The following information will help us better understand what's going on**:

NA

**Anything else you would like to add:**

NA

**Environment:**

- Velero version (use `velero version`): 1.12 rc1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by blackpiglet**
Thank you for contributing to Velero!

# Please add a summary of your change
Fix #6752 
Add the namespace exclude check to avoid all namespaces listed in the backup.
Also, add the PSA warning and audit label to avoid prompting warning messages and audit events.

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by Lyndon-Li — DISMISSED** [review]

**Review by sseago — DISMISSED** [review]

**Review by Lyndon-Li — APPROVED** [review]

File: pkg/backup/item_collector.go [hunk 1]
```diff
@@ -289,7 +289,7 @@ func (r *itemCollector) getResourceItems(log logrus.FieldLogger, gv schema.Group
 			return nil, errors.WithStack(err)
 		}
 
-		items := r.backupNamespaces(unstructuredList, namespacesToList, gr, preferredGVR, log)
+		items := r.backupNamespaces(unstructuredList, r.backupRequest.NamespaceIncludesExcludes, gr, preferredGVR, log)
```
Comment (reasonerjt) [inline pkg/backup/item_collector.go:292]: if `namespacesToList` is not used in this chunk we should move it closer to the chunk it's used.
Same applies to `clusterScoped`

Comment (blackpiglet) [reply pkg/backup/item_collector.go:289]: Modified.

**Review by reasonerjt — APPROVED** [review]

**Review by Lyndon-Li — APPROVED** [review]
