### PR TITLE
Add test coverage and fix validation for MRAP ARN bucket names

### LINKED ISSUE #9544: Add test coverage for S3 bucket name in MRAP (Multi-Region Access Point) ARN notation
## Summary

Velero currently lacks test coverage for scenarios where the S3 bucket name is specified using an AWS Multi-Region Access Point (MRAP) ARN instead of a traditional bucket name.

## Background

AWS S3 Multi-Region Access Points allow specifying an ARN in place of a bucket name for S3 API operations. The ARN format is:

```
arn:aws:s3::{account-id}:accesspoint/{mrap-alias}.mrap
```

For example:
```
arn:aws:s3::123456789012:accesspoint/abcdef0123456.mrap
```

This ARN is passed directly as the `--bucket` parameter in S3 API calls, replacing the traditional bucket name. See the [AWS documentation on MRAP operations](https://docs.aws.amazon.com/AmazonS3/latest/userguide/MrapOperations.html#get-object-mrap) for details.

## What needs to be done

- Add unit/integration tests that exercise Velero's backup and restore paths when the BSL (Backup Storage Location) bucket is configured with an MRAP ARN instead of a regular bucket name.
- Verify that bucket name validation, parsing, and any string manipulation logic (e.g., path construction, prefix handling) correctly handles the ARN format, which contains colons and slashes that differ from standard bucket names.
- Ensure that any code that constructs S3 API requests properly passes the MRAP ARN as the bucket parameter without modification.

## Why this matters

Users who rely on MRAP for multi-region failover and routing may configure their Velero BSL with an MRAP ARN. Without test coverage, regressions in ARN handling could go undetected and break these configurations.

> [!Note]
> Responses generated with Claude

### PR DESCRIPTION
**Pull request by testsabirweb**
Thank you for contributing to Velero!

# Please add a summary of your change

AWS S3 Multi-Region Access Points (MRAP) allow specifying an ARN in place of a 
traditional bucket name. The ARN format looks like:
```bash
arn:aws:s3::{account-id}:accesspoint/{mrap-alias}.mrap
```

Velero's BSL bucket validation was rejecting these ARNs with the error:

> backup storage location's bucket name "arn:aws:s3::..." must not contain a '/'

This is because ARNs legitimately contain a `/` as part of their path syntax, 
which is different from a user accidentally putting `<bucket>/<prefix>` in the 
bucket field.

This PR:
- Fixes the validation in `objectBackupStoreGetter.Get()` to exempt bucket names 
  starting with `arn:` from the slash check
- Adds unit tests covering MRAP ARN bucket names (plain ARN and ARN with a trailing slash)

# Does your change fix a particular issue?

Fixes #9544

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by testsabirweb** [comment]
Hi Team ,
While writing the tests for this issue, I found that the MRAP ARN test case 
actually failed against the existing code — not just missing coverage but an 
active bug.

The bucket validation in `objectBackupStoreGetter.Get()` rejects any bucket 
name containing a `/`, which was meant to catch accidental `<bucket>/<prefix>` 
input from users. But MRAP ARNs like `arn:aws:s3::123456789012:accesspoint/alias.mrap` 
have a `/` as part of their ARN syntax, so they were being rejected with:

> backup storage location's bucket name "arn:aws:s3::..." must not contain a '/'

I've included a one-line fix alongside the tests to exempt bucket names starting 
with `arn:` from this check. Happy to split this into a separate PR if preferred.

File: changelogs/unreleased/9554-testsabirweb [hunk 1]
```diff
@@ -0,0 +1 @@
+Issue #9544: Add test coverage for S3 bucket name in MRAP ARN notation and fix bucket validation to accept ARN format
```
Comment (blackpiglet) [inline changelogs/unreleased/9554-testsabirweb:1]: The changelog file name should match the PR number.
It should be 9554-testsabirweb

File: pkg/persistence/object_store_mrap_test.go [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+limitations under the License.
+*/
+
+package persistence
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
```
Comment (blackpiglet) [inline pkg/persistence/object_store_mrap_test.go]: Please add a blank line here.

**Review by blackpiglet — DISMISSED** [review]

File: pkg/persistence/object_store.go [hunk 3]
```diff
@@ -149,7 +149,8 @@ func (b *objectBackupStoreGetter) Get(location *velerov1api.BackupStorageLocatio
 	// if there are any slashes in the middle of 'bucket', the user
 	// probably put <bucket>/<prefix> in the bucket field, which we
 	// don't support.
-	if strings.Contains(bucket, "/") {
+	// Exception: MRAP ARNs (arn:aws:s3::...) legitimately contain slashes.
+	if strings.Contains(bucket, "/") && !strings.HasPrefix(bucket, "arn:") {
```
Comment (reasonerjt) [inline pkg/persistence/object_store.go]: How about. making it more restrictive, such as:
`HasPrefix(bucket, "arn:aws:s3:")`

Comment (testsabirweb) [reply pkg/persistence/object_store.go]: Thanks for the suggestion, I've applied it.

Using `arn:aws:s3:` instead of `arn:` is better because:

- It restricts the slash exception to S3 ARNs only (e.g. MRAP), which are the only valid "bucket" values that contain a `/`.
- With just `arn:`, we'd also allow any other ARN (e.g. IAM role ARNs with slashes`arn:aws:iam::123456789012:role/my-role`), which could hide user mistakes.

**Comment by testsabirweb** [comment]
Hi @kaovilai @blackpiglet , 
can we merge this?
