### PR TITLE
Don't include excluded items in ItemBlocks

### LINKED ISSUE #8510: After upgrade to 1.15, volumes are not excluded but PVC's are, with the exclude label set
**What steps did you take and what happened:**
This has been detected as a regression in our automated test suite after upgrading from 1.14 to 1.15.

We have a set of pods with their PVCs, some of which we label with `velero.io/exclude-from-backup=true`.
Since the upgrade to 1.15, all the volumes are being backed up, even those for the annotated PVCs.

**What did you expect to happen:**
The volumes corresponding to PVCs with the `velero.io/exclude-from-backup=true` should not have been backed up.

**The following information will help us better understand what's going on**:

From the velero logs, we can see that the PVC `cluster-velero-e2e-3` is being excluded.

```
    time="2024-12-10T08:38:37Z" level=info
.   msg="Excluding item because it has label velero.io/exclude-from-backup=true"
.   backup=velero/cluster-velero-e2e-backup-1 logSource="pkg/backup/item_backupper.go:115"
.   name=cluster-velero-e2e-3 namespace=velero-e2e-8546
.   resource=persistentvolumeclaims
```

However, the corresponding volumes are being backed up.

```
    time="2024-12-10T08:38:37Z" level=info
.   msg="Backing up item"
.   backup=velero/cluster-velero-e2e-backup-1 logSource="pkg/backup/item_backupper.go:184"
.   name=pvc-cd84b2c0-c8ee-41f2-98ea-e4b803d21351 namespace= resource=persistentvolumes

    time="2024-12-10T08:38:37Z" level=info
.   msg="Executing takePVSnapshot"
.   backup=velero/cluster-velero-e2e-backup-1
.   logSource="pkg/backup/item_backupper.go:549"
.   name=pvc-cd84b2c0-c8ee-41f2-98ea-e4b803d21351 namespace= resource=persistentvolumes
```

And in the `backup describe` we can see there are 6 volumes, where there should only be 2:

```
    Backup Volumes:
      Velero-Native Snapshots:
        pvc-6db130db-fe12-4a8c-a7eb-c5eb5b9b7641: specify --details for more information
        pvc-25019cca-05ba-4f9e-919e-39dcc4ae172a: specify --details for more information
        pvc-6b2024a6-34cd-4aed-9cca-54387a024162: specify --details for more information
        pvc-60febcb2-4621-4c73-81e9-77935226bdb7: specify --details for more information
        pvc-68ede3fe-b20c-486f-8681-0ca8c0145bc4: specify --details for more information
        pvc-22333a02-55c3-45bd-bada-438732491e19: specify --details for more information
```

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.15.0 (plus AWS Plugin v1.11.0)
- Velero features (use `velero client config get features`):  `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): 1.28 through 1.31
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Amazon EKS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by sseago**
Thank you for contributing to Velero!

# Please add a summary of your change
Run itemExclusionChecks before adding items to ItemBlocks. Fixes a regression in 1.15 where excluding PVCs from backup no longer excludes associated PVs.

# Does your change fix a particular issue?

Fixes #8510

# Please indicate you've done the following:

- [x ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [x ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by sseago** [comment]
I haven't tested this locally yet. I need to rebuild my cluster tomorrow and then I'll test.

**Comment by Lyndon-Li** [comment]
@sseago
Thanks for the quick fix. We are planning to create another quick patch 1.15.2 and this PR is included.
So hopefully this PR could be ready earlier next week, let us know if you need any help. Thanks.

**Comment by sseago** [comment]
@Lyndon-Li I was hoping to test the PR in a cluster environment today, but I ended up having to fix some problems with the PR (updated now) as well as rebuild my aws cluster. My plan is to test the PR on Monday, in the meantime it should be ready to review (but I want to do the testing on Monday before merging anything -- I want to make sure the change actually fixes the problem reported -- with PVC labeled for exclude but no labels on PV.

**Comment by Lyndon-Li** [comment]
> @Lyndon-Li I was hoping to test the PR in a cluster environment today, but I ended up having to fix some problems with the PR (updated now) as well as rebuild my aws cluster. My plan is to test the PR on Monday, in the meantime it should be ready to review (but I want to do the testing on Monday before merging anything -- I want to make sure the change actually fixes the problem reported -- with PVC labeled for exclude but no labels on PV.

Sure, we will start to review it, and will not merge it until you fully test it.

File: pkg/backup/backup.go [hunk 1]
```diff
@@ -645,6 +645,17 @@ func (kb *kubernetesBackupper) executeItemBlockActions(
...
+
+			relatedItemMetadata, err := meta.Accessor(item)
+			if err != nil {
+				log.WithError(errors.WithStack(err)).Warn("Failed to get object metadata.")
+				continue
+			}
+			// Don't add to ItemBlock if item is excluded
+			// itemInclusionChecks logs the reason
+			if !itemBlock.itemBackupper.itemInclusionChecks(log, false, relatedItemMetadata, item, relatedItem.GroupResource) {
+				continue
```
Comment (kaovilai) [inline pkg/backup/backup.go:657]:
```diff
			itemsMap[relatedItem] = append(itemsMap[relatedItem], &kubernetesResource{
				groupResource: relatedItem.GroupResource,
				preferredGVR:  gvr,
				namespace:     relatedItem.Namespace,
				name:          relatedItem.Name,
-				inItemBlock:   true,
+				inItemBlock:   false,
			})
```
Shouldn't this code in line 646 be flipped to false?

File: pkg/backup/itemblock.go [hunk 2]
```diff
@@ -60,6 +61,18 @@ func (b *BackupItemBlock) addKubernetesResource(item *kubernetesResource, log lo
...
 	}
+
+	metadata, err := meta.Accessor(&unstructured)
+	if err != nil {
+		log.WithError(errors.WithStack(err)).Warn("Error accessing item metadata")
+		return nil
+	}
+	// Don't add to ItemBlock if item is excluded
+	// itemInclusionChecks logs the reason
+	if !b.itemBackupper.itemInclusionChecks(log, false, metadata, &unstructured, item.groupResource) {
```
Comment (blackpiglet) [inline pkg/backup/itemblock.go:72]: To me, it seems this change should already work.
It seems no need to add the same check in the `pkg/backup/backup.go`.

File: pkg/backup/backup.go (hunk 1 above)
Comment (sseago) [reply pkg/backup/backup.go:657]: @kaovilai No. "True" means we've already processed this for item block exclusion -- it prevents Velero from adding it to another ItemBlock later. Since we already know we don't want to include this in an ItemBlock, we set it to true here so we don't have to even consider it later.

I guess `processedForItemBlock` would have been a more accurate field name here, but that's clumsy and might also be confusing. I think the current name is probably clearest, but maybe a comment here explaining why it's set to true would be appropriate?

Comment (kaovilai) [reply pkg/backup/backup.go:657]: or just `processed` indicating item was processed. a comment to clarify that inItemBlock does not mean it would be in an item block would be great.

File: pkg/backup/itemblock.go (hunk 2 above)
Comment (sseago) [reply pkg/backup/itemblock.go:72]: @blackpiglet When we add related items to the ItemBlock, we first attempt to find it in the list from the item collector -- in that case we already have the item content and don't need to make an APIServer call. That's the code path that adds to the ItemBlock here, so we need the inclusion check to skip excluded items.

In cases where the item is *not* already in the list of items from the item collector (PVs returned from PVC plugin when includeClusterResources==nil), then we have to pull the item via the APIServer -- that's the code path that makes the check in `pkg/backup/backup.go`

Note that this `itemInclusionChecks` call happens within `itemblock.addKubernetesResource` -- and whenever `addKubernetesResource` is called from `backup.go`, there's a `continue` call afterwards (line 613) , and the second `itemInclusionChecks` call is after this continue,  so this check won't be performed twice.

File: pkg/backup/backup.go (hunk 1 above)
Comment (sseago) [reply pkg/backup/backup.go:657]: @kaovilai What about `inItemBlockOrExcluded`? That covers the default use case of "this has already been included" more explicitly than "processed" without being confusing in the exclusion case?

Comment (kaovilai) [reply pkg/backup/backup.go:657]: works for me.

**Comment by sseago** [comment]
@Lyndon-Li PR updated with feedback from @kaovilai and I was able to test it in an aws cluster environment today. Labeling the PVC but not the PV with the exclude label now properly excludes both PVC and PV from backup -- without this PR, I reproduced the bug found by the issue reporter.

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by blackpiglet — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]
