### PR TITLE
Mark BackupRepository not ready when BSL changed

### LINKED ISSUE #8860: BackupRepository does not backup to updated BSL prefix
**What steps did you take and what happened:**

Part of investigating https://issues.redhat.com/browse/OADP-5062
1. create credentials secret
2. create velero install with nodeagent enabled(oadp dpa create)
3. deploy stateful app with pvc
4. backup app with defaultToFsBackup
5. modify bsl to different bucket prefix (modifying oadp dpa)
6. create another backup with defaultToFsBackup
7. backupRepo spec did not change, resticIdentifier and all
8. observe that new prefix is not used to backup by kopia
    1. velero log does show `level=info msg="BSL's prefix has changed, invalid backup repositories" BSL=velero-sample-1 logSource="pkg/controller/backup_repository_controller.go:176" new prefix=tiger419diffprefix old prefix=tiger419`
    2. subsequent maintenance all failed with errors
        ```
        recentMaintenance
            - message: 'failed to prune repo: error to connect backup repo: error to connect
                repo with storage: error to connect to repository: repository not initialized
                in the provided storage'
              result: Failed
              startTimestamp: "2025-04-11T06:55:20Z"
            - message: 'failed to prune repo: error to connect backup repo: error to connect
                repo with storage: error to connect to repository: repository not initialized
                in the provided storage'
              result: Failed
              startTimestamp: "2025-04-11T07:00:20Z"
        kind: List
        metadata:
          resourceVersion: ""
        ```
`Invalidating Backup Repository` log was not observed, which probably indicates that following
https://github.com/vmware-tanzu/velero/blob/fa156c3961bbe5e0234c4c8789fbadf3b62a6015/pkg/controller/backup_repository_controller.go#L108
do not work.. or something wrong with
https://github.com/vmware-tanzu/velero/blob/fa156c3961bbe5e0234c4c8789fbadf3b62a6015/pkg/controller/backup_repository_controller.go#L119

**What did you expect to happen:**

kopia dir gets populated under new prefix

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

[velero pod logs](https://gist.github.com/kaovilai/4727b2579114354adc8944aef864f090)

**Anything else you would like to add:**

From https://github.com/openshift/velero/tree/oadp-1.5
which currently is not materially different from main
https://github.com/openshift/velero/compare/oadp-1.5...vmware-tanzu%3Avelero%3Amain

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by ywk253100**
Mark BackupRepository not ready when BSL changed

Fixes #8860

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/controller/backup_repository_controller.go [hunk 1]
```diff
@@ -130,18 +127,41 @@ func (r *BackupRepoReconciler) invalidateBackupReposForBSL(ctx context.Context,
...
+			continue
 		}
+		requests = append(requests, reconcile.Request{NamespacedName: types.NamespacedName{Namespace: list.Items[i].Namespace, Name: list.Items[i].Name}})
 	}
 
-	return []reconcile.Request{}
+	return requests
+}
+
+type bslPredicate struct {
```
Comment (Lyndon-Li) [inline pkg/controller/backup_repository_controller.go:143]: Let's try to reuse a create a generic predicate which could be shared with others.
