### PR TITLE
[fix] Avoid overwritten hook's exec.container parameter when running …

### LINKED ISSUE #4499: Hooks use wrong container name with multiple label selectors.
### Discussed in https://github.com/vmware-tanzu/velero/discussions/4488

<div type='discussions-op-text'>

<sup>Originally posted by **sabir-catalogic** January  5, 2022</sup>
I have two applications running (Postgres and MongoDB). I took a backup using the manifest file below.
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  labels:
    velero.io/storage-location: default
  name: firstbackup
  namespace: velero
spec:
  hooks:
    resources:
      -
        name: pre-hook-AAA
        includedNamespaces:
        - '*'
        includedResources:
        - pods
        labelSelector:
          matchExpressions:
          - {key: app, operator: In, values: [mongo,postgres]}
        pre:
          -
            exec:
              command:
                - env
              onError: Fail
              timeout: 10s
  includedNamespaces:
  - '*'
  storageLocation: default
```
But the backup is partially failing with the error 
```
time="2022-01-03T12:31:39Z" level=error msg="Error executing hook" backup=velero/firstbackup error="no such container: \"mongo\"" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podexec/pod_command_executor.go:184" error.function=github.com/vmware-tanzu/velero/pkg/podexec.ensureContainerExists group=v1 hookPhase=pre hookSource=backupSpec hookType=exec logSource="pkg/backup/item_hook_handler.go:134" name=postgres-deployment-f574f5b46-5djpc namespace=default resource=pods
time="2022-01-03T12:31:39Z" level=error msg="Error backing up item" backup=velero/firstbackup error="no such container: \"mongo\"" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podexec/pod_command_executor.go:184" error.function=github.com/vmware-tanzu/velero/pkg/podexec.ensureContainerExists group=v1 logSource="pkg/backup/resource_backupper.go:294" name=postgres-deployment-f574f5b46-5djpc namespace= resource=pods
```
by looking at the logs I understand that the backup of MongoDB deployment got successful but when backup turns comes to Postgres deployment velero is searching for a container named "mongo" in the Postgres pod. But this must not happen because I didn't mention running the command in the mongo container.

according to the documentation if the container is not specified then the first container in the pod is used.
```
              # first container in the pod will be used. Optional.
              # container: my-container
```
but it is not happening while using hooks with multiple labelSelector.
however, when I ran the backup with a single label selector for both applications, the backup is getting successful.
I believe it is some kind of bug while selecting the appropriate container while using hooks with multiple labelSelector like
```
labelSelector:
          matchExpressions:
          - {key: app, operator: In, values: [mongo,postgres]}
```

</div>

### PR DESCRIPTION
**Pull request by blackpiglet**
…pod command executor

Fix #4499
When hook influnce multiple pods, current logic's first pod's container will overwrite the hook's exec.container parameter. That will cause the other pod fail on the hook executing.

Signed-off-by: Xun Jiang <jxun@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/podexec/pod_command_executor_test.go [hunk 1]
```diff
@@ -101,12 +102,34 @@ func TestExecutePodCommandMissingInputs(t *testing.T) {
...
 			},
 		},
+		{
+			name:         "hook's container is not overwritten by pod",
+			item:         velerotest.UnstructuredOrDie(`{"kind":"Pod","spec":{"containers":[{"name":"foo"}]}}`).Object,
+			podNamespace: "ns",
+			podName:      "pod",
+			hookName:     "hook",
+			hook: &v1.ExecHook{
+				Container: "bar",
```
Comment (reasonerjt) [inline pkg/podexec/pod_command_executor_test.go:112]: The `Container` should be `""` to test your change, right?

Comment (blackpiglet) [reply pkg/podexec/pod_command_executor_test.go]: Right. Changed to ""

**Review by reasonerjt — APPROVED** [review]

**Review by qiuming-best — APPROVED** [review]
