### PR TITLE
don't error during backup when additional items returned by plugin don't exist

### LINKED ISSUE #1878: Non-existent items should not cause backup to be PartiallyFailed
xref #1858 

During a backup, if we have, for example, a pod that references a non-existent PVC, the backup will be `PartiallyFailed` because the PVC doesn't exist.

Arguably, the non-existence of the PVC should not cause the backup to fail. It's not Velero's job to validate the API resources, just to back them up as-is.

### LINKED ISSUE #2269: Unscheduled pod with invalid PVC reference results in partial failure
**What steps did you take and what happened:**
This is a bit of an edge case but we have had this happen in one of our production clusters. If you create a pod with a persistentVolumeClaim reference that does not exist, the pod will be stuck in the status `Pending`. Now when a velero full backup runs it tries to backup all volumes of all pods and naturally fails because the persistentVolumeClaim it tries to backup does not exist.

https://github.com/vmware-tanzu/velero/blob/master/pkg/backup/pod_action.go#L65

**What did you expect to happen:**

The backup should either skip pods which are not scheduled or check if a PVC actually exists before adding it to the list in `pod_action.go`.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* Create a pod with an invalid PVC reference
```bash
cat << EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  dnsPolicy: Default
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: doesnotexist
EOF
```
* Create a full backuo `velero backup create full`
* `velero backup logs full | grep -B 5 error`
```
time="2020-02-13T08:18:29Z" level=info msg="Backing up item" backup=velero/full group=v1 logSource="pkg/backup/item_backupper.go:169" name=nginx-test namespace=velero resource=pods
time="2020-02-13T08:18:29Z" level=info msg="Executing custom action" backup=velero/full group=v1 logSource="pkg/backup/item_backupper.go:330" name=nginx-test namespace=velero resource=pods
time="2020-02-13T08:18:29Z" level=info msg="Executing podAction" backup=velero/full cmd=/velero logSource="pkg/backup/pod_action.go:51" pluginName=velero
time="2020-02-13T08:18:29Z" level=info msg="Adding pvc doesnotexist to additionalItems" backup=velero/full cmd=/velero logSource="pkg/backup/pod_action.go:67" pluginName=velero
time="2020-02-13T08:18:29Z" level=info msg="Done executing podAction" backup=velero/full cmd=/velero logSource="pkg/backup/pod_action.go:77" pluginName=velero
time="2020-02-13T08:18:29Z" level=info msg="1 errors encountered backup up item" backup=velero/full group=v1 logSource="pkg/backup/resource_backupper.go:284" name=nginx-test namespace= resource=pods
time="2020-02-13T08:18:29Z" level=error msg="Error backing up item" backup=velero/full error="persistentvolumeclaims \"doesnotexist\" not found" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:351" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*defaultItemBackupper).executeActions" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=nginx-test namespace= resource=pods
```

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.2.0
        Git commit: 5d008491bbf681658d3e372da1a9d3a21ca4c03c
Server:
        Version: v1.2.0
```
- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-12-04T07:23:47Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
`kind v0.6.1 go1.13.4 linux/amd64`
- Cloud provider or hardware configuration:
GCP with GCS
- OS (e.g. from `/etc/os-release`):
Fedora 31 Workstation

### PR DESCRIPTION
**Pull request by skriss**
closes #1878 
closes #2269 

This PR changes the backup code to log a warning instead of returning an error if an additional item returned by a backup item action plugin can't be found in the Kubernetes API. It also changes `velero backup get/describe` to always display warning/error count, rather than doing it selectively based on phase.

### CODE REVIEW

File: pkg/cmd/util/output/backup_describer.go [hunk 1]
```diff
@@ -70,11 +70,9 @@ func DescribeBackup(
 			}
 		}
 
-		if status.Phase == velerov1api.BackupPhasePartiallyFailed {
-			d.Println()
-			d.Printf("Errors:\t%d\n", status.Errors)
-			d.Printf("Warnings:\t%d\n", status.Warnings)
-		}
+		d.Println()
```
Comment (nrb) [inline pkg/cmd/util/output/backup_describer.go:73]: I like this change. It is a good step towards unifying restore and backup describe output. (cc @sseago)

Comment (skriss) [reply pkg/cmd/util/output/backup_describer.go:73]: Yeah I tried to be consistent between the two, it's a lot easier for users that way.
