### PR TITLE
Check whether the volume is provisioned by CSI driver or not by the annotation as well

### LINKED ISSUE #4496: restic-wait container never terminates when enabling CSI migration
I got this issue on Azure cluster which installs both in-tree and CSI driver, and enables CSI-migration, but it should exist for other cloud providers as well.

The steps to reproduce this issue:
1. Deploy a workload with PVs provisioned by the in-tree driver
2. Backup the workload with Restic
3. Remove the workload
4. Restore

The restore finished successfully but the `restic-wait` init container never terminates.

The spec of the PV is as following:
```
yinw@yinw-a02 velero-develop-tool % k get pv pvc-427c1989-8188-413a-9279-cdc078d45993  -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  creationTimestamp: "2022-01-06T07:31:58Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-427c1989-8188-413a-9279-cdc078d45993
  resourceVersion: "28570039"
  uid: e3ea046c-cf8b-4042-be33-3fda3c8d767b
spec:
  accessModes:
  - ReadWriteOnce
  azureDisk:
    cachingMode: ReadWrite
    diskName: pvc-427c1989-8188-413a-9279-cdc078d45993
    diskURI: /subscriptions/xxx/resourceGroups/mc_yinw-resource-group-01_yinw-cluster-02_westus/providers/Microsoft.Compute/disks/pvc-427c1989-8188-413a-9279-cdc078d45993
    fsType: ""
    kind: Managed
    readOnly: false
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: etcd0-pv-claim
    namespace: default
    resourceVersion: "28570020"
    uid: 427c1989-8188-413a-9279-cdc078d45993
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.disk.csi.azure.com/zone
          operator: In
          values:
          - ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: managed
  volumeMode: Filesystem
status:
  phase: Bound
```

The [code](https://github.com/vmware-tanzu/velero/blob/main/pkg/util/kube/utils.go#L108) thinks the PV is provisioned by the in-tree driver as there is no `CSI` stuff in the volume spec, but because the CSI-migration is enabled, the underlying volumes are provisioned by the CSI driver actually.

This causes that the tailing `mount` directory isn't appended for the volumes and the `restic-wait` container cannot find the `done` file forever

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by ywk253100**
Check whether the volume is provisioned by CSI driver or not by the annotation as well

Fixes #4496

Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: Tiltfile [hunk 1]
```diff
@@ -103,7 +103,7 @@ local_resource(
 
 local_resource(
     "restic_binary",
-    cmd = 'cd ' + '.' + ';mkdir -p _tiltbuild/restic; BIN=velero GOOS=' + local_goos + ' GOARCH=amd64 RESTIC_VERSION=0.12.0 OUTPUT_DIR=_tiltbuild/restic ./hack/download-restic.sh',
+    cmd = 'cd ' + '.' + ';mkdir -p _tiltbuild/restic; BIN=velero GOOS=linux GOARCH=amd64 RESTIC_VERSION=0.12.0 OUTPUT_DIR=_tiltbuild/restic ./hack/download-restic.sh',
```
Comment (blackpiglet) [inline Tiltfile:106]: Is there any difference after modifying the GOOS setting for the Tiltfile?

**Review by blackpiglet — DISMISSED** [review]
LGTM

File: pkg/util/kube/utils.go [hunk 2]
```diff
@@ -140,13 +149,27 @@ func GetVolumeDirectory(pod *corev1api.Pod, volumeName string, pvcLister corev1l
...
 }
 
+func isProvisionedByCSI(pv *corev1api.PersistentVolume) bool {
+	if pv.Spec.CSI != nil {
+		return true
+	}
+	// Although the pv.Spec.CSI is nil, the volume could be provisioned by a CSI driver when enabling the CSI migration
+	// Refer to https://github.com/vmware-tanzu/velero/issues/4496 for more details
+	if pv.Annotations != nil {
+		if strings.Contains(pv.Annotations[KubeAnnDynamicallyProvisioned], "csi") {
```
Comment (reasonerjt) [inline pkg/util/kube/utils.go:166]: for safety how about checking `.csi.`?

Can we add a log saying `because the provisioned-by annotation is xxxx so I think this is provisioned by CSI`?

Comment (ywk253100) [reply pkg/util/kube/utils.go:166]: There are some drivers named `csi.xxx` and `csi-xxx`: https://kubernetes-csi.github.io/docs/drivers.html

**Review by blackpiglet — APPROVED** [review]
lgtm

**Review by reasonerjt — APPROVED** [review]
