### PR TITLE
Fix backup post hook issue

### LINKED ISSUE #8159: Post hook command is executed before the Kopia snapshot is completed
**What steps did you take and what happened:**

I am using Velero to back up a PostgreSQL dump created by a pre-hook command, so that Kopia can backup the dump, then delete the file using a post-hook command. However, I noticed that the post-hook was executed before Kopia had the chance to back up the dump.

I conducted several tests:
- The first one involved adding a `sleep 60` at the beginning of my post-hook command-> the dump was successfully included in the Kopia snapshot.

- The second test involved creating a file after the dump was completed, which I used in my post-hook command to wait for the file to be fully generated before deleting the dump -> the dump was not included in the Kopia snapshot.

**What did you expect to happen:**

Dump file should be in Kopia snapshot

**Anything else you would like to add:**

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: my-app-pg-app
  namespace: velero
spec:
  schedule: "0 4 * * *"
  useOwnerReferencesInBackup: false
  template:
    includedNamespaces:
      - my-app
    labelSelector:
      matchLabels:
        cnpg.io/cluster: pg-app-16
    metadata: {}
    ttl: 720h
    hooks:
      resources:
        - name: dump
          pre:
            - exec:
                container: postgres
                command:
                  - /bin/bash
                  - -c
                  - |
                    set -e
                    echo "/pgdata/*" > /var/lib/postgresql/data/.kopiaignore &&
                    pg_dump -d app -f /var/lib/postgresql/data/dump_app-$(hostname)-$(date '+%Y-%m-%d-%H-%M-%S')
                onError: Fail
                timeout: 5m
          post:
            - exec:
                container: postgres
                command:
                  - /bin/bash
                  - -c
                  - |
                    rm -f /var/lib/postgresql/data/dump_app-$(hostname)-*
                onError: Fail

```

**Environment:**

- Velero version (use `velero version`):  1.14.0
- Velero features (use `velero client config get features`):  None
- Kubernetes version (use `kubectl version`): 1.30
- Kubernetes installer & version: -
- Cloud provider or hardware configuration: AWS - EKS v1.30.2-eks-db838b0
- OS (e.g. from `/etc/os-release`): Amazon Linux 2023

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by ywk253100**
Fix backup post hook issue

Fixes #8159

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/backup/backup.go [hunk 1]
```diff
@@ -730,6 +732,99 @@ func (kb *kubernetesBackupper) handleItemBlockHooks(itemBlock BackupItemBlock, h
 	return successPods, failedPods, errs
 }
 
+func (kb *kubernetesBackupper) handleItemBlockPostHooks(ctx context.Context, itemBlock BackupItemBlock, hookPods []itemblock.ItemBlockItem) {
+	log := itemBlock.Log
+
+	// Handle post hooks for file system backup
+	// The hooks cannot execute until the PVBs to be processed
+	isFileSystemBackup := itemBlock.itemBackupper.backupRequest.Spec.DefaultVolumesToFsBackup
```
Comment (sseago) [inline pkg/backup/backup.go:740]: This doesn't completely determine whether the pod has fs-backup pods. If we're defaulting to fs-backup, individual volumes could opt out via annotations. If we're not defaulting to fs-backup, individual volumes coule opt in via annotations. Or the user could be using volume policies to determine this.

@shubham-pampattiwar What's the right way to determine whether we have any fs-backup volumes among the pods passed in?

**Review by sseago — COMMENTED** [review]
We need to do something other than assuming that all volumes use fs-backup when defaultVolumesToFsBackup is true and no volumes use it when false. If it's true and all volumes in an itemBlock either opt out of fs-backup via annotation (for snapshotting) or use volume policies to snapshot, then we'll be grabbing the PVB list unnecessarily. That's harmless enough. However the other case is more problematic -- if defaultVolumesToFsBackup is false but some volumes in the ItemBlock opt in via annotation or are selected for fs-backup via volume policies, then we won't wait for them to complete to run hooks.

File: pkg/backup/backup.go (hunk 1 above)
Comment (sseago) [reply pkg/backup/backup.go:740]: @ywk253100 I just discussed this with @shubham-pampattiwar -- we're currently thinking that the best option will be to just skip the `if isFileSystemBackup` test and always proceed as if there may be one or more PVBs. If there are no PVBs at all for the backup, then inside `waitUntilPVBsProcessed`, `pvbList` and `pvbMap` will both be empty, so `allProcessed` will be true on the first run. If there are some PVBs for the backup but none for this ItemBlock, then `pvbList` will be non-empty but `pvbMap` will be empty so `allProcessed` will still be true on the first run. This only requires a single  APIServer `List` call, while to determine accurately whether we have any filesystem backup PVCs for the item block would require retrieving the list of volumes here, which would be a more expensive operation.

**Review by sseago — DISMISSED** [review]

File: internal/hook/hook_tracker.go [hunk 2]
```diff
@@ -69,14 +69,16 @@ type HookTracker struct {
 	// HookExecutedCnt indicates the number of executed hooks.
 	hookExecutedCnt int
 	// hookErrs records hook execution errors if any.
-	hookErrs []HookErrInfo
+	hookErrs        []HookErrInfo
+	AsyncItemBlocks *sync.WaitGroup
```
Comment (Lyndon-Li) [inline internal/hook/hook_tracker.go:73]: `BackupWithResolvers` calls this `Stat` by its end, but `BackupWithResolvers` doesn't know details of each itemBlock, it just calls `backupItemBlock` for all itemBlocks.
On the other hand, PVBs in each itemBlock belong to the itemBlock, so looks like this semantic is more rational --- for each `backupItemBlock` call,  start all PVBs of the itemBlock->wait all PVB complete->run post hooks.

However, at present, when `backupItemBlock` exits, the PVBs have not actually completed, `BackupWithResolvers` needs to call hooker's `Stat` to wait them indirectly.

Therefore, I suggest we make the waiting for PVB completion into `backupItemBlock` and call post hooks in the same place. cc @sseago

Comment (Lyndon-Li) [reply internal/hook/hook_tracker.go:73]: We can do this in 1.16 only, as in 1.15, we don't support concurrent `backupItemBlock`, if we put the wait inside `backupItemBlock`, PVBs among itemBlocks have to be done in sequence, this is not helpful practically.

Comment (Lyndon-Li) [reply internal/hook/hook_tracker.go:73]: @sseago Just let us know your thinking

Comment (sseago) [reply internal/hook/hook_tracker.go:73]: @Lyndon-Li "Therefore, I suggest we make the waiting for PVB completion into backupItemBlock and call post hooks in the same place."

So right now, we invoke the "wait for PVB completion and then call hooks" with `go kb.handleItemBlockPostHooks` -- is your suggestion to replace the goroutine call with a direct func call? This would effectively mean that the specific `BackupItemBlock` call would not return until 1) PVB processing completes and 2) post-backup hooks are done.

With the current codebase (i.e. concurrent `backupItemBlock` is not yet implemented), that might, in the short term, have a negative performance impact -- but it may make more sense to handle it that way once we have concurrent `backupItemBlock` processing. However, there still may be edge cases where this has a negative performance impact -- in particular, with large clusters with a large number of node agents, each of which enables multiple parallel PVB processing -- the number of concurrent PVBs we can process may exceed the number of parallel ItemBlocks configured, in which case parallel item block processing will become the bottleneck, not allowing full use of the node agent pods to handle many volumes at once.

Comment (Lyndon-Li) [reply internal/hook/hook_tracker.go:73]: > With the current codebase (i.e. concurrent backupItemBlock is not yet implemented), that might, in the short term, have a negative performance impact

Yes, agree. This is why we suggest to do this only in 1.16 where concurrent itemBlock processing is fully supported.

File: pkg/backup/backup.go (hunk 1 above)
Comment (ywk253100) [reply pkg/backup/backup.go]: Updated.

**Review by Lyndon-Li — APPROVED** [review]

**Review by blackpiglet — APPROVED** [review]

File: internal/hook/hook_tracker.go (hunk 2 above)
Comment (ywk253100) [reply internal/hook/hook_tracker.go:73]: @Lyndon-Li @sseago
I'm going to merge this PR and cherry pick the changes to branch 1.15 to unblock the release 1.15.1.
Let's continue the discussion on issue https://github.com/vmware-tanzu/velero/issues/8516

Comment (sseago) [reply internal/hook/hook_tracker.go:73]: > > the number of concurrent PVBs we can process may exceed the number of parallel ItemBlocks configured
> 
> If so, can we recommend users to adjust the concurrent number of ItemBlocks? We don't need to consider the number of CPU cores to fit the thread pool, as in this case, the work is actually done by node-agent, the itemBlock threads just need to wait the completion

@Lyndon-Li In many cases yes. I imagine there's a point beyond which increasing the pool size might have negative performance consequences -- so in huge clusters with many nodes, it may not make sense to have the number of concurrent ItemBlocks be as high as the maximum possible number of concurrent PVBs, but as long as the ItemBlock concurrency is the bottleneck, increasing it should help.

Comment (Lyndon-Li) [reply internal/hook/hook_tracker.go:73]: > in huge clusters with many nodes, it may not make sense to have the number of concurrent ItemBlocks be as high as the maximum possible number of concurrent PVBs

What is the problem if we do so? Do you mean the number of CPU core may be less than number of concurrent PVBs, so increasing the pool size may not get the best performance of item blocks?
