### PR TITLE
7979 fix

### LINKED ISSUE #7979: CSI Artifacts are not patched in object store after Finalizing Phase
**What steps did you take and what happened:**

In the finalizing phase today the backup controller re uploads the backup TarBall. (https://github.com/vmware-tanzu/velero/blob/1ec52beca80975f74f9ed28d6f9c5f7afe67edee/pkg/backup/backup.go#L756)
But it does not update CSI related artifacts in the object store. 
The CSI gzips with VolumeSNapshotCOntent, VolumeSnapshot etc.

Velero in the CSI plugin BIAv2 implementation does a cleanup of the VolumeSnapshot & recreates VolumeSnapshotContent  after the backup goes into finalizing phase. 
https://github.com/vmware-tanzu/velero/blob/28d64c2c529f33510a68200c129012a163777a67/pkg/util/csi/volume_snapshot.go#L633-L636

Given this behavioural gap in velero, the object store is not updated with this recreated VolumeSnapshotContent as the contents are not re uploaded.

This has lead to other behavioural issues in Velero as highlighted in Issue - #7978

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by blackpiglet**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #7979 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/restore/actions/csi/volumesnapshot_action.go [hunk 1]
```diff
@@ -188,13 +143,85 @@ func (p *volumeSnapshotRestoreItemAction) Progress(
...
+	if err := p.crClient.Get(
+		context.TODO(),
+		crclient.ObjectKey{Namespace: operationIDParts[0], Name: operationIDParts[1]},
+		vs,
+	); err != nil {
+		logger.Errorf("Fail to get the VolumeSnapshot %s", operationID)
+		return progress, err
+	}
+
+	if vs.Spec.Source.VolumeSnapshotContentName == nil {
```
Comment (Lyndon-Li) [inline pkg/restore/actions/csi/volumesnapshot_action.go:173]: This can reuse existing helper function `util.GetVolumeSnapshotContentForVolumeSnapshot`

File: pkg/restore/actions/csi/volumesnapshot_action.go [hunk 2]
```diff
@@ -188,13 +143,85 @@ func (p *volumeSnapshotRestoreItemAction) Progress(
...
+	} else {
+		logger.Debugf("VolumeSnapshot or VolumeSnapshotContent are not ready yet.")
+		progress.Description = "VolumeSnapshot or VolumeSnapshotContent creation are still in progress."
+		return progress, nil
+	}
+
+	progress.Description = "VolumeSnapshot and VolumeSnapshotContent are ready"
+	progress.OperationUnits = "Bytes"
+	progress.Completed = true
+	if vsc.Status.RestoreSize != nil {
```
Comment (Lyndon-Li) [inline pkg/restore/actions/csi/volumesnapshot_action.go:209]: Don't set `progress.NCompleted` and `progress.NTotal` as discussed previously

File: pkg/restore/actions/csi/volumesnapshotcontent_action.go [hunk 3]
```diff
@@ -51,19 +61,56 @@ func (p *volumeSnapshotContentRestoreItemAction) AppliesTo() (
...
+	p.log.Info("Starting VolumeSnapshotContentRestoreItemAction")
+
+	var snapCont snapshotv1api.VolumeSnapshotContent
 	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(
 		input.Item.UnstructuredContent(), &snapCont); err != nil {
 		return &velero.RestoreItemActionExecuteOutput{},
 			errors.Wrapf(err, "failed to convert input.Item from unstructured")
 	}
 
+	if err := p.ensureDeleteExistingVSC(snapCont); err != nil {
```
Comment (Lyndon-Li) [inline pkg/restore/actions/csi/volumesnapshotcontent_action.go:79]: There is an existing helper function for this purpose `util. EnsureDeleteVSC`

File: pkg/restore/actions/csi/volumesnapshot_action.go (hunk 2 above)
Comment (blackpiglet) [reply pkg/restore/actions/csi/volumesnapshot_action.go:209]: There should not be a progress function according to design.
I will modify it.

File: internal/delete/actions/csi/volumesnapshotcontent_action.go [hunk 4]
```diff
@@ -77,25 +80,48 @@ func (p *volumeSnapshotContentDeleteItemAction) Execute(
...
+		p.log.Warnf("fail to parse resource timeout annotation %s: %s",
+			input.Backup.Annotations[velerov1api.ResourceTimeoutAnnotation], err.Error())
+		timeout = 10 * time.Minute
+	}
+	p.log.Debugf("resource timeout is set to %s", timeout.String())
+
+	interval := 5 * time.Second
+
+	// Wait until VSC created and ReadyToUse is true.
+	if err := wait.PollUntilContextTimeout(
```
[the remark this answers is not in the document]
Comment (blackpiglet) [reply internal/delete/actions/csi/volumesnapshotcontent_action.go:115]: The suggestion about using existing helper functions all have the same impediment.
The existing helper functions uses a typed go-client, which is provisioned by the external-snapshotter code.
The added functions uses a untyped go-client, which is provisioned by the controller-runtime package.

IMO, the untyped controller-runtime is a better choice. As a result, we should do  refactor the existing helper functions to adopt the controller-runtime client, but the functions dependency is complicated. A lot of files will be involved to resolve it.
I propose to do that in a separate PR.

**Comment by blackpiglet** [comment]
@anshulahuja98 
Please also take a look. I made some changes in the design because I found that restore needs a way to record the VSs and VSCs generated in the restore. 
As a result, I added an async operation in the VolumeSnapshot RestoreItemAction to wait till the VSC's snapshot handle is created.

Although the async operation doesn't wait till VS and VSC become `ReadyToUse`, it is still different from what we have agreed.
Please check whether that's OK for your scenario.

**Comment by anshulahuja98** [comment]
As discussed over chat, I have concern with deletion of VS / VSC in finalizing. 
Our eventual targe is that the PVC being restored from VS gets restored properly.
Now here if we delete the VS before the PVC is fully hydrated.
Consider 2 scenarios - If PVC is waiting for first consumer and there is no pod mounting it, and vS gets deleted, the VS is useless

Another scenarios is where CSI driver is expected to take time to hydrate the PVC from VS, in those case also we can't delete VS inflight.

**Comment by blackpiglet** [comment]
> As discussed over chat, I have concern with deletion of VS / VSC in finalizing. Our eventual targe is that the PVC being restored from VS gets restored properly. Now here if we delete the VS before the PVC is fully hydrated. Consider 2 scenarios - If PVC is waiting for first consumer and there is no pod mounting it, and vS gets deleted, the VS is useless
> 
> Another scenarios is where CSI driver is expected to take time to hydrate the PVC from VS, in those case also we can't delete VS inflight.

It's a reasonable consideration. I will update the implementation.
Restore will not delete the VolumeSnapshotContent and VolumeSnapshot.

**Comment by blackpiglet** [comment]
@anshulahuja98 
Modified according to comment. PTAL.

**Review by Lyndon-Li — APPROVED** [review]

File: pkg/util/csi/volume_snapshot.go [hunk 5]
```diff
@@ -475,17 +475,29 @@ func IsVolumeSnapshotExists(
 	return err == nil
 }
 
+func IsVolumeSnapshotContentExists(name string, client crclient.Client) bool {
```
Comment (mayankagg9722) [inline pkg/util/csi/volume_snapshot.go:478]: This func is not used

File: pkg/restore/actions/csi/volumesnapshotcontent_action.go [hunk 6]
```diff
@@ -51,34 +57,77 @@ func (p *volumeSnapshotContentRestoreItemAction) AppliesTo() (
...
+	// If cross-namespace restore is configured, change the namespace
+	// for VolumeSnapshot object to be restored
+	newNamespace, ok := input.Restore.Spec.NamespaceMapping[vsc.Spec.VolumeSnapshotRef.Namespace]
+	if ok {
+		// Update the referenced VS namespace to the mapping one.
+		vsc.Spec.VolumeSnapshotRef.Namespace = newNamespace
+	}
+
+	// Reset VSC name to align with VS.
+	vsc.Name = util.GenerateSha256FromRestoreUIDAndVsName(
```
Comment (mayankagg9722) [inline pkg/restore/actions/csi/volumesnapshotcontent_action.go:91]: Should we add a label to the restored VS & VSC object with the original name as well? That might help for debugging.

File: pkg/util/csi/volume_snapshot.go (hunk 5 above)
Comment (blackpiglet) [reply pkg/util/csi/volume_snapshot.go]: Thanks. Deleted.

File: pkg/restore/actions/csi/volumesnapshotcontent_action.go (hunk 6 above)
Comment (blackpiglet) [reply pkg/restore/actions/csi/volumesnapshotcontent_action.go:91]: I agree this is useful from the code perspective, but is there any scenario needing that mapping relation?
IMO, the VS and the VSC are not useful after the PVC creation. 
The original proposal was to delete the restored VS and VSC after the restore completes.
As a result, the mapping may not be that useful to me, but if there is any concrete scenario that needs that, I'm open to adding it.

Comment (mayankagg9722) [reply pkg/restore/actions/csi/volumesnapshotcontent_action.go:91]: No @blackpiglet I don't think of any scenario that needs this. I only asked from code/debug perspective.

**Review by mayankagg9722 — APPROVED** [review]

**Review by Lyndon-Li — APPROVED** [review]

**Review by ywk253100 — APPROVED** [review]
