### PR TITLE
Privileged fs backup pods

### LINKED ISSUE #9294: Velero 1.17 filesystem backup is broken for clusters that require Privileged pod security context to access the mount path
**What steps did you take and what happened:**

With Velero 1.17, I tried to use fs-backup on OpenShift. I get a permission error because the fs-backup pod is not running in a Privileged security context, which is required for fs-backup to work on OpenShift. In 1.16, this worked because we have the option to run the node agent pods in privileged mode.

**What did you expect to happen:**
The backup to work
**The following information will help us better understand what's going on**:

I'll be submitting a PR shortly. We need a new `--privileged-fs-backup` install and node-agent server option for users using k8s environments that require this. We need a new param rather than simply propagating the existing node-agent privileged flag, since the conditions where this is needed for node agent (block mode on all clusters) are different from where it's needed for fs-backup (for certain cluster types if using fs-backup). It's possible to need privileged node agent but not privileged fs-backup, and vice versa.

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by sseago**
Thank you for contributing to Velero!

# Please add a summary of your change
Adds install/node-agent server arg: `--privileged-fs-backup` to enable fs-backup on OpenShift (and other k8s environments that need it)
# Does your change fix a particular issue?

Fixes #9294 

# Please indicate you've done the following:

- [ x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ x] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/cmd/cli/nodeagent/server.go [hunk 1]
```diff
@@ -84,6 +84,7 @@ type nodeAgentServerConfig struct {
 	resourceTimeout         time.Duration
 	dataMoverPrepareTimeout time.Duration
 	nodeAgentConfig         string
+	privilegedFsBackup      bool
```
Comment (Lyndon-Li) [inline pkg/cmd/cli/nodeagent/server.go]: As the discussion, let's move this flag to node-agent configMap.

File: pkg/exposer/pod_volume.go [hunk 2]
```diff
@@ -394,6 +398,9 @@ func (e *podVolumeExposer) createHostingPod(ctx context.Context, ownerObject cor
 					Env:             podInfo.env,
 					EnvFrom:         podInfo.envFrom,
 					Resources:       resources,
+					SecurityContext: &corev1api.SecurityContext{
```
Comment (Lyndon-Li) [inline pkg/exposer/pod_volume.go]: Windows containers don't support this. So need to check the nodeOS and set this securityContext for non-Windows only.

**Comment by sseago** [comment]
I've updated the PR to use the node agent configmap and to not modify the SecurityContext for windows.

File: pkg/controller/pod_volume_backup_controller.go [hunk 3]
```diff
@@ -74,7 +74,7 @@ func NewPodVolumeBackupReconciler(client client.Client, mgr manager.Manager, kub
 		vgdpCounter:           counter,
 		preparingTimeout:      preparingTimeout,
 		resourceTimeout:       resourceTimeout,
-		exposer:               exposer.NewPodVolumeExposer(kubeClient, logger),
+		exposer:               exposer.NewPodVolumeExposer(kubeClient, logger, privileged),
```
Comment (Lyndon-Li) [inline pkg/controller/pod_volume_backup_controller.go]: nit: `privileged` is more like a expose parameter, so it's better to set it into `PodVolumeExposeParam` in function `setupExposeParam` just like other parameters.

File: pkg/controller/pod_volume_restore_controller.go [hunk 4]
```diff
@@ -69,7 +69,7 @@ func NewPodVolumeRestoreReconciler(client client.Client, mgr manager.Manager, ku
 		vgdpCounter:           counter,
 		preparingTimeout:      preparingTimeout,
 		resourceTimeout:       resourceTimeout,
-		exposer:               exposer.NewPodVolumeExposer(kubeClient, logger),
+		exposer:               exposer.NewPodVolumeExposer(kubeClient, logger, privileged),
```
Comment (Lyndon-Li) [inline pkg/controller/pod_volume_restore_controller.go]: nit: privileged is more like a expose parameter, so it's better to set it into PodVolumeExposeParam in function setupExposeParam just like other parameters.

File: pkg/exposer/pod_volume.go [hunk 5]
```diff
@@ -409,6 +411,10 @@ func (e *podVolumeExposer) createHostingPod(ctx context.Context, ownerObject cor
 			ImagePullSecrets:              podInfo.imagePullSecrets,
 		},
 	}
+	if nodeOS != kube.NodeOSWindows {
```
Comment (Lyndon-Li) [inline pkg/exposer/pod_volume.go]: nit: There is a central place above `if nodeOS == kube.NodeOSWindows {}else{}` to handle differences of nodeOS, it's better we put this one there as well, to prevent it is ignored and overwrite other code which also set `pod.Spec.Containers[0].SecurityContext` in future.

Comment (sseago) [reply pkg/exposer/pod_volume.go]: That would work if we have a value to set for SecurityContext for windows. But Spec.Containers[0] isn't defined yet in the windows block above. So this code sets pod.Spec.Containers[0].SecurityContext only if it's not windows.  Is it fine for windows to just set this to nil? Then I can always set this field to a local var `containerSecurityCtx`, which will be the block below for non-windows, and nil for windows, and then I can define that inline. Is that fine for windows?

File: pkg/controller/pod_volume_backup_controller.go (hunk 3 above)
Comment (sseago) [reply pkg/controller/pod_volume_backup_controller.go]: I'll update this.

File: pkg/exposer/pod_volume.go (hunk 5 above)
Comment (sseago) [reply pkg/exposer/pod_volume.go]: @Lyndon-Li ok, I've updated it as I suggested above. Let me know whether what I've done works for windows too.

**Review by shubham-pampattiwar — COMMENTED** [review]
@sseago Everything looks good, maybe just add a unit test ?

**Comment by sseago** [comment]
> @sseago Everything looks good, maybe just add a unit test ?

Done

**Review by Lyndon-Li — APPROVED** [review]

**Comment by Lyndon-Li** [comment]
@sseago Please help to cherry-pick this PR to 1.17 branch. Thanks!
