### PR TITLE
Fix issue 6561

### LINKED ISSUE #6561: alpine can not be pulled in some environments when moving snapshot
We use the `alpine:latest` as the image for the pod in data mover, however, it cannot be pulled in some environments, e.g. airgap env or env reaches the pull limit of Dockerhub.

Besides, we also need to consider the maintenance effort for the new image, e.g. CVE 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by Lyndon-Li**
Fix #6561, change the backup/restore pod's image to the same image used by the node-agent, but with a different binary `velero-helper`, so as not to depend on Alpine which may have compliance or security issues or image pull issues.

### CODE REVIEW

File: pkg/exposer/csi_snapshot.go [hunk 1]
```diff
@@ -366,9 +366,8 @@ func (e *csiSnapshotExposer) createBackupPod(ctx context.Context, ownerObject co
 			Containers: []corev1.Container{
 				{
 					Name:            podName,
-					Image:           "alpine:latest",
+					Image:           "gcr.io/google_containers/pause:latest",
```
[the remark this answers is not in the document]
Comment (Lyndon-Li) [reply pkg/exposer/csi_snapshot.go:369]: No special reason to use `latest`. Merely, we don't have anything depending on the image, so use the `latest` to have it up-to-date. (we only require an image that is as small in size as possible, is widely available and is with less security issues)
Additionally, it doesn't matter actually. This image is very simple and hasn't been updated for years. It is not expected to by changed.

**Review by sseago — APPROVED** [review]

File: cmd/velero-helper/velero-helper.go
Comment (mateusoliveira43) [inline cmd/velero-helper/velero-helper.go:1]: would be interesting to use cobra here? it would be more verbose, but we would have a CLI by default (and it also have the 2 validations builtin: `cobra.MinimumNArgs(1)` and `cobra.OnlyValidArgs`

**Comment by Lyndon-Li** [comment]
We have more inputs/requirements today, so changed the solution from end to end and see if this can meet them:

- Use Velero image for data mover pods
- Create a binary `velero-helper` with small size into Velero image
- Data mover pods launches  `velero-helper` instead of velero, so that data mover pods memory footprint is small
- Duplicate all the image options(including the image itself) from node-agent so that data mover pods never need to pull images themselves, so as to eliminate the complication for image pulling

File: cmd/velero-helper/velero-helper.go
Comment (Lyndon-Li) [reply cmd/velero-helper/velero-helper.go:1]: I am hesitating to involve cobra:

- The binary is targeted to implement simply tasks (otherwise, we can use velero binary instead), i.e., the current pause functionality, it is not expected to be with complex parameters, for which cobra could make a big help.
- Involving cobra will involve some more packages, which will make the total binary size larger.

**Review by reasonerjt — APPROVED** [review]
lgtm

File: cmd/velero-helper/velero-helper.go
Comment (reasonerjt) [reply cmd/velero-helper/velero-helper.go:1]: We may even make it simpler to make it velero-pause, b/c I don't think we wanna support other subcommand, it's simply a placeholder for DM.

**Review by blackpiglet — APPROVED** [review]

**Review by ywk253100 — APPROVED** [review]
