### PR TITLE
Make the backup repository controller doesn't invalidate the BSL on restart

### LINKED ISSUE #9032: Connection to backup repo fails after Velero server restarts
A maintenance job failed after Velero server restarts:

```
time="2025-06-19T20:35:49-07:00" level=warning msg="Failed to retrieve backup repo, need retry" error="backup repository is not ready: re-establish on BSL change, create or delete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/cmd/cli/repomantenance/maintenance.go:175"
time="2025-06-19T20:35:50-07:00" level=warning msg="Failed to retrieve backup repo, need retry" error="backup repository is not ready: re-establish on BSL change, create or delete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/cmd/cli/repomantenance/maintenance.go:175"
time="2025-06-19T20:35:51-07:00" level=warning msg="Failed to retrieve backup repo, need retry" error="backup repository is not ready: re-establish on BSL change, create or delete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/cmd/cli/repomantenance/maintenance.go:175"
time="2025-06-19T20:35:52-07:00" level=warning msg="Failed to retrieve backup repo, need retry" error="backup repository is not ready: re-establish on BSL change, create or delete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/cmd/cli/repomantenance/maintenance.go:175"
time="2025-06-19T20:35:53-07:00" level=warning msg="Failed to retrieve backup repo, need retry" error="backup repository is not ready: re-establish on BSL change, create or delete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/cmd/cli/repomantenance/maintenance.go:175"
Repo maintenance error: failed to get backup repository: backup repository is not ready: re-establish on BSL change, create or delete% 
```

This happens because the repo controller has invalidated the backup repo CR erroneously, because no BSL change has actually happened.
This issue should not only for repo maintenance but for other activities that connect to the repo right after Velero server restarts.

### PR DESCRIPTION
**Pull request by blackpiglet**
Enlarge the timeout for maintenance job waiting for BackupRepository's readiness.

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #9032

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/util/kube/predicate.go [hunk 1]
```diff
@@ -98,10 +98,44 @@ func NewGenericEventPredicate(f func(object client.Object) bool) predicate.Predi
...
 // NewUpdateEventPredicate creates a new Predicate that checks the Update event with the provided func
-func NewUpdateEventPredicate(f func(objectOld client.Object, objectNew client.Object) bool) predicate.Predicate {
+func NewUpdateEventPredicate(
+	f func(objectOld client.Object, objectNew client.Object) bool,
+) predicate.Predicate {
 	return predicate.Funcs{
 		UpdateFunc: func(event event.UpdateEvent) bool {
 			return f(event.ObjectOld, event.ObjectNew)
 		},
+		CreateFunc: func(event event.CreateEvent) bool {
```
Comment (ywk253100) [inline pkg/util/kube/predicate.go]: We should only care about the `Update()` for `UpdateEventPredicate`, similar for `DeleteEventPredicate`

Comment (blackpiglet) [reply pkg/util/kube/predicate.go]: Thanks. Modified.

**Review by ywk253100 — DISMISSED** [review]

**Review by kaovilai — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]
