### PR TITLE
Skip patching the PV in finalization for failed operation

### LINKED ISSUE #8182: Restore finalizing should not run if the async restore operation is failed/cancelled
Related to #8178.

We have a finalizing operation after the async restore completes regardless of the completion status of the async restore. At present, this finalizing operation is used to patch the restored PV, there are some problems:
1. If the async operation was not successful, the PV patching operation may never succeed since the PVC/PV may not have been successfully restored
2. If we run the finalizing operation for failed/cancelled aysnc operation, we need to be careful that the errors/warnings generated by the async operation may be overwritten by the finalizing operation

Therefore, for the current PV patch task, it should not run for failed/cancelled async operations; and for a general purpose, we need to consider whether allow the finalizing operation to run for failed/cancelled async operations.

### PR DESCRIPTION
**Pull request by reasonerjt**
This commit makes change in restore finalizer controller, to make it check the status in item operation of a PVC before patch the PV that is bound to it.  If the operation is not successful it will skip patching the PV.

Fixes #8182

# Please indicate you've done the following:

- [X] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [X] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

File: pkg/controller/restore_finalizer_controller.go [hunk 1]
```diff
@@ -310,6 +353,17 @@ func (ctx *finalizerContext) patchDynamicPVWithVolumeInfo() (errs results.Result
 						return false, err
 					}
 
+					// Check whether the async operation to populate the PVC is successful.  If it's not, will skip patching the PV, instead of waiting.
+					operations := ctx.restoreItemOperationList.SelectByPVC(pvc.Namespace, pvc.Name)
+					for _, op := range operations {
+						if op.Spec.RestoreItemAction == constant.PluginCSIPVCRestoreRIA &&
```
Comment (Lyndon-Li) [inline pkg/controller/restore_finalizer_controller.go:359]: When patching the PV, we do it for all RIA types, so do we need to check the RIA type here?
Or if we want to check the RIA type, should we do it for the entire patching PV logic?

Comment (reasonerjt) [reply pkg/controller/restore_finalizer_controller.go:359]: > if we want to check the RIA type, should we do it for the entire patching PV logic?

I don't quite understand this question.  The reason to check the RIA type is to that there may be async operation to do cosmetic work to the PVC and doesn't impact patching the PV.

Comment (Lyndon-Li) [reply pkg/controller/restore_finalizer_controller.go:359]: If another type of async operation doesn't result in PV creation, we don't need to patch the PV at all. 
If another type of async operation does result in PV creation, we also need to wait for the operation completion, otherwise, PV patching may also fail.

Generally speaking, we don't know if an async operation results in PV creation, so it is fine NOT to check the operation type, by which we arbitrarily regard all operations result in PV creation. It is fine at present though it may be a problem in future.
On the other hand, if we do this more cautiously, we check the operation type, by which we think only the specific action results in PV creation, i.e., RIA. Then if it is NOT RIA, we should not try to patch the PV at all (instead of not checking its completion).

I think either approach is fine.

Comment (Lyndon-Li) [reply pkg/controller/restore_finalizer_controller.go:359]: As the discussion, let's keep it as is. This is a best effort behavior and we do the check for the operation type we know would have patch problem otherwise.

**Review by Lyndon-Li — APPROVED** [review]
