### PR TITLE
Fix VolumeGroupSnapshot restore failure with Ceph RBD CSI driver

### LINKED ISSUE #9512: VGS restore fails with Ceph RBD - missing VGSC causes VS to stay not ready
## What happened

VGS restore with Ceph RBD fails. The VolumeSnapshot shows:
```
error: cannot find the group snapshot for VolumeSnapshot
readyToUse: false
```

PVCs stay Pending, restore times out.

## Environment

- Velero 1.17
- OCP 4.20.13 / K8s 1.33
- ODF 4.20.4 with Ceph RBD

## Root cause

Ceph RBD stores group snapshot relationships in its journal (`csi.groupid` omap key). When we create a pre-provisioned VSC during restore, the RBD driver reads this metadata and populates `status.volumeGroupSnapshotHandle`. 

The CSI snapshot controller then looks for a VGSC with matching `status.VolumeGroupSnapshotHandle`. Since we delete VGSC after backup, it doesn't find one and fails to update VS status.

## Relevant code paths

1. **Ceph RBD populates GroupSnapshotId on snapshot import:**
   https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/snapshot.go#L167
   ```go
   GroupSnapshotId: rbdSnap.groupID,
   ```

2. **CSI snapshot controller requires VGSC when volumeGroupSnapshotHandle exists:**
   https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L1293
   ```go
   return nil, fmt.Errorf("updateSnapshotStatus: cannot find the group snapshot for VolumeSnapshot [%s], will not update snapshot status", ...)
   ```

3. **Velero deletes VGSC after backup:**
   https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/actions/csi/pvc_action.go#L1124-L1147

## Why CephFS works but RBD doesn't

Both drivers support VGS for backup. The difference is in restore behavior:

- CephFS doesn't populate `volumeGroupSnapshotHandle` when importing a pre-provisioned snapshot
- RBD reads group metadata from its journal and populates `volumeGroupSnapshotHandle`

So RBD triggers the VGSC lookup, CephFS doesn't.

## Workaround

Create a stub VGSC with matching `volumeGroupSnapshotHandle` and patch its status. Validated this fixes the issue.

## Proposed fix

1. Backup: Capture `volumeGroupSnapshotHandle` from VSC status in `CSISnapshotInfo`
   - File: `internal/volume/volumes_information.go`

2. Restore: If handle exists, create stub VGSC before creating VSC
   - File: `pkg/restore/actions/csi/volumesnapshotcontent_action.go`

This is a no-op for CephFS (handle won't be populated) and fixes RBD.

## Scope

Only affects: VGS + Ceph RBD + non-datamover
Not affected: CephFS, datamover, individual VS backups

### LINKED ISSUE #9515: CSI snapshot restore fails on Ceph RBD when VolumeSnapshotClassName is not set on restored VSC
## What happened

CSI snapshot restore fails on Ceph RBD because the restored VolumeSnapshotContent does not have `VolumeSnapshotClassName` set. The CSI controller cannot get credentials for snapshot verification, causing the VSC to stay `readyToUse: false` and PVCs to remain Pending.

## Steps to reproduce

1. Create a PVC with Ceph RBD storage class
2. Create a Velero backup with CSI snapshots (non-datamover)
3. Restore to a new namespace
4. Observe VSC stays `readyToUse: false` and PVC stays Pending

## Error

```
status:
  error:
    message: 'Failed to check and update snapshot content: failed to list snapshot
      for content <vsc-name>: "rpc error: code = Internal desc = failed to find 
      snapshot with ID \"<id>\": failed to get credentials: provided secret is empty"'
  readyToUse: false
```

## Root cause

The VSC restore action removes `VolumeSnapshotClassName` from restored VSCs (introduced in PR #9431) to make restore independent of VolumeSnapshotClass. However, for pre-provisioned VSCs, the CSI controller needs the class reference to get credentials for snapshot verification calls.

Relevant code in `pkg/restore/actions/csi/volumesnapshotcontent_action.go`:
```go
if vsc.Spec.VolumeSnapshotClassName != nil {
    // Delete VolumeSnapshotClass from the VolumeSnapshotContent.
    // This is necessary to make the restore independent of the VolumeSnapshotClass.
    vsc.Spec.VolumeSnapshotClassName = nil
    ...
}
```

## Workaround

Manually patch VSC with a matching VolumeSnapshotClass:
```
kubectl patch volumesnapshotcontent <name> --type='json' \
  -p='[{"op": "add", "path": "/spec/volumeSnapshotClassName", "value": "<class-name>"}]'
```

## Additional findings

- Having a **default VolumeSnapshotClass** in the cluster does NOT help - the CSI controller only uses default class for dynamically created snapshots, not pre-provisioned ones
- This affects ALL CSI snapshot restores on Ceph RBD, not just VolumeGroupSnapshot workflows

## Proposed fix

Instead of removing `VolumeSnapshotClassName`, look up a matching VolumeSnapshotClass by driver on the target cluster and set it on the restored VSC.

## Environment

- Velero version: main
- Kubernetes: OpenShift 4.18
- CSI Driver: Ceph RBD (openshift-storage.rbd.csi.ceph.com)
- Storage: ODF 4.18

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
# Please add a summary of your change

This PR fixes two related issues that cause CSI snapshot restore failures with drivers like Ceph RBD:

1. **VolumeGroupSnapshot restore failure (#9512)**: When restoring VolumeSnapshots that were originally part of a VolumeGroupSnapshot, the CSI external-snapshotter controller fails because it cannot find the VolumeGroupSnapshotContent (VGSC) referenced by the `status.volumeGroupSnapshotHandle` field on the restored VolumeSnapshotContent.

2. **VolumeSnapshotClassName removal breaking credential lookup (#9515)**: PR #9431 removed the VolumeSnapshotClassName from restored VolumeSnapshotContents, which breaks CSI drivers that need credentials for snapshot verification via ListSnapshots (e.g., Ceph RBD).

### Changes

**Backup phase (`pkg/backup/actions/csi/volumesnapshot_action.go`):**
- Capture `volumeGroupSnapshotHandle` from VSC status as a VolumeSnapshot annotation during backup

**Restore phase (`pkg/restore/actions/csi/volumesnapshot_action.go`):**
- Create a stub VolumeGroupSnapshotContent during restore when the annotation exists
- The stub VGSC contains the matching `volumeGroupSnapshotHandle` in its status, satisfying the CSI controller's validation

**Restore phase (`pkg/restore/actions/csi/volumesnapshotcontent_action.go`):**
- Instead of removing VolumeSnapshotClassName entirely, look up a VolumeSnapshotClass matching the CSI driver
- This allows the restore to remain portable (not dependent on original class name) while still providing credentials

### Root Cause Analysis

**Issue 1 (VGS):** Ceph RBD CSI driver populates `status.volumeGroupSnapshotHandle` on VolumeSnapshotContents that were created as part of a VolumeGroupSnapshot. The CSI external-snapshotter controller validates this field and expects a corresponding VGSC to exist. Velero deletes the VGSC after backup (keeping only individual VS/VSC), so during restore this validation fails.

**Issue 2 (Credentials):** The CSI controller calls ListSnapshots to verify the snapshot exists on storage. For Ceph RBD, this requires credentials configured in the VolumeSnapshotClass. Without the class reference, the controller cannot authenticate and the snapshot stays in a non-ready state.

# Does your change fix a particular issue?

Fixes #9512
Fixes #9515

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/restore/actions/csi/volumesnapshot_action.go [hunk 1]
```diff
@@ -65,6 +70,124 @@ func resetVolumeSnapshotAnnotation(vs *snapshotv1api.VolumeSnapshot) {
 		string(snapshotv1api.VolumeSnapshotContentRetain)
 }
 
+// ensureStubVGSCExists creates a stub VolumeGroupSnapshotContent if the snapshot
+// was created as part of a VolumeGroupSnapshot. This is needed for CSI drivers
+// like Ceph RBD that populate volumeGroupSnapshotHandle on pre-provisioned snapshots.
+// The CSI snapshot controller requires a VGSC with matching handle to exist.
+func (p *volumeSnapshotRestoreItemAction) ensureStubVGSCExists(
```
Comment (Lyndon-Li) [inline pkg/restore/actions/csi/volumesnapshot_action.go:77]: After the restore, must the VGSC stay in the cluster?

Comment (shubham-pampattiwar) [reply pkg/restore/actions/csi/volumesnapshot_action.go:77]: The stub VGSC is only required during initial VSC reconciliation. Once the VSCs become `readyToUse: true`, the VGSC can be safely deleted.

We tested this on a cluster:
1. Completed a VGS restore - VSCs became `readyToUse: true`
2. Deleted the stub VGSC
3. Waited and verified VSCs remained `readyToUse: true`

The VGSC is labeled with `velero.io/restore-name` for easy identification/cleanup. We can add optional cleanup logic in a follow-up PR if needed.

File: pkg/restore/actions/csi/volumesnapshot_action.go [hunk 2]
```diff
@@ -65,6 +70,124 @@ func resetVolumeSnapshotAnnotation(vs *snapshotv1api.VolumeSnapshot) {
...
+	}
+
+	// Generate a deterministic name for the stub VGSC based on the group handle
+	vgscName := util.GenerateSha256FromRestoreUIDAndVsName(string(restore.UID), vgsh)
+
+	// Check if VGSC already exists
+	existingVGSC := &volumegroupsnapshotv1beta1.VolumeGroupSnapshotContent{}
+	err := p.crClient.Get(ctx, crclient.ObjectKey{Name: vgscName}, existingVGSC)
+	if err == nil {
+		// VGSC already exists, check if we need to add this snapshot handle
```
Comment (blackpiglet) [inline pkg/restore/actions/csi/volumesnapshot_action.go]: Per the comment, it seems there are still some logic not implemented for the VGSC existing case.

Comment (shubham-pampattiwar) [reply pkg/restore/actions/csi/volumesnapshot_action.go]: Good catch! Fixed in the latest commit. The code now properly adds snapshot handles to an existing VGSC when multiple VolumeSnapshots from the same VolumeGroupSnapshot are being restored.

Also added comprehensive unit tests for both `ensureStubVGSCExists` (5 test cases) and `addSnapshotHandleToVGSC` (4 test cases).

File: pkg/restore/actions/csi/volumesnapshot_action.go (hunk 1 above)
Comment (Lyndon-Li) [reply pkg/restore/actions/csi/volumesnapshot_action.go:77]: > We can add optional cleanup logic in a follow-up PR if needed

I think the less leftovers after restore the better. What do you think @shubham-pampattiwar?

Comment (shubham-pampattiwar) [reply pkg/restore/actions/csi/volumesnapshot_action.go:77]: Agreed, less leftovers is better. The challenge is that multiple VSs share one stub VGSC, so we can't delete it until all related VSCs are `readyToUse`. The VS restore action is per-item and doesn't have visibility into when all items are complete.

For now, the stub VGSC is labeled with `velero.io/restore-name` for easy identification/cleanup. We can add automatic cleanup logic in a follow-up PR - likely in the restore controller's finalization phase where we know the restore is complete.

Want me to add the cleanup in this PR, or keep it separate?

**Comment by shubham-pampattiwar** [comment]
Addressed feedback. @Lyndon-Li @blackpiglet ready for another look when you have time.

File: pkg/restore/actions/csi/volumesnapshot_action.go (hunk 1 above)
Comment (Lyndon-Li) [reply pkg/restore/actions/csi/volumesnapshot_action.go:77]: @shubham-pampattiwar Let's cleanup the VGSC after restore, as aligned to the behavior of Velero's CSI volume snapshot restore.
Looks like CSI restore is also doing similar things in finalization phase. cc @blackpiglet for more information.

Comment (shubham-pampattiwar) [reply pkg/restore/actions/csi/volumesnapshot_action.go:77]: Agreed. Added stub VGSC cleanup in the restore finalizer controller (commit 386d4a18c).

The cleanup runs during the restore finalization phase in `finalizerContext.execute()`. Before deleting each stub VGSC, it polls until all related VolumeSnapshotContents are `ReadyToUse` (correlated by matching snapshot handles between the VGSC and each VSC). On timeout, it proceeds with deletion anyway since the VGSC has `DeletionPolicy: Retain` and won't affect the underlying snapshots.

CRD-not-installed scenarios (clusters without VolumeGroupSnapshot support) are handled gracefully as warnings.

**Comment by weshayutin** [comment]
@sseago @kaovilai please review

**Comment by weshayutin** [comment]
related issue https://redhat.atlassian.net/browse/OADP-7381

File: internal/volume/volumes_information.go [hunk 3]
```diff
@@ -456,6 +460,10 @@ func (v *BackupVolumesInformation) generateVolumeInfoForCSIVolumeSnapshot() {
 		if volumeSnapshotContent.Status.SnapshotHandle != nil {
```
Comment (kaovilai) [inline internal/volume/volumes_information.go:460]: should this have similar nil status check?

File: pkg/restore/actions/csi/volumesnapshot_action.go [hunk 4]
```diff
@@ -65,6 +70,165 @@ func resetVolumeSnapshotAnnotation(vs *snapshotv1api.VolumeSnapshot) {
...
+		p.log.Warnf("Failed to fetch stub VGSC %s for status patch: %v", vgscName, err)
+		return nil
+	}
+
+	// Set volumeGroupSnapshotHandle in status using Patch to avoid conflicts with the CSI controller.
+	patchBase := createdVGSC.DeepCopy()
+	if createdVGSC.Status == nil {
+		createdVGSC.Status = &volumegroupsnapshotv1beta1.VolumeGroupSnapshotContentStatus{}
+	}
+	createdVGSC.Status.VolumeGroupSnapshotHandle = &vgsh
```
Comment (blackpiglet) [inline pkg/restore/actions/csi/volumesnapshot_action.go:188]: Since VolumeGroupSnapshotHandle is already in the VGSC's spec, why do we still need to patch VolumeGroupSnapshotHandle in the VGSC' status?
Is it possible that the CSI controller writes a different value in VGSC's status?

File: pkg/controller/restore_finalizer_controller.go [hunk 5]
```diff
@@ -443,6 +449,93 @@ func (ctx *finalizerContext) patchDynamicPVWithVolumeInfo() (errs results.Result
...
+				for j := range vscList.Items {
+					vsc := &vscList.Items[j]
+					if vsc.Spec.Source.SnapshotHandle == nil {
+						continue
+					}
+					if !snapshotHandles[*vsc.Spec.Source.SnapshotHandle] {
+						continue
+					}
+					// This VSC is related to our VGSC
+					if vsc.Status == nil || !boolptr.IsSetToTrue(vsc.Status.ReadyToUse) {
```
Comment (blackpiglet) [inline pkg/controller/restore_finalizer_controller.go:510]: Apologies for the delayed comments.

I have a question: Will deleting the VolumeGroupSnapshotContent automatically trigger the deletion of the corresponding VolumeSnapshotContent?
* If not, the proposed code change appears acceptable.
* If yes, we need to proceed with caution. Even if a VolumeSnapshotContent is in the ReadyToUse state, it might still be actively used by Persistent Volume Claims (PVCs) for data hydration into new volumes.

File: pkg/restore/actions/csi/volumesnapshot_action.go (hunk 4 above)
Comment (shubham-pampattiwar) [reply pkg/restore/actions/csi/volumesnapshot_action.go:188]: The CSI common-controller's updateSnapshotStatus function validates this by matching on `status.VolumeGroupSnapshotHandle`, not the spec field. When a VSC has `status.VolumeGroupSnapshotHandle` set, the controller lists all VGSCs and looks for one whose status VolumeGroupSnapshotHandle matches. If no match is found, it returns an error and blocks the VolumeSnapshot status update entirely. See https://github.com/kubernetes-csi/external-snapshotter/blob/44b5c593566c4eac588b82307655aeaabb6ccc10/pkg/common-controller/snapshot_controller.go#L1234-L1253:       
```go
  if content.Status != nil && content.Status.VolumeGroupSnapshotHandle != nil {                                                                                            
      // ...lists all VGSCs and matches on status.VolumeGroupSnapshotHandle                                                                                                
      if !found {                                                                                                                                                          
          return nil, fmt.Errorf("updateSnapshotStatus: cannot find the group snapshot for VolumeSnapshot [%s]...")                                                        
      }                                                                                                                                                                    
  }                                                                                                                                                                        
```                                                                                                                                                                  
So we need the handle in both places, spec for Velero's own correlation (cleanup, handle tracking), and status to satisfy the CSI controller's validation. The CSI controller won't write a different value here since this is a stub VGSC that Velero fully controls with `DeletionPolicy: Retain`.

File: pkg/controller/restore_finalizer_controller.go (hunk 5 above)
Comment (shubham-pampattiwar) [reply pkg/controller/restore_finalizer_controller.go:510]: Deleting the stub VGSC will not cascade-delete the VSCs. The stub is created with `DeletionPolicy: Retain`, and there is no code in any VGSC deletion path that deletes the associated VSC objects.                                                                                                                                                 
                
Specifically:                                                                                                                                                            
                
1. The common-controller at                                                                                                                                              
https://github.com/kubernetes-csi/external-snapshotter/blob/44b5c593566c4eac588b82307655aeaabb6ccc10/pkg/common-controller/groupsnapshot_controller_helper.go#L1566-L1571 sets deleteGroupSnapshotContent to true only when `DeletionPolicy == Delete`. The VGSC API object is then conditionally deleted at                                        
https://github.com/kubernetes-csi/external-snapshotter/blob/44b5c593566c4eac588b82307655aeaabb6ccc10/pkg/common-controller/groupsnapshot_controller_helper.go#L1638-L1640 with Retain, that block is skipped entirely.
2. The sidecar controller at
https://github.com/kubernetes-csi/external-snapshotter/blob/44b5c593566c4eac588b82307655aeaabb6ccc10/pkg/sidecar-controller/groupsnapshot_helper.go#L173-L191 skips the CSI DeleteGroupSnapshot call with Retain and just removes the finalizer.
3. Even for individual VSCs that belong to a group, the sidecar at                                                                                                       
https://github.com/kubernetes-csi/external-snapshotter/blob/44b5c593566c4eac588b82307655aeaabb6ccc10/pkg/sidecar-controller/snapshot_controller.go#L63-L64 skips the CSI DeleteSnapshot call when VolumeGroupSnapshotHandle is set -- group member snapshots can only be deleted at the storage level through the group deletion path.
                                                                                                                                                                         
No code in the VGSC deletion path deletes the associated VolumeSnapshotContent objects. The only related cleanup is deletion of VolumeSnapshot (namespace-scoped) objects, not VSCs. So deleting the stub VGSC is safe even if PVCs are still hydrating data from the restored volumes.

**Review by blackpiglet — APPROVED** [review]
