### PR TITLE
Copy SecurityContext from Containers[0] if present for PVR

### LINKED ISSUE #8711: fs-backup restore on OpenShift results in wrong SCC annotation
**What steps did you take and what happened:**
Using Velero 1.16/main velero, in an OpenShift (4.17+) environment, a user workload pod (created as non-admin user) gets the wrong SecurityContextConstraint (SCC) on restore.

Velero 1.15.1 added a change to set a default SecurityContext on the fs-backup InitContainer to fix a bug related to pod security standards enforcement. In an OpenShift environment, when the pod was created by a non-admin user, using this default SecurityContext with runAsUser set based on the current (velero) user breaks because this forces the openshift.io/scc annotation to the default privileged level of the velero SA.

The fix is to use the SecurityContext from the first pod container if that container has a SecurityContext set, using the default otherwise.
The SecurityContext ConfigMap won't work here for two reasons:
1) That configmap will set it to be the same SecurityContext for all pod InitContainers. The immediate cause of the bug is the mismatch in the `runAsUser` field, requiring the higher-privileged SCC. The "use from pod" fix will make sure these match.
2) This is a base use case. Regular user-created workloads should back up and restore out of  the box.

**What did you expect to happen:**
A pod that had the `openshift.io/scc: restricted-v2` annotation at backup time should have the same SCC annotation on restore.

**The following information will help us better understand what's going on**:

Fix PR forthcoming.

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by sseago**
Thank you for contributing to Velero!

# Please add a summary of your change
Velero 1.15.1 added a change to set a default SecurityContext on the fs-backup InitContainer to fix a bug related to pod security standards enforcement. In an OpenShift environment, when the pod was created by a non-admin user, using this default SecurityContext with runAsUser set based on the current (velero) user breaks because this forces the openshift.io/scc annotation to the default privileged level of the velero SA.

The fix is to use the SecurityContext from the first pod container if that container has a SecurityContext set, using the default otherwise.

# Does your change fix a particular issue?

Fixes #8711

# Please indicate you've done the following:

- [x ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [x ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

File: pkg/restore/actions/pod_volume_restore_action.go [hunk 1]
```diff
@@ -157,15 +157,24 @@ func (a *PodVolumeRestoreAction) Execute(input *velero.RestoreItemActionExecuteI
...
+	if runAsUser != "" || runAsGroup != "" || allowPrivilegeEscalation != "" || secCtx != "" {
 		securityContext, err = kube.ParseSecurityContext(runAsUser, runAsGroup, allowPrivilegeEscalation, secCtx)
 		if err != nil {
 			log.Errorf("Using default securityContext values, couldn't parse securityContext requirements: %s.", err)
-			securityContext = defaultSecurityCtx()
+		} else {
+			securityContextSet = true
 		}
 	}
+	// if first container in pod has a SecurityContext set, then copy this security context
```
Comment (reasonerjt) [inline pkg/restore/actions/pod_volume_restore_action.go:170]: The log message printed in line 165 could be misleading, maybe just remove "Using default securityContext values" in the sentence?

**Comment by sseago** [comment]
@reasonerjt unit test added

**Review by shubham-pampattiwar — APPROVED** [review]
