### PR TITLE
Bypass the remap CRD version plugin when v1beta1 CRD is not supported

### LINKED ISSUE #4080: error fetching v1beta1 version of volumesnapshotclasses.snapshot.storage.k8s.io
Using Kubernetes v1.22.1 and the latest version of Velero v1.6.3 and helm chart version v2.23.6 gives me the following error on backups: 

```
error executing custom action (groupResource=customresourcedefinitions.apiextensions.k8s.io, namespace=, name=volumesnapshots.snapshot.storage.k8s.io): rpc error: code = Unknown desc = error fetching v1beta1 version of volumesnapshots.snapshot.storage.k8s.io: the server could not find the requested resource" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:331" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemBackupper).executeActions" logSource="pkg/backup/backup.go:431" name=volumesnapshots.snapshot.storage.k8s.io
```

I've also gotten other related errors for other apps such as:

```
error executing custom action (groupResource=customresourcedefinitions.apiextensions.k8s.io, namespace=, name=pgclusters.crunchydata.com): rpc error: code = Unknown desc = error fetching v1beta1 version of pgclusters.crunchydata.com: the server could not find the requested resource" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:331" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemBackupper).executeActions" logSource="pkg/backup/backup.go:431" name=pgclusters.crunchydata.com
```

### PR DESCRIPTION
**Pull request by reasonerjt**
When velero is running on clusters that don't support v1beta1 CRD, the
plugin will not try to backup v1beta1 CRD.
The plugin should be kept for backward compatibility.  It will be
removed when velero drop the support for k8s v1.21

Signed-off-by: Daniel Jiang <jiangd@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #4080

# Please indicate you've done the following:

- [X] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [X] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/backup/remap_crd_version_action.go [hunk 1]
```diff
@@ -68,7 +71,26 @@ func (a *RemapCRDVersionAction) Execute(item runtime.Unstructured, backup *v1.Ba
...
+					break CheckVersion
+				}
+			}
+
+		}
+	}
+	if !supportv1b1 {
+		a.logger.Info("Exiting RemapCRDVersionAction, the cluster does not support v1beta1 CRD")
+		return item, nil, nil
+	}
```
Comment (jenting) [inline pkg/backup/remap_crd_version_action.go:91]: Can we write it something like
```go
gvr, _, err := a.discoveryHelper.ResourceFor(
	schema.GroupVersionResource{
		Group:    "apiextensions.k8s.io",
		Version:  "v1beta1",
		Resource: "customresourcedefinitions",
	})
```

Comment (reasonerjt) [reply pkg/backup/remap_crd_version_action.go:91]: @jenting Thanks for the comment, but this seems not working.  It returns a `no matching` error on cluster that supports `v1beta1` CRD
seems the helper will only put the preferred version in the map unless the `APIGroupVersionsFeatureFlag` is set:
https://github.com/vmware-tanzu/velero/blob/15136745488c07201b13a8ebd738eb6e27fffaf1/pkg/discovery/helper.go#L161

Comment (jenting) [reply pkg/backup/remap_crd_version_action.go:91]: I see, make sense.

**Review by ywk253100 — APPROVED** [review]
