### PR TITLE
Only set BSL credential field if provided

### LINKED ISSUE #4196: CLI `backup-location create` command incorrectly sets empty `credential` field when no credential provided
**What steps did you take and what happened:**
We run Velero Server as an ECS task rather than as a Kubernetes pod. In v1.5.4 our configuration works as intended, and the ECS task's instance profile (and associated IAM permissions) is what is used to access to the S3 bucket storage location. 

After upgrading to v1.6.x with the same configuration, this breaks with the following error:
```
Error getting backup store for this location" backupLocation=xxxx controller=backup-sync error="unable to get credentials: unable to get key for secret: Secret \"\" not found"
```

**What did you expect to happen:**
The velero server should detect the valid AWS credentials via the instance profile; adhering to AWS best practices.

**The output of the following commands will help us better understand what's going on**:

N/A

**Anything else you would like to add:**

This has also been raised as a Q&A by @toddgardner here: https://github.com/vmware-tanzu/velero/discussions/3800

**Environment:**

- Velero version (use `velero version`): 1.6.x
- Velero features (use `velero client config get features`): N/A
- Kubernetes version (use `kubectl version`): 1.21
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): `velero/velero` Dockerfile

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by zubron**
# Please add a summary of your change
Previously, the BSL credential field would always be set when using the
`create` command, even if no credential details were provided. This
would result in an empty `SecretKeySelector` in the BSL which would
cause operations using this BSL to fail as Velero would attempt to fetch
a `Secret` with an empty name from the K8s API server.

With this change, the `Credential` field is only set if credential
details have been specified. This change also includes some refactoring
to allow the change to be tested.

Signed-off-by: Bridget McErlean <bmcerlean@vmware.com>

# Does your change fix a particular issue?

Fixes #4196

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/cmd/cli/backuplocation/create_test.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+	o := NewCreateOptions()
+
+	bsl, err := o.BuildBackupStorageLocation("velero-test-ns", false, false)
+	assert.NoError(t, err)
+	assert.Nil(t, bsl.Spec.Credential)
+
+	setErr := o.Credential.Set("my-secret=key-from-secret")
+	assert.NoError(t, setErr)
+
+	bsl, err = o.BuildBackupStorageLocation("velero-test-ns", false, true)
```
Comment (jenting) [inline pkg/cmd/cli/backuplocation/create_test.go:72]: nit:
```go
bsl, err = o.BuildBackupStorageLocation("velero-test-ns", false, false)
```

**Review by jenting — APPROVED** [review]
LGTM in general

**Comment by turkenh** [comment]
Experiencing this issue with with velero `v1.7.1`. 
Will this fix be cherry-picked to `v1.7` ?
