### PR TITLE
fix: delete empty backups

### LINKED ISSUE #4551: Unable to delete empty backup
**What steps did you take and what happened:**

I accidentally created an empty backup as the selector didn't return any items. I then realized that Velero was unable to delete it as it got stuck in the Deleting phase forever. Related Slack thread: [https://kubernetes.slack.com/archives/C6VCGP4MT/p1642496332027400](https://kubernetes.slack.com/archives/C6VCGP4MT/p1642496332027400)

```sh
$ velero backup create --include-namespaces 'jenkins' --include-resources '*' --selector some-key=non-existent my-backup-name
$ velero get backups
NAME                        STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
my-backup-name              Completed   0        0          2022-01-19 13:00:40 +0100 CET   29d       default            some-key=non-existent

$ velero backup delete my-backup-name
$ velero get backups
NAME                        STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
...
my-backup-name              Deleting    0        0          2022-01-19 13:00:40 +0100 CET   29d       default            some-key=non-existent
```

**What did you expect to happen:**

Backup is deleted :-)

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

[bundle-2022-01-19-13-05-20.tar.gz](https://github.com/vmware-tanzu/velero/files/7896893/bundle-2022-01-19-13-05-20.tar.gz)

Bundle was generated prior to deletion as I otherwise ran into this:

```sh
velero debug --backup my-backup-name
2022/01/19 12:57:29 Collecting velero resources in namespace: velero
2022/01/19 12:57:31 Collecting velero deployment logs in namespace: velero
2022/01/19 12:57:32 Collecting log and information for backup: my-backup-name
An error occurred: exec failed: Traceback (most recent call last):
  velero-debug-collector:27:20: in <toplevel>
  velero-debug-collector:7:22: in capture_backup_logs
  <builtin>: in capture
Error: capture_local: exit status 1
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 

```txt
Client:
        Version: v1.7.0
        Git commit: 9e52260568430ecb77ac38a677ce74267a8c2176
Server:
        Version: v1.7.1
```

- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`):

```txt
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version: AKS, v1.21.2
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): N/A

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by yuvalman**
Signed-off-by: Yuval Manor [yuvalman958@gmail.com](mailto:yuvalman958@gmail.com)

Thank you for contributing to Velero!

# Please add a summary of your change

Deleting backups that were created empty

# Does your change fix a particular issue?

Fixes #4551

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by blackpiglet** [comment]
Is this PR used to delete backups that don't have resource tarball in object storage?
Could you explain your use case?

**Comment by aslafy-z** [comment]
@blackpiglet have a look to the linked issue. Empty backups are stuck in Deleting state. This PR aims to fix the bug.

**Comment by yuvalman** [comment]
Hi @blackpiglet, as @aslafy-z mentioned this PR aims to delete backups that were created empty, and because of that, they will be stuck in DELETING phase forever. You can also check for scenarios in the [related Slack thread](https://kubernetes.slack.com/archives/C6VCGP4MT/p1642496332027400) mentioned in the opened issue (#4551).


BTW, the issue can also theoratically happen if we try to restore backup with 0 items. In such case, we can also change the restore resources dir [logic](https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L379-L383) as been done in this pr (for deleting the backup) to handle such case, and if the resources dir is not exist, we won't add an error to Velero Result (because there is no resources to restore).

Please let me know if you want me to add this logic.

File: pkg/restore/restore_test.go [hunk 1]
```diff
@@ -792,12 +792,34 @@ func TestInvalidTarballContents(t *testing.T) {
...
 		})
 	}
 }
 
+func assertWantErrs(t *testing.T, wantErrRes Result, errRes Result) {
+	t.Helper()
+	if wantErrRes.Velero != nil {
+		assert.Equal(t, len(wantErrRes.Velero), len(errRes.Velero))
+		for i := range errRes.Velero {
+			assert.Contains(t, errRes.Velero[i], wantErrRes.Velero[i])
```
Comment (blackpiglet) [inline pkg/restore/restore_test.go:806]: Should this line use assert.Equal()?

File: internal/delete/delete_item_action_handler.go [hunk 2]
```diff
@@ -68,10 +68,11 @@ func InvokeDeleteActions(ctx *Context) error {
 	ctx.Log.Debugf("Downloaded and extracted the backup file to: %s", dir)
 
 	backupResources, err := archive.NewParser(ctx.Log, ctx.Filesystem).Parse(dir)
-	if err != nil {
+	if existErr := errors.Is(err, archive.ErrNotExist); err != nil && !existErr {
 		return errors.Wrapf(err, "error parsing backup %q", dir)
+	} else if existErr {
```
Comment (blackpiglet) [inline internal/delete/delete_item_action_handler.go:73]: Need to add a log to trace

File: pkg/restore/restore_test.go (hunk 1 above)
Comment (yuvalman) [reply pkg/restore/restore_test.go:806]: Actually, the best was to check the error using assert.ErrorIs. But Result contains strings and not the errors.

After changing the Parser to use the [checkAndReadDir function](https://github.com/vmware-tanzu/velero/blob/bebbd837324eca3a876d4a2b802694e81771e386/pkg/archive/parser.go#L71), I removed the [strings.TrimPrefix](https://github.com/vmware-tanzu/velero/blob/main/pkg/archive/parser.go#L74) of the dir+"/", so in the errors we will get the whole path (include a temp dir that is created as part of the flow). So, we can't use assert.Equal because there will be a different path every time.

Using assert.Contains, We can check that the string of error contains the error we meant to.

**Review by blackpiglet — DISMISSED** [review]

File: internal/delete/delete_item_action_handler.go [hunk 3]
```diff
@@ -62,16 +62,17 @@ func InvokeDeleteActions(ctx *Context) error {
...
 	}
 	defer ctx.Filesystem.RemoveAll(dir)
 	ctx.Log.Debugf("Downloaded and extracted the backup file to: %s", dir)
 
 	backupResources, err := archive.NewParser(ctx.Log, ctx.Filesystem).Parse(dir)
-	if err != nil {
+	if existErr := errors.Is(err, archive.ErrNotExist); err != nil && !existErr {
 		return errors.Wrapf(err, "error parsing backup %q", dir)
+	} else if existErr {
+		ctx.Log.Debug("ignore deleting resources: ", err)
```
Comment (reasonerjt) [inline internal/delete/delete_item_action_handler.go:73]: 1.  Why not write it like 
```
if existErr := errors.Is(err, archive.ErrNotExist); existErr {
.....
} else if err != nil {
...
}
```

2. I think the log message is misleading, here you actually ignore invoking the delete item actions, not ignore deleting resources....

Comment (yuvalman) [reply internal/delete/delete_item_action_handler.go]: @reasonerjt I agree, I added your suggestion.

**Review by reasonerjt — APPROVED** [review]

File: internal/delete/delete_item_action_handler.go (hunk 3 above)
Comment (reasonerjt) [reply internal/delete/delete_item_action_handler.go]: thanks!

**Review by blackpiglet — APPROVED** [review]
