### PR TITLE
Only get VolumeSnapshotClass when DataUpload exists.

### LINKED ISSUE #7823: Velero backup gets partially failed when CSI is enabled but VolumeSnapshotClass CRD doesn't exist
For 1.13+
Install Velero with CSI enabled
In the cluster, there is no VolumeSnapshotClass CRD
Run a fs-backup
Velero gets partially failed with error like `cannot list VolumeSnapshotClass no matches for kind \"VolumeSnapshotClass\" in version \"snapshot.storage.k8s.io/v1\"`

### PR DESCRIPTION
**Pull request by blackpiglet**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #7823 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by blackpiglet** [comment]
> Don't we also need VSClass for CSI snapshot backups without datamover?

Yes, but for the CSI plugin scenario, because the VolumeSnapshot-related CRs are persisted, so VolumeSnapshotClasses are already passed in by parameters.

https://github.com/vmware-tanzu/velero/blob/1ec52beca80975f74f9ed28d6f9c5f7afe67edee/internal/volume/volumes_information.go#L321-L340

**Review by shubham-pampattiwar — DISMISSED** [review]

File: internal/volume/volumes_information.go [hunk 1]
```diff
@@ -551,6 +551,22 @@ func (v *BackupVolumesInformation) generateVolumeInfoFromPVB() {
...
+func (v *BackupVolumesInformation) getVolumeSnapshotClasses(
+	classes *snapshotv1api.VolumeSnapshotClassList,
+) (*snapshotv1api.VolumeSnapshotClassList, error) {
+	if classes != nil {
+		return classes, nil
+	}
+
+	vsClassList := new(snapshotv1api.VolumeSnapshotClassList)
+	if err := v.crClient.List(context.TODO(), vsClassList); err != nil {
+		v.logger.WithError(err).Errorf("cannot list VolumeSnapshotClass %s", err.Error())
```
Comment (Lyndon-Li) [inline internal/volume/volumes_information.go:563]: If we generate an error log here, the backup will be partiallyFailed. So probably we need to check `apierrors.IsNotFound`, if it is true, no log should be printed, otherwise, I think a warning log is enough.

Comment (blackpiglet) [reply internal/volume/volumes_information.go:563]: Because this function is only called when the DataUpload CR exists, we should print some information on failing to get the VolumeSnapshotClasses list, no matter the reason for the error.

This condition check already can avoid the scenario described in issue #7823.

As a result, we should print a log error without checking the error type, but it's reasonable to lower the log level to a warning.

Comment (Lyndon-Li) [reply internal/volume/volumes_information.go:563]: VolumeSnapshotClass is only used by data mover backup, for the restore, it can be absent.

**Review by Lyndon-Li — APPROVED** [review]

File: internal/volume/volumes_information.go [hunk 2]
```diff
@@ -551,6 +551,22 @@ func (v *BackupVolumesInformation) generateVolumeInfoFromPVB() {
 	v.volumeInfos = append(v.volumeInfos, tmpVolumeInfos...)
 }
 
+func (v *BackupVolumesInformation) getVolumeSnapshotClasses(
+	classes *snapshotv1api.VolumeSnapshotClassList,
+) (*snapshotv1api.VolumeSnapshotClassList, error) {
+	if classes != nil {
+		return classes, nil
+	}
```
Comment (kaovilai) [inline internal/volume/volumes_information.go:559]: I would do nil check outside this function in `generateVolumeInfoFromDataUpload `.

This function is called `getVolumeSnapshotClasses`, it should be returning the most recent information, rather than exiting.

Also since we are already passing in a pointer, we can just write back to it.
This function shouldn't need any parameter imo unless we rename it to like `getVolumeSnapshotClassesIfNil`.

Comment (blackpiglet) [reply internal/volume/volumes_information.go:559]: Renaming the function is a good point.

Let me explain why this function looks like this.
The generateVolumeInfoFromDataUpload function is called every time a backup completes. No DataUpload may be included. It's also possible the k8s environment doesn't even have the CSI-related CRDs installed.
Calling to list the VolumeSnapshotClasses in such a condition will raise an unnecessary error.

That's why I moved the VolumeSnapshotClasses listing code from the beginning of the function into the iteration of the operations to make sure only tried to list them when the DataUpload was created.

Comment (kaovilai) [reply internal/volume/volumes_information.go:559]: This is what I was thinking.
```diff
-vsClassList, err = v.getVolumeSnapshotClasses(vsClassList)
+if vsClassList == nil {
+	vsClassList, err = v.getVolumeSnapshotClasses()
+	if err != nil {
+		return
+	}
+}
```

This should allow the get func here to be paramless, and still be inside the _iteration of the operations_. But renaming is fine with me too.

Comment (blackpiglet) [reply internal/volume/volumes_information.go:559]: I see. Thanks.

Comment (blackpiglet) [reply internal/volume/volumes_information.go:559]: Modified.

**Review by shubham-pampattiwar — DISMISSED** [review]

File: internal/volume/volumes_information.go [hunk 3]
```diff
@@ -551,95 +550,124 @@ func (v *BackupVolumesInformation) generateVolumeInfoFromPVB() {
...
 
-// generateVolumeInfoFromDataUpload generate BackupVolumeInfo for DataUpload.
-func (v *BackupVolumesInformation) generateVolumeInfoFromDataUpload() {
-	if !features.IsEnabled(velerov1api.CSIFeatureFlag) {
-		v.logger.Debug("Skip generating BackupVolumeInfo when the CSI feature is disabled.")
-		return
+func (v *BackupVolumesInformation) getVolumeSnapshotClasses(
+	classes *snapshotv1api.VolumeSnapshotClassList,
+) (*snapshotv1api.VolumeSnapshotClassList, error) {
+	if classes != nil {
```
Comment (Lyndon-Li) [inline internal/volume/volumes_information.go:556]: Looks like we don't need this `classes` parameter and this check, as this function is not called for multiple times.

Comment (kaovilai) [reply internal/volume/volumes_information.go:556]: looks like we have [similar feedback](https://github.com/vmware-tanzu/velero/pull/7974#discussion_r1674708795)?

File: internal/volume/volumes_information.go [hunk 4]
```diff
@@ -551,95 +550,124 @@ func (v *BackupVolumesInformation) generateVolumeInfoFromPVB() {
...
+	if len(duOperationMap) > 0 {
+		var err error
+		vsClassList, err = v.getVolumeSnapshotClasses(vsClassList)
+		if err != nil {
+			return
+		}
+	} else {
+		// No DataUpload is found. Return early.
+		return
+	}
```
Comment (kaovilai) [inline internal/volume/volumes_information.go:603]: If we remove parameter like lyndon said, this can just be like so. vsClassList will always be nil so parameter doesn't do anything.
```suggestion
	var vsClassList *snapshotv1api.VolumeSnapshotClassList
	if len(duOperationMap) > 0 {
		var err error
		vsClassList, err = v.getVolumeSnapshotClasses()
		if err != nil {
			return
		}
	} else {
		// No DataUpload is found. Return early.
		return
	}
```

Comment (blackpiglet) [reply internal/volume/volumes_information.go]: Modified.

File: internal/volume/volumes_information.go (hunk 3 above)
Comment (blackpiglet) [reply internal/volume/volumes_information.go]: Thanks. Modified.

**Comment by blackpiglet** [comment]
@kaovilai @Lyndon-Li 
Modified according to comments. PTAL.

**Review by Lyndon-Li — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]
