### PR TITLE
Enhance uninstall and backup deletion for restore finalizer

### LINKED ISSUE #6576: Velero backup delete controller should wait the restore is deleted before removing the backup
See some error logs when deleting the backups:
```
time="2023-08-01T08:16:33Z" level=info msg="Finalizer is deleting external resources, backup: dm-11" logSource="pkg/controller/restore_controller.go:666"
time="2023-08-01T08:16:33Z" level=error msg="fail to delete external resources: can't get backup info, backup: dm-11: can't find backup velero/dm-11: Backup.velero.io \"dm-11\" not found" Restore=velero/dm-15 logSource="pkg/controller/restore_controller.go:178"
time="2023-08-01T08:16:33Z" level=error msg="Reconciler error" controller=restore controllerGroup=velero.io controllerKind=Restore error="can't get backup info, backup: dm-11: can't find backup velero/dm-11: Backup.velero.io \"dm-11\" not found" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/restore_controller.go:446" error.function=github.com/vmware-tanzu/velero/pkg/controller.fetchBackupInfoInternal logSource="/go/pkg/mod/github.com/bombsimon/logrusr/v3@v3.0.0/logrusr.go:123" name=dm-15 namespace=velero reconcileID="\"6b4932eb-9f25-493f-9f2a-cde776f54380\"" restore="{\"name\":\"dm-15\",\"namespace\":\"velero\"}"
```

The backup deletion controller should wait the restores be deleted before removing the backup: https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/backup_deletion_controller.go#L380

And the backup deletion controller doesn't need to clean the restore data in the storage anymore as this is already done by the restore deletion controller: https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/backup_deletion_controller.go#L373

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by allenxu404**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #6576 #6583

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/cmd/cli/uninstall/uninstall.go [hunk 1]
```diff
@@ -25,23 +25,31 @@ import (
...
 	velerov1api "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
 	"github.com/vmware-tanzu/velero/pkg/client"
 	"github.com/vmware-tanzu/velero/pkg/cmd"
 	"github.com/vmware-tanzu/velero/pkg/cmd/cli"
+	"github.com/vmware-tanzu/velero/pkg/controller"
 	"github.com/vmware-tanzu/velero/pkg/install"
+	kubeutil "github.com/vmware-tanzu/velero/pkg/util/kube"
 )
 
+var gracefulDeletionMaximumDuration = 30 * time.Second
```
Comment (ywk253100) [inline pkg/cmd/cli/uninstall/uninstall.go:51]: How about increasing the timeout value? If there are lots of restores or the network is bad, 30 seconds may be not enough.

Comment (allenxu404) [reply pkg/cmd/cli/uninstall/uninstall.go]: Done

**Review by ywk253100 — APPROVED** [review]

**Review by blackpiglet — APPROVED** [review]
