### PR TITLE
fix: load AWS config and assume role

### LINKED ISSUE #3142: AWS Role to be assumed not being read from configuration file.
### Versions
Version: v1.3.2
AWS Plugin Version: 1.0.1
AWS EKS Version: 1.15

### Description
Though my config file has role_arn and source_profile entries, it does not appear the role is being assumed.

### Details
`$ velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.0.1 --bucket backup-velero  --secret-file ./config`

```
time="2020-04-07T23:01:43Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = AccessDenied: Access Denied
```
`./config`
```
[default]
region = us-west-2
role_arn=arn:aws:iam::99999999999:role/IAM_CARole_XXX
source_profile=eks

[profile eks]
aws_access_key_id = AKIAXXXXXXXX
aws_secret_access_key = mfrXXXXXXXXXXXXXXXX
```
### Additional Information
I ran up another pod in the same cluster using the `mesosphere/aws-cli:latest` docker image. Then `exec`ed into the image and copied the same config (pointed to with `AWS_CONFIG_FILE` environment variable ). All the `aws s3` commands worked fine on the bucket.

I suspect the `stscreds.NewCredentials` call needs to be used as described in **Assume Role** section [here](stscreds.NewCredentials).

### PR DESCRIPTION
**Pull request by luisdavim**
Thank you for contributing to Velero!

# Please add a summary of your change

Currently `GetS3Credentials` is just getting the credentials from the config file directly but if we let the AWS SDK do it it will support things like assuming roles and source profiles.

# Does your change fix a particular issue?

Fixes #3142 for volumes where the fix for resource backups is in https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/168

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/repository/config/aws.go [hunk 1]
```diff
@@ -51,32 +56,45 @@ func GetS3ResticEnvVars(config map[string]string) (map[string]string, error) {
...
 
+	opts := session.Options{}
 	credentialsFile := config[CredentialsFileKey]
 	if credentialsFile == "" {
 		credentialsFile = os.Getenv("AWS_SHARED_CREDENTIALS_FILE")
 	}
-
-	if credentialsFile == "" {
-		return nil, errors.New("missing credential file")
+	if credentialsFile != "" {
```
Comment (Lyndon-Li) [inline pkg/repository/config/aws.go:86]: Looks like `credentialsFile` is never used, should it be set into `opts`? Otherwise, if the credentialFile is from `config` instead of `AWS_SHARED_CREDENTIALS_FILE` env variable, it won't be reached by the SDK.

Comment (luisdavim) [reply pkg/repository/config/aws.go:86]: you are right, I've updated the PR. Thanks.

**Review by Lyndon-Li — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]
