### PR TITLE
Check whether the namespaces specified in namespace filter exist.

### LINKED ISSUE #7928: v1.14.0 Scheduled backup fails if namespace doesn't exist
**What steps did you take and what happened:**
Create a schedule and include a non-existing namespace:

```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-application-backup
  namespace: velero
  annotations:
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: velero
spec:
  useOwnerReferencesInBackup: false
  schedule: "0 0 * * *"
  template:
    csiSnapshotTimeout: 14400s
    hooks: {}
    includeClusterResources: false
    includedNamespaces:
    - my-namespace
    - a-non-existing-namespace
    itemOperationTimeout: 0s
    metadata: {}
    ttl: 720h
```

**What did you expect to happen:**

Velero before v1.14.0 executed the backup without complaint. Velero v1.14.0 stops the scheduled backup instantly and sets the status `FailedValidation` instead of executing the backup and e.g. setting the `PartiallyFailed` status. This new behavior is dangerous (or even critical?) as scheduled backups become fragile and stop working as soon as a defined namespace doesn't exist anymore.

### PR DESCRIPTION
**Pull request by blackpiglet**
Check whether the namespaces specified in the `backup.Spec.IncludeNamespaces` exist during backup resource collection.
If not, log an error message to mark the backup as `PartiallyFailed`.

Thank you for contributing to Velero!

# Please add a summary of your change
Create a backup with a namespace filter, and specify a non-existing namespace in the filter.
The backup fails with a validation error.

```
velero backup create --include-namespaces=kube-public,invalid invalid-tst
Backup request "invalid-tst" submitted successfully.
Run `velero backup describe invalid-tst` or `velero backup logs invalid-tst` for more details.

k -n velero get backup invalid-tst  -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/resource-timeout: 10m0s
    velero.io/source-cluster-k8s-gitversion: v1.29.4-gke.1043002
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "29"
  creationTimestamp: "2024-07-02T03:01:38Z"
  generation: 2
  labels:
    velero.io/storage-location: default
  name: invalid-tst
  namespace: velero
  resourceVersion: "100954432"
  uid: ee6eb635-1fe2-4d3f-8278-050c813fe042
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  hooks: {}
  includedNamespaces:
  - kube-public
  - invalid
  itemOperationTimeout: 4h0m0s
  metadata: {}
  snapshotMoveData: false
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - default
status:
  expiration: "2024-08-01T03:01:38Z"
  formatVersion: 1.1.0
  phase: FailedValidation
  validationErrors:
  - 'Invalid included/excluded namespace lists: Namespace "invalid" not found'
  version: 1
```

This is not an ideal behavior. The preferred behavior should be making the backup as `PartiallyFailed` and continues the backup process.
https://github.com/vmware-tanzu/velero/issues/7928#issuecomment-2199548047

# Does your change fix a particular issue?

Fixes #7928 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/backup/item_collector.go [hunk 1]
```diff
@@ -741,6 +741,19 @@ func (r *itemCollector) collectNamespaces(
 		return nil, errors.WithStack(err)
 	}
 
+	for _, includedNSName := range r.backupRequest.Backup.Spec.IncludedNamespaces {
```
Comment (sseago) [inline pkg/backup/item_collector.go:744]: Since "*" is a valid entry in `IncludedNamespaces`, we should not look for the literal namespace "*" if this is the value of `includedNSName`.

We probably want something like:
```
if includedNSName == "*" {
    continue
}
```

Comment (blackpiglet) [reply pkg/backup/item_collector.go:744]: Thanks. Modified.

**Review by sseago — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

**Comment by srekkas** [comment]
Hi. Can partialFailure be avoided with some parameter? Like ignoreMissingNamespaces: true :)
. I have multiple namespaces included, but in some cases namespaces can be non existent. But backup for all clusters is the same.

**Comment by kaovilai** [comment]
@srekkas see https://github.com/vmware-tanzu/velero/issues/7928
No. you cannot ignore missing namespaces yet.
