### PR TITLE
Fix int/float conversion issues in CRD version remapping plugin

### LINKED ISSUE #2319: Error: unable to convert unstructured item to a v1 CRD: cannot convert int64 to float64
**What steps did you take and what happened:**

Run a full backup of cluster using Restic

**What did you expect to happen:**

No fail during backup

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
```
Found 2 pods, using pod/restic-sgkfd
time="2020-03-04T17:44:27Z" level=info msg="Setting log-level to INFO"
time="2020-03-04T17:44:27Z" level=info msg="Starting Velero restic server v1.3.0 (8fec8ed7fb8b4776b191753497eafeb47f2f9136)" logSource="pkg/cmd/cli/restic/server.go:62"
time="2020-03-04T17:44:28Z" level=info msg="Starting controllers" logSource="pkg/cmd/cli/restic/server.go:156"
time="2020-03-04T17:44:28Z" level=info msg="Controllers started successfully" logSource="pkg/cmd/cli/restic/server.go:199"
time="2020-03-04T17:44:28Z" level=info msg="Starting controller" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:76"
time="2020-03-04T17:44:28Z" level=info msg="Waiting for caches to sync" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:79"
time="2020-03-04T17:44:28Z" level=info msg="Starting controller" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:76"
time="2020-03-04T17:44:28Z" level=info msg="Waiting for caches to sync" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:79"
time="2020-03-04T17:44:28Z" level=info msg="Caches are synced" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:83"
time="2020-03-04T17:44:28Z" level=info msg="Caches are synced" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:83"
time="2020-03-04T17:45:04Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-f6rzx namespace=velero
time="2020-03-04T17:45:05Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-f6rzx namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-04T17:45:05Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-f6rzx namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-04T17:45:05Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-f6rzx namespace=velero
time="2020-03-04T17:45:12Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-f6rzx namespace=velero
time="2020-03-05T11:04:12Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-gc2nt namespace=velero
time="2020-03-05T11:04:16Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-gc2nt namespace=velero
time="2020-03-05T11:04:16Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-d5272 namespace=velero
time="2020-03-05T11:04:16Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-d5272 namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:04:16Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-d5272 namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:04:16Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-d5272 namespace=velero
time="2020-03-05T11:04:20Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-d5272 namespace=velero
time="2020-03-05T11:04:20Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-ct92z namespace=velero
time="2020-03-05T11:04:20Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-ct92z namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:04:20Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-ct92z namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:04:20Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-ct92z namespace=velero
time="2020-03-05T11:04:36Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-ct92z namespace=velero
time="2020-03-05T11:04:37Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-5swgr namespace=velero
time="2020-03-05T11:04:37Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-5swgr namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:04:37Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-5swgr namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:04:37Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-5swgr namespace=velero
time="2020-03-05T11:04:40Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-5swgr namespace=velero
time="2020-03-05T11:14:52Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-544n5 namespace=velero
time="2020-03-05T11:14:52Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-544n5 namespace=velero pvcUID=ca3ef62f-3ecf-4527-a565-32e779cd5920
time="2020-03-05T11:14:52Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-544n5 namespace=velero pvcUID=ca3ef62f-3ecf-4527-a565-32e779cd5920
time="2020-03-05T11:14:52Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-544n5 namespace=velero
time="2020-03-05T11:17:12Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-544n5 namespace=velero
time="2020-03-05T11:17:12Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-c9c5p namespace=velero
time="2020-03-05T11:17:12Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-c9c5p namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:17:12Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-c9c5p namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:17:12Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-c9c5p namespace=velero
time="2020-03-05T11:17:16Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-c9c5p namespace=velero
time="2020-03-05T11:17:16Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-psrrr namespace=velero
time="2020-03-05T11:17:16Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-psrrr namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:17:16Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-psrrr namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:17:16Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-psrrr namespace=velero
time="2020-03-05T11:17:25Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-psrrr namespace=velero
time="2020-03-05T11:17:25Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-zwdt8 namespace=velero
time="2020-03-05T11:17:25Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-zwdt8 namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:17:25Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-zwdt8 namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:17:25Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-zwdt8 namespace=velero
time="2020-03-05T11:17:28Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-zwdt8 namespace=velero
time="2020-03-05T11:27:23Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-nn7h8 namespace=velero
time="2020-03-05T11:27:23Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-nn7h8 namespace=velero pvcUID=ca3ef62f-3ecf-4527-a565-32e779cd5920
time="2020-03-05T11:27:23Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-nn7h8 namespace=velero pvcUID=ca3ef62f-3ecf-4527-a565-32e779cd5920
time="2020-03-05T11:27:23Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-nn7h8 namespace=velero
time="2020-03-05T11:28:20Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-nn7h8 namespace=velero
time="2020-03-05T11:28:21Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-p7nn7 namespace=velero
time="2020-03-05T11:28:21Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-p7nn7 namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:28:21Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-p7nn7 namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:28:21Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-p7nn7 namespace=velero
time="2020-03-05T11:28:25Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-p7nn7 namespace=velero
time="2020-03-05T11:28:25Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-sb8bh namespace=velero
time="2020-03-05T11:28:25Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-sb8bh namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:28:25Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-sb8bh namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:28:25Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-sb8bh namespace=velero
time="2020-03-05T11:28:38Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-sb8bh namespace=velero
time="2020-03-05T11:28:38Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-5llwt namespace=velero
time="2020-03-05T11:28:38Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-5llwt namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:28:38Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-5llwt namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:28:38Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-5llwt namespace=velero
time="2020-03-05T11:28:42Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-5llwt namespace=velero
time="2020-03-05T11:28:45Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-926tt namespace=velero
time="2020-03-05T11:28:45Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-926tt namespace=velero pvcUID=5e733400-e696-4f2a-85f4-4ee1458bb664
time="2020-03-05T11:28:45Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-926tt namespace=velero pvcUID=5e733400-e696-4f2a-85f4-4ee1458bb664
time="2020-03-05T11:28:45Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-926tt namespace=velero
time="2020-03-05T11:30:48Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-926tt namespace=velero
```

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

```
Name:         test-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  PartiallyFailed (run `velero backup logs test-backup` for more information)

Errors:    1
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-03-05 12:27:08 +0100 CET
Completed:  2020-03-05 12:30:54 +0100 CET

Expiration:  2020-04-04 13:27:08 +0200 CEST

Persistent Volumes: <none included>

Restic Backups (specify --details for more information):
  Completed:  5
```

* `velero backup logs <backupname>`

```
[...]
resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=resticrepositories.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=resticrepositories.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=restores.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=restores.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=schedules.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=schedules.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=serverstatusrequests.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=serverstatusrequests.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=volumesnapshotclasses.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=volumesnapshotclasses.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="1 errors encountered backup up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:283" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions
time="2020-03-05T11:30:53Z" level=error msg="Error backing up item" backup=velero/test-backup error="error executing custom action (groupResource=customresourcedefinitions.apiextensions.k8s.io, namespace=, name=volumesnapshotcontents.snapshot.storage.k8s.io): rpc error: code = Unknown desc = unable to convert unstructured item to a v1 CRD: cannot convert int64 to float64" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:334" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*defaultItemBackupper).executeActions" group=apiextensions.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:287" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=volumesnapshotlocations.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=volumesnapshotlocations.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=volumesnapshots.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=volumesnapshots.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up group" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/group_backupper.go:101"
time="2020-03-05T11:30:53Z" level=info msg="Backing up resource" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:105" resource=priorityclasses
time="2020-03-05T11:30:53Z" level=info msg="Listing items" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:226" namespace= resource=priorityclasses
time="2020-03-05T11:30:53Z" level=info msg="Retrieved 2 items" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:240" namespace= resource=priorityclasses
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=system-cluster-critical namespace= resource=priorityclasses.scheduling.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=system-node-critical namespace= resource=priorityclasses.scheduling.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Backing up group" backup=velero/test-backup group=coordination.k8s.io/v1 logSource="pkg/backup/group_backupper.go:101"
time="2020-03-05T11:30:53Z" level=info msg="Backing up resource" backup=velero/test-backup group=coordination.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:105" resource=leases
time="2020-03-05T11:30:53Z" level=info msg="Listing items" backup=velero/test-backup group=coordination.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:226" namespace= resource=leases
time="2020-03-05T11:30:53Z" level=info msg="Retrieved 5 items" backup=velero/test-backup group=coordination.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:240" namespace= resource=leases
[...]
```

* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**

```
time="2020-03-05T11:30:53Z" level=info msg="1 errors encountered backup up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:283" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions
time="2020-03-05T11:30:53Z" level=error msg="Error backing up item" backup=velero/test-backup error="error executing custom action (groupResource=customresourcedefinitions.apiextensions.k8s.io, namespace=, name=volumesnapshotcontents.snapshot.storage.k8s.io): rpc error: code = Unknown desc = unable to convert unstructured item to a v1 CRD: cannot convert int64 to float64" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:334" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*defaultItemBackupper).executeActions" group=apiextensions.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:287" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions
```

**Environment:**

- Velero version (use `velero version`): v1.3.0
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Scaleway
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by nrb**
Fixes #2319

### CODE REVIEW

File: pkg/backup/remap_crd_version_action.go [hunk 1]
```diff
@@ -61,6 +61,7 @@ func (a *RemapCRDVersionAction) Execute(item runtime.Unstructured, backup *v1.Ba
 	}
 
 	// We've got a v1 CRD, so proceed.
+	// TODO: why is this causing int/float errors?
 	var crd apiextv1.CustomResourceDefinition
 	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(item.UnstructuredContent(), &crd); err != nil {
```
Comment (nrb) [inline pkg/backup/remap_crd_version_action.go]: Changing this to a JSON marshalling dance causes the unit test to pass, but I have no measured impact on actual restores yet.

```go
	var crd apiextv1.CustomResourceDefinition
	js, err := json.Marshal(item.UnstructuredContent())
	if err != nil {
		return nil, nil, errors.Wrap(err, "unable to convert unstructured item to JSON")
	}

	if err = json.Unmarshal(js, &crd); err != nil {
		return nil, nil, errors.Wrap(err, "unable to convert JSON to CRD")
	}
```
I'm also exploring using the helpers in the `unstructured` package, but I think they may be unwieldy given the number of fields we access in this plugin.

I'll try to see if I can log any sort of timing data to help make this decision.

Comment (nrb) [reply pkg/backup/remap_crd_version_action.go]: Based on the timing data at https://docs.google.com/spreadsheets/d/16YNPgBOlAzSBxyg_6Bsm0cLtZ2hBob0Vr_nz9vwYYL8/edit?usp=sharing in the `crd-log` tab, I'm leaning towards doing the JSON marshalling dance and no the unstructured helpers & casting for readability. Thoughts, @skriss and @ashish-amarnath?

Comment (skriss) [reply pkg/backup/remap_crd_version_action.go]: So basically, using `FromUnstructured` does not properly convert the integer value to a float, but marshaling the Unstructured to JSON and then using `json.Unmarshal` does? Is that correct?

Comment (nrb) [reply pkg/backup/remap_crd_version_action.go]: Yep, that appears to be the case. Also in my test case, if the value was `5.0`, it would fail with `FromUnstructured`, but it would be fine with `5.2`. So any whole number appears to have problems with the `FromUnstructured` implementation right now.

Comment (skriss) [reply pkg/backup/remap_crd_version_action.go]: OK. I'm onboard with going through JSON for this -- let's just add a good comment explaining.

Comment (skriss) [reply pkg/backup/remap_crd_version_action.go]: If you wanted to do the same in the other spot too, that'd be OK - not sure if it's worth changing or not, up to you.

Comment (ashish-amarnath) [reply pkg/backup/remap_crd_version_action.go]: The problem sounds super weird! But the changes seem fine. 
The impact of the change doesn't seem to be that much. This may be one exception to keep commented code. WDYT?

Comment (nrb) [reply pkg/backup/remap_crd_version_action.go]: @ashish-amarnath I'll keep a mention of the full path to the call, but not all the error handling, as well as a mention of the Kubernetes issue.

@skriss I'll look at the other site and see if it's worth doing the JSON marshalling. If it's a single field, it's probably not worth it.

File: pkg/backup/remap_crd_version_action_test.go [hunk 2]
```diff
@@ -58,4 +59,23 @@ func TestRemapCRDVersionAction(t *testing.T) {
 		require.NoError(t, err)
 		assert.Equal(t, "apiextensions.k8s.io/v1beta1", item.UnstructuredContent()["apiVersion"])
 	})
+
+	t.Run("Having an integer on a float64 field should work (issue 2319)", func(t *testing.T) {
+		b := builder.ForV1CustomResourceDefinition("test.velero.io")
+		schema := builder.ForJSONSchemaPropsBuilder().Maximum(5).Result()
```
Comment (ashish-amarnath) [inline pkg/backup/remap_crd_version_action_test.go]: magic number `5`

Comment (skriss) [reply pkg/backup/remap_crd_version_action_test.go]: I think this is the test data (i.e. an integer in the float field).

**Comment by skriss** [comment]
LGTM @nrb, just need to add a changelog

File: pkg/backup/remap_crd_version_action_test.go (hunk 2 above)
Comment (nrb) [reply pkg/backup/remap_crd_version_action_test.go]: Correct, this is test data for an int in a float field.

Comment (nrb) [reply pkg/backup/remap_crd_version_action_test.go]: Added comment here to explain it

**Comment by nrb** [comment]
@ashish-amarnath @carlisia Could you please review this today? I'd like to release a v1.3.1 with this fix on Tuesday, March 10 if possible. @NissesSenap tested an image of this with his data and had no issues, but would like to make sure we're all ok with the solution.
