### PR TITLE
Account for possible missing schemas on v1 CRDs

### LINKED ISSUE #2249: Restore CRD panic if the CRD without structural schema
**What steps did you take and what happened:**

Install velero by [helm chart](https://github.com/vmware-tanzu/helm-charts), backup and restore the CRD, bump out errors when describing the restore name.
`rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference`

**What did you expect to happen:**

Restore CRD without error.

**The output of the following commands will help us better understand what's going on**:

I think the main problem comes with this line https://github.com/vmware-tanzu/velero/blob/5b1280c/pkg/restore/crd_v1_preserve_unknown_fields_action.go#L79

Not every CRD includes OpenAPIV3Schema, such as https://github.com/vmware-tanzu/helm-charts/blob/e32ce47/charts/velero/crds/backups.yaml and https://github.com/dexidp/dex/blob/34dcf6c/scripts/manifests/crds/authcodes.yaml.

I think the correct solution to fix CRD is when backing up, to back up its original CRD apiVersion, not server-preferred apiVersion which is `v1` version in k8s 1.16+ cluster.
Then at restoring, velero restores the original CRD apiVersion.
My 2 cents.

The problem is how to backup the original CRD apiVersion :thinking: ? Since after k8s 1.16+ cluster, via webhook conversion, all the CRD apiVersion converts from `v1beta1` to `v1`.

---

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
```
Errors:
  Velero:     <none>
  Cluster:  error preparing customresourcedefinitions.apiextensions.k8s.io/authcodes.dex.coreos.com: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/authrequests.dex.coreos.com: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/backups.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/backupstoragelocations.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/connectors.dex.coreos.com: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/deletebackuprequests.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/downloadrequests.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/oauth2clients.dex.coreos.com: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/offlinesessionses.dex.coreos.com: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/passwords.dex.coreos.com: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/podvolumebackups.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/podvolumerestores.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/refreshtokens.dex.coreos.com: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/resticrepositories.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/restores.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/schedules.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/serverstatusrequests.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/signingkeies.dex.coreos.com: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
            error preparing customresourcedefinitions.apiextensions.k8s.io/volumesnapshotlocations.velero.io: rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference
  Namespaces: <none>

Backup:  backup2slave

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto
```
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.2.0
	Git commit: 5d008491bbf681658d3e372da1a9d3a21ca4c03c
Server:
	Version: v1.3.0-beta.1`
```
- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-28T12:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by nrb**
Fixes #2249 

If a v1beta1 CRD without a Schema was submitted to a Kubernetes v1.16
cluster, then Kubernetes will serve it back as a v1 CRD without a
schema.

However, when Velero tries to restore this document, the request will be
rejected as a v1 CRD must have a schema.

This commit has some defensive coding on the restore side, as well as
potential fixes on the backup side for getting around this.

In draft until we reach some consensus on a solution.

Signed-off-by: Nolan Brubaker <brubakern@vmware.com>

### CODE REVIEW

**Comment by nrb** [comment]
In its current form, this will fail CI, as I have 2 competing solutions in code I would like folks to look at and provide feedback on.

File: pkg/backup/remap_crd_version_action.go [hunk 1]
```diff
@@ -0,0 +1,97 @@
+/*
+Copyright 2017 the Velero contributors.
```
Comment (nrb) [inline pkg/backup/remap_crd_version_action.go]: TODO: set this copyright to 2020.

File: pkg/backup/remap_crd_version_action.go [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+		return nil, nil, errors.Wrap(err, "unable to convert unstructured item to CRD")
+	}
+
+	log := a.logger.WithField("plugin", "RemapCRDVersionAction").WithField("CRD", crd.Name)
+
+	// TODO: Is it possible or likely that a CRD had multiple versions without a Schema?
+	if len(crd.Spec.Versions) == 1 && crd.Spec.Versions[0].Schema == nil {
+		log.Debug("CRD is a candidate for v1beta1 backup")
+
+		// Two solutions are presented here, and they both appear to work. I've uncommented them both for readability; they won't necessarily compile this way.
```
Comment (nrb) [inline pkg/backup/remap_crd_version_action.go]: TODO: pick a solution and remove the other.

File: pkg/restore/crd_v1_preserve_unknown_fields_action.go [hunk 3]
```diff
@@ -74,6 +79,11 @@ func (c *CRDV1PreserveUnknownFieldsAction) Execute(input *velero.RestoreItemActi
...
 		// Make sure all versions are set to preserve unknown fields
 		for _, v := range crd.Spec.Versions {
+			// If the Schema is nil, there are no nested fields to set, so skip over it for this version.
+			if v.Schema == nil {
+				continue
+			}
+
 			// Use the address, since the XPreserveUnknownFields value is undefined or true (false is not allowed)
 			preserve := true
 			v.Schema.OpenAPIV3Schema.XPreserveUnknownFields = &preserve
```
Comment (nrb) [inline pkg/restore/crd_v1_preserve_unknown_fields_action.go]: TODO: `Schema.OpenAPIV3Schema` could also be a nil pointer, so check it before accessing, too.

Comment (jenting) [reply pkg/restore/crd_v1_preserve_unknown_fields_action.go]: The `Schema.OpenAPIV3Schema.XPreserveUnknownFields` could also be a nil pointer.

File: pkg/backup/remap_crd_version_action.go [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+	// Pros:
+	//   - Relatively simple; just changing a string
+	//   - Data is the same as what's in the source Kubernetes cluster - the only reason we got it as a v1 instance was due to our usage of the preferred version endpoint.
+	// Cons:
+	//   - Data in the backup won't be valid for as long - v1beta1 CRDs will have to be upgraded sooner rather than later - but is that Velero's problem?
+
+	// Since we can't manipulate an Unstructured's Object map directly, get a copy to manipulate before setting it back
+	tempMap := item.UnstructuredContent()
+
+	if err := unstructured.SetNestedField(tempMap, "apiextensions.k8s.io/v1beta1", "apiVersion"); err != nil {
```
Comment (skriss) [inline pkg/backup/remap_crd_version_action.go]: does this actually work (namely, on the restore side)? I woulda thought there would be more logic required to convert a v1 CRD back to a v1beta1 that would actually be accepted by the API server on restore.

Comment (nrb) [reply pkg/backup/remap_crd_version_action.go]: So far in my tests, yes, both of these solutions will be accepted on restore.

Changing the version field appears to get it accepted and then returned via the `v1` API endpoint in much the same way as creating it via Helm does.

Comment (skriss) [reply pkg/backup/remap_crd_version_action.go]: Huh, interesting. I woulda thought there'd be incompatible fields in the v1 API that couldn't be submitted as v1beta1, but I guess this is what's meant by forwards- and backwards-compatible in Kubernetes API changes.

If this is valid for all scenarios, then I agree with @jenting that this is probably the preferable path

Comment (nrb) [reply pkg/backup/remap_crd_version_action.go]: > I woulda thought there'd be incompatible fields in the v1 API that couldn't be submitted as v1beta1, but I guess this is what's meant by forwards- and backwards-compatible in Kubernetes API changes.

Well, the problem was that these `v1beta1` CRDs were being returned from the v1 endpoint without a schema entry at all, then velero couldn't restore them. So the Kube API was happily serving them (even as they were invalid), but not accepting them back at the v1 endpoint.

Comment (skriss) [reply pkg/backup/remap_crd_version_action.go]: right, I get that - I'm just saying that behind the scenes, Kube has conversion logic to convert them from v1beta1 to v1 and vice-versa, so that they can be served from either API version. I'm surprised that you can just take the v1 YAML representation, change the version, and apply it directly to the v1beta1 version without going through the Kube conversion logic.

Comment (nrb) [reply pkg/backup/remap_crd_version_action.go]: Here's the diff of what I applied vs what I got back - the only things that got applied appear to be a `versions` slice and the `PerserveUnknownFields` field. All of these things are valid in v1beta1.

`diff authcodes.yaml from_v1.yaml`

```diff
1c1
< apiVersion: apiextensions.k8s.io/v1beta1
---
> apiVersion: apiextensions.k8s.io/v1
3a4,8
>   annotations:
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"authcodes.dex.coreos.com"},"spec":{"group":"dex.coreos.com","names":{"kind":"AuthCode","listKind":"AuthCodeList","plural":"authcodes","singular":"authcode"},"version":"v1"}}
>   creationTimestamp: "2020-02-12T22:13:38Z"
>   generation: 1
4a10,12
>   resourceVersion: "3645"
>   selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/authcodes.dex.coreos.com
>   uid: f73f31e4-4613-4f45-9498-adff20be05a1
5a14,15
>   conversion:
>     strategy: None
12c22,46
<   version: v1
---
>   preserveUnknownFields: true
>   scope: Namespaced
>   versions:
>   - name: v1
>     served: true
>     storage: true
> status:
>   acceptedNames:
>     kind: AuthCode
>     listKind: AuthCodeList
>     plural: authcodes
>     singular: authcode
>   conditions:
>   - lastTransitionTime: "2020-02-12T22:13:38Z"
>     message: no conflicts found
>     reason: NoConflicts
>     status: "True"
>     type: NamesAccepted
>   - lastTransitionTime: "2020-02-12T22:13:38Z"
>     message: the initial names have been accepted
>     reason: InitialNamesAccepted
>     status: "True"
>     type: Established
>   storedVersions:
>   - v1
```

**Comment by skriss** [comment]
@carlisia @ashish-amarnath please weigh in if you have any thoughts here!

**Comment by nrb** [comment]
Pushed an update that goes with option 2, along with some tests.

It currently fails tests because I updated the CRD builders to use the v1 types and didn't realize til after that we still use v1beta1 for checking readiness...so I may have to split the builder into two sets.

File: pkg/restore/crd_v1_preserve_unknown_fields_action.go (hunk 3 above)
Comment (skriss) [reply pkg/restore/crd_v1_preserve_unknown_fields_action.go]: do we need to add a nil-check for `v.Schema.OpenAPIV3Schema`?

File: pkg/backup/remap_crd_version_action.go [hunk 5]
```diff
@@ -0,0 +1,116 @@
...
+
+// NewRemapCRDVersionAction instantiates a new RemapCRDVersionAction plugin.
+func NewRemapCRDVersionAction(logger logrus.FieldLogger) *RemapCRDVersionAction {
+	return &RemapCRDVersionAction{logger: logger}
+}
+
+// AppliesTo selects the resources the plugin should run against. In this case, CustomResourceDefinitions.
+func (a *RemapCRDVersionAction) AppliesTo() (velero.ResourceSelector, error) {
+	return velero.ResourceSelector{
+		IncludedResources: []string{"customresourcedefinition.apiextensions.k8s.io"},
```
[the remark this answers is not in the document]
Comment (nrb) [reply pkg/backup/remap_crd_version_action.go]: Singular's worked fine in all of my testing so far.

File: pkg/restore/crd_v1_preserve_unknown_fields_action.go (hunk 3 above)
Comment (nrb) [reply pkg/restore/crd_v1_preserve_unknown_fields_action.go]: Ah, yeah, thanks!

Comment (nrb) [reply pkg/restore/crd_v1_preserve_unknown_fields_action.go]: @jenting I think the `XPreserveUnknownFields` nil pointer is fine, since we're setting it here explicitly.

File: pkg/backup/remap_crd_version_action.go [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+	apiVersion, ok, err := unstructured.NestedString(item.UnstructuredContent(), "apiVersion")
+	if err != nil {
+		return nil, nil, errors.Wrap(err, "unable to read apiVersion from CRD")
+	}
+	if ok && apiVersion != "apiextensions.k8s.io/v1" {
+		a.logger.Info("Exiting RemapCRDVersionAction, CRD is not v1")
+		return item, nil, nil
+	}
+
+	a.logger.Infof("Unstructured looked like: %#v", item.UnstructuredContent())
```
Comment (skriss) [inline pkg/backup/remap_crd_version_action.go]: should we bump this down to debug?

Comment (nrb) [reply pkg/backup/remap_crd_version_action.go]: Actually we can just remove this, it was from writing some tests.

**Comment by skriss** [comment]
only other thing is we need a changelog; after that, LGTM if the testing looks OK

**Comment by nrb** [comment]
Results of my testing with the latest changes:

Backup taken on Kubernetes 1.15 restores back to Kubernetes 1.15 as v1beta1 (as expected). It also restores to Kubernetes 1.16 and 1.17. The document is stored as v1beta1.

Backup taken on Kubernetes 1.16 restores back to Kubernetes 1.16 and 1.17 as v1beta1 but gets upgraded to v1 through the upgrade webhook, as expected. The document is stored as v1beta1 in the backup. Retrieving it via `kubectl get --raw /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/authcodes.dex.coreos.com` returns a v1beta1 CRD.

Backup taken on Kubernetes 1.17 restores back to Kubernetes 1.17 as v1beta1 but gets upgraded to v1 through the upgrade webhook, as expected. The document is stored as v1beta1 in the backup. Retrieving it from `/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/authcodes.dex.coreos.com` returns a v1beta1 CRD.

**Comment by nrb** [comment]
@skriss Changelog added.

@jenting I added your `NonStructuralSchema` condition case to the plugin, though I've not encountered it myself.

**Comment by jenting** [comment]
I encountered when testing with [contour crds](https://github.com/helm/charts/tree/master/stable/contour/crds).

**Comment by skriss** [comment]
@carlisia or @ashish-amarnath let's get this merged ASAP so we can release a second beta, thanks!

**Comment by ashish-amarnath** [comment]
Over to @carlisia for the merge

File: pkg/backup/remap_crd_version_action.go [hunk 7]
```diff
@@ -0,0 +1,114 @@
...
+
+	// Looking for 1 version should be enough to tell if it's a v1beta1 CRD, as all v1beta1 CRD versions share the same schema.
+	// v1 CRDs can have different schemas per version
+	// The silently upgraded versions will often have a `versions` entry that looks like this:
+	//   versions:
+	//   - name: v1
+	//     served:  true
+	//     storage: true
+	// This is acceptable when re-submitted to a v1beta1 endpoint on restore.
+	if len(crd.Spec.Versions) > 0 {
```
Comment (kaovilai) [inline pkg/backup/remap_crd_version_action.go:79]: Would this be a more accurate condition for this?
```suggestion
	if len(crd.Spec.Versions) == 1 {
```
