### PR TITLE
Fix BSL controller to avoid invoking init() on all BSLs regardless of…

### LINKED ISSUE #2991: BSL controller loop always invokes init() regardless of backup location's ValidationFrequency
**What steps did you take and what happened:**
After upgrading to Velero v1.5.1, we observed that BSL controller always invokes init() for existing backup storage locations regardless of the BSL's ValidationFrequency (we tried setting BSL validationFrequency to 0 to skip validation but this didn't help). This is an issue since for some objectstore plugins the init() method could be an expensive call, for instance our objectstore plugin init() method opens connection to the backup target and creates directories/buckets  if they don't exist as part of initializing the backup repository. Looking at the Velero [BSL controller code](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/backup_storage_location_controller.go#L80), we first initialize backupStore prior to the check for whether the BSL is ready to be validated:

```
                backupStore, err := r.NewBackupStore(location, pluginManager, log)
		if err != nil {
			log.WithError(err).Error("Error getting a backup store")
			continue
		}

		if !storage.IsReadyToValidate(location.Spec.ValidationFrequency, location.Status.LastValidationTime, r.DefaultBackupLocationInfo, log) {
			log.Debug("Backup location not ready to be validated")
			continue
		}
```
I think moving r.NewBackupStore() to after the check for whether BSL is ready to be validated will fix this issue to avoid invoking init() on all backup storage locations whenever the controller loop runs.

**What did you expect to happen:**
Setting BSL validationFrequency to 0 should skip validation for the backup storage location.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.5.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):1.18
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by betta1**
… ValidationFrequency

This fixes #2991 

Signed-off-by: Bett, Antony <antony.bett@dell.com>

### CODE REVIEW

File: pkg/controller/backup_storage_location_controller.go [hunk 1]
```diff
@@ -77,14 +77,14 @@ func (r *BackupStorageLocationReconciler) Reconcile(req ctrl.Request) (ctrl.Resu
 			defaultFound = true
 		}
 
-		backupStore, err := r.NewBackupStore(location, pluginManager, log)
-		if err != nil {
-			log.WithError(err).Error("Error getting a backup store")
+		if !storage.IsReadyToValidate(location.Spec.ValidationFrequency, location.Status.LastValidationTime, r.DefaultBackupLocationInfo, log) {
```
Comment (nrb) [inline pkg/controller/backup_storage_location_controller.go:80]: I think this only addresses the case where validation frequency is 0, unless I'm misreading something.

If validation frequency is 1 minute (the server's default), then it will still invoke the Init() function. Is that acceptable in your case?

**Review by nrb — APPROVED** [review]
I haven't run this against a cluster, but I think this does fix the issue of invoking the plugin's Init() function every reconciliation loop (roughly once per second), since it exits the loop iteration early based on the validation frequency, which is roughly once a minute based on the server default.

There may be a longer term fix here where we can instantiate a plugin process and let it live longer, but I think that has bigger implications that I don't understand at the moment.

File: pkg/controller/backup_storage_location_controller.go (hunk 1 above)
Comment (betta1) [reply pkg/controller/backup_storage_location_controller.go:80]: This change ensures we first check if the BSL is ready to be validated and then initialize the backup store only for those BSLs that pass the check. It should address all cases where validation frequency is 0 as well as user specified validation frequency or server's default validation frequency.

**Review by carlisia — APPROVED** [review]
This was a very good catch, thank you. 👍

**Comment by carlisia** [comment]
I did run this against a cluster.

**Comment by betta1** [comment]
Thanks @carlisia @nrb
