### PR TITLE
Fixes #(8816) When specifying LabelSelector on restore, related items such as PVC and VolumeSnapshot are not included

### LINKED ISSUE #8816: When specifying LabelSelector on restore, related items such as PVC and VolumeSnapshot are not included
**What steps did you take and what happened:**

A namespace has two applications, Deployment1/Pod1/PVC1/VS1 and Deployment2/Pod2/PVC2/VS2.
Both deployment and pods are labeled using labels "app=app1" and "app=app2".
Running a backup with the app1 label selector correctly backs up the first application, including the PVC and the VS created during backup because the PVC and VS are returned as additional items by BIA plugins.

However, if we do filtering on restore, this does not work. Back up entire namespace without label selector, then restore using app1 label selector. In this case, neither the PVC nor the VS will be included.

**What did you expect to happen:**
The restore should include the PVC and VS for app1 but not the PVC and VS for app2.

Two possible approaches to solve this:
1) Update RIAs to include these as additional items:
  - For including PVCs, it's not complicated -- just add the mounted PVCs as additional items for the pod action, just as we do for backup.
  - For VS it's more complicated since the VS needs to already be restored when the current PVC action runs, which means this would require a new RIA that runs before this one.
2) Restore infra dependency tracking
 - This avoids needing to write the RIAs, but now we need to track item-to-item dependencies based on what BIAs return additional items at backup time
 - We need to track the dependency across multiple levels -- VS->PVC->Pod

For 2) it might look something like this:
- On backup, create a map where the keys are item identifiers, and the values are also item identifiers
- In backup workflow, every time a BIA returns an additional item, we add an entry to this map with the key as the additional item returned, and the value as the current item.
- This map needs to be saved in object storage as part of the backup process
- On restore, when iterating over items to back up:
  -  If item matches label selectors, add to the restore list and move on
  -  else look up item in dependency map. If not found, skip item and move on.
  - If item is found in dependency map, perform label selector match on the item linked to. If match, include, if not, repeat process (i.e. is this second item in the dependency map, if so, follow steps above)

We need to make sure we avoid infinite loops here on the restore side. Should be easy enough to do -- just track the items we've already looked up and when we get a repeated item, we're done, move on.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by amastbau**
This pull request introduces several improvements to the CSI plugin's backup and restore actions to resolve issue #8816.

Key changes include:

- Moves the logic for patching the PVC's request size to the backup action. This is done to resolve a dependency on the VolumeSnapshot's existence during restore, as the snapshot may not have been restored yet when the PVC action runs.
- Includes the associated VolumeSnapshot as an additional item during the CSI PVC backup action to ensure it is always included, even when not applying a label selector.
- Corrects a log message in the VolumeSnapshot CSI action to properly indicate that the associated VolumeSnapshotContent is also included in the backup.

Fixes #8816

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by kaovilai — CHANGES_REQUESTED** [review]
You have existing todo
> [Created a changelog file (make new-changelog)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment /kind changelog-not-required on this PR.

also retest prow command won't work here.

File: pkg/backup/actions/csi/pvc_action.go [hunk 1]
```diff
@@ -252,6 +254,23 @@ func (p *pvcBackupItemAction) Execute(
 		return nil, nil, "", nil, err
 	}
 
+	// Wait until VS associated VSC snapshot handle created before
+	// continue.we later require the vsc restore size
+	vsc, err := csi.WaitUntilVSCHandleIsReady(
```
Comment (blackpiglet) [inline pkg/backup/actions/csi/pvc_action.go:274]: Not sure about this change.
This does make the logic more unified for both data mover and CSI cases; however, the CSI case already includes a check in the VolumeSnapshot BIA.
It is a bit redundant to also check in the PVC BIA.
https://github.com/vmware-tanzu/velero/blob/9500f0b82f1ec1df9ebe83c4f6896b1a32c99a38/pkg/backup/actions/csi/volumesnapshot_action.go#L102-L111

File: pkg/backup/actions/csi/pvc_action.go [hunk 2]
```diff
@@ -563,3 +571,61 @@ func NewPvcBackupItemAction(f client.Factory) plugincommon.HandlerInitializer {
...
 }
+
+func setPVCRequestSizeToVSRestoreSize(
+	pvc *corev1api.PersistentVolumeClaim,
+	crClient crclient.Client,
+	volumeSnapshotName string,
+	vsc *snapshotv1api.VolumeSnapshotContent,
+	logger logrus.FieldLogger,
+) error {
+	vs := new(snapshotv1api.VolumeSnapshot)
```
Comment (blackpiglet) [inline pkg/backup/actions/csi/pvc_action.go]: I'm curious why VS is retrieved here, but it is not used in the function.
Is it possible to delete the VS from the function?

File: pkg/backup/actions/csi/pvc_action.go (hunk 1 above)
Comment (amastbau) [reply pkg/backup/actions/csi/pvc_action.go:274]: Thanks for the comment. You're right that the volumesnapshot_action also performs a check. However, this pvc_action needs the VolumeSnapshotContent to be ready immediately for two key scenarios: 1) to get the RestoreSize for pure CSI snapshots, and 2) to ensure the snapshot is ready before a data mover upload can start. To handle both cases correctly, I've placed the WaitUntilVSCHandleIsReady call before this logic splits. Please let me know if you think there's a better approach, or if i am missing anything [blackpiglet](https://github.com/blackpiglet)

File: pkg/backup/actions/csi/pvc_action.go (hunk 2 above)
Comment (amastbau) [reply pkg/backup/actions/csi/pvc_action.go]: Thank you! We do not need this vs. I've removed it
[blackpiglet](https://github.com/blackpiglet)

**Review by kaovilai — CHANGES_REQUESTED** [review]
Please resolve PR conflicts.

**Comment by shubham-pampattiwar** [comment]
@amastbau please resolve the PR conflicts, Thanks !

File: pkg/backup/actions/csi/pvc_action.go [hunk 3]
```diff
@@ -252,6 +254,23 @@ func (p *pvcBackupItemAction) Execute(
...
+		vs,
+		p.crClient,
+		p.log,
+		backup.Spec.CSISnapshotTimeout.Duration,
+	)
+	if err != nil {
+		p.log.Errorf(
+			"Fail to wait VolumeSnapshot turned to ReadyToUse: %s",
+			err.Error(),
+		)
```
Comment (kaovilai) [inline pkg/backup/actions/csi/pvc_action.go]:
```go
p.log.Errorf("Failed to wait for VolumeSnapshot %s/%s to become ReadyToUse within timeout %v: %s", 
        vs.Namespace, vs.Name, backup.Spec.CSISnapshotTimeout.Duration, err.Error())
```
Could help to have this info if the logger doesn't already. If you ran this PR and the log line already contained vs.Name then ignore this.

**Review by kaovilai — DISMISSED** [review]

File: pkg/backup/actions/csi/pvc_action.go (hunk 3 above)
Comment (amastbau) [reply pkg/backup/actions/csi/pvc_action.go]: done.added

File: pkg/restore/actions/csi/pvc_action.go [hunk 4]
```diff
@@ -186,24 +155,27 @@ func (p *pvcRestoreItemAction) Execute(
...
-				return nil, errors.WithStack(err)
-			}
+			//To avoid confilcs, vs and vsc get a new uniq name based in restore UID
+			// and vs name old name
+			newVSName := util.GenerateSha256FromRestoreUIDAndVsName(string(input.Restore.UID), vsName)
+
+			p.log.Debugf("Setting PVC source to VolumeSnapshot new name: %s", newVSName)
+			resetPVCSourceToVolumeSnapshot(&pvc, newVSName)
+
+			additionalItems = append(additionalItems, velero.ResourceIdentifier{
```
Comment (blackpiglet) [inline pkg/restore/actions/csi/pvc_action.go:174]: Sorry for the late response.
If the purpose is to include the VolumeSnapshot for CSI PVC restore, we need to add something more to make it work. We need to add them in the MustHave list.

The reason is Velero restore will filter AdditionalItems by the restore's resource filters.
The list in the MustHave list will skip the filters check.

https://github.com/vmware-tanzu/velero/blob/d889ad318b96ad207f8032865b74b81fed2d1f6c/pkg/restore/restore.go#L84-L87

Comment (amastbau) [reply pkg/restore/actions/csi/pvc_action.go:174]: Yeha, we accepted this as a limitation.
Are we sure there might not be  scenario in which user would like to filter out volume snapshots?

Comment (blackpiglet) [reply pkg/restore/actions/csi/pvc_action.go:174]: It depends on the user's knowledge.
If both PVC and VS are labeled, it would work; however, if only the PVC is labeled, it would not work as expected.

If this is by design, then I don't have any other comments.

**Review by blackpiglet — DISMISSED** [review]

File: pkg/backup/actions/csi/pvc_action.go [hunk 5]
```diff
@@ -252,6 +254,21 @@ func (p *pvcBackupItemAction) Execute(
 		return nil, nil, "", nil, err
 	}
 
+	// Wait until VS associated VSC snapshot handle created before
+	// continue.we later require the vsc restore size
+	vsc, err := csi.WaitUntilVSCHandleIsReady(
```
Comment (shubham-pampattiwar) [inline pkg/backup/actions/csi/pvc_action.go:274]: @amastbau @blackpiglet Should we remove the WaitUntilVSCHandleIsReady from VS BIA ?

Comment (blackpiglet) [reply pkg/backup/actions/csi/pvc_action.go:274]: https://github.com/vmware-tanzu/velero/pull/9024#discussion_r2160856133
There was some discussion about this change previously.

Comment (shubham-pampattiwar) [reply pkg/backup/actions/csi/pvc_action.go:274]: yeah thats why I am asking if we should remove the redundant check from VS BIA.

**Comment by shubham-pampattiwar** [comment]
@amastbau @blackpiglet just one question: https://github.com/vmware-tanzu/velero/pull/9024#discussion_r2219667261
Also, I would appreciate if we merge this PR in after the final VGS impl PR gets merged: https://github.com/vmware-tanzu/velero/pull/9019
It will be easier to manage conflicts if any in the current PR IMHO. Thanks for considering.

File: pkg/backup/actions/csi/pvc_action.go (hunk 5 above)
Comment (amastbau) [reply pkg/backup/actions/csi/pvc_action.go:274]: But we still  need to get the vsc @shubham-pampattiwar 
do you suggest getting it without waiting?

Comment (amastbau) [reply pkg/backup/actions/csi/pvc_action.go:274]: we need it to get the restore size

Comment (blackpiglet) [reply pkg/backup/actions/csi/pvc_action.go:274]: Ah, I see.
@amastbau 
@shubham-pampattiwar means to refactor `VS BIA`,  not `PVC BIA` modified by this PR.

Because the VS is returned as an AdditionalItem by `PVC BIA`, it's reasonable to remove the `WaitUntilVSCHandleIsReady` from `VS BIA`.
https://github.com/vmware-tanzu/velero/blob/ff8a070dd37b37aede18ee185f5a11d99054a01e/pkg/backup/actions/csi/volumesnapshot_action.go#L101-L110

Comment (blackpiglet) [reply pkg/backup/actions/csi/pvc_action.go:274]: I also have a PR related to this area.
I think we can merge this PR first, then I will handle the redundancy removal in #9092.

Comment (amastbau) [reply pkg/backup/actions/csi/pvc_action.go:274]: @blackpiglet  we need the vsc not the vs

Comment (amastbau) [reply pkg/backup/actions/csi/pvc_action.go:274]: or did we refer to the vsc?

Comment (blackpiglet) [reply pkg/backup/actions/csi/pvc_action.go:274]: @amastbau 
Yes, you are right about the relation between VSC and PVC BIA.

@shubham-pampattiwar meant, since we already added waiting VSC readiness check in the PVC BIA,
We can delete the existing waiting VSC readiness code from the VS BIA.

I'm OK either way in this PR. I can modify in my following PRs.

Please resolve the conflict first, then I think it's good enough to merge this PR.

**Comment by shubham-pampattiwar** [comment]
@amastbau Please update the PR and fix CI, after that we are good to go I think.

**Review by sseago — DISMISSED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by weshayutin** [comment]
@amastbau @shubham-pampattiwar ya.. we'll want to cherry pick to the 1.16 branch if possible

**Comment by weshayutin** [comment]
@amastbau if you want this before OADP-1.6.. the time is NOW

**Comment by weshayutin** [comment]
https://github.com/vmware-tanzu/velero/pull/9125
