### PR TITLE
Parse resource from backup tarball directly rather than resolving it via discovery service to avoid #4009

### LINKED ISSUE #4009: Unable to delete backup after application is uninstalled
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Backup stuck Deleting
```
./velero backup get
NAME          STATUS     ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
zen-backup1   Deleting   0        0          2021-07-27 20:50:43 -0700 PDT   362d      default            <none>
```

Logs show that a delete action is re-queued since an application's CRD is missing
```
oc logs velero-564475877c-b5945

time="2021-07-30T13:33:35Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=backup-deletion error="error invoking delete item actions: failed to resolve resource into complete group/version/resource: myhttpsservices.myhttps.cpd.ibm.com: no matches for myhttps.cpd.ibm.com/, Resource=myhttpsservices" error.file="/opt/app-root/src/github.com/vmware-tanzu/velero/internal/delete/delete_item_action_handler.go:78" error.function=github.com/vmware-tanzu/velero/internal/delete.InvokeDeleteActions key=oadp-operator/zen-backup1-njv78 logSource="pkg/controller/generic_controller.go:140"
```

Application CRD was included in the backup
```
./velero describe backup zen-backup1 --details | grep my
    - myhttpsservices.myhttps.cpd.ibm.com
    - zen/https-cr-sample-01-myhttps-1627430502419000
    - zen/https-cr-sample-01-myhttps-1627430502419000-7bbbc65565
  myhttps.cpd.ibm.com/v1/MyhttpsService:
```

Application CRD no longer exists in system since it was uninstalled
```
# oc get crd | grep my
#
```

**What did you expect to happen:**

Backup delete to be successful

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  1.6.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): v1.19.0+e49167a
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): RHEL 8.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by ywk253100**
If the resource is a CR and the CRD is removed, the resource cannot be fully resolved via discovery and the backup cannot be deleted anymore. This commit parses the resource from backup tarball directly to avoid this

Fixes #4009

Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: internal/delete/delete_item_action_handler.go [hunk 1]
```diff
@@ -79,7 +80,16 @@ func InvokeDeleteActions(ctx *Context) error {
...
+			if !meta.IsNoMatchError(err) {
+				return errors.Wrapf(err, "failed to resolve resource into complete group/version/resource: %v", resource)
+			}
+			// The resource may not be fully resolved via discovery because it is possible that the
+			// resource is a custom resource while the custom resource definition is already removed.
+			// Skip the resolving from discovery here for this case.
+			// Refer to https://github.com/vmware-tanzu/velero/issues/4009 for more details
+			gvr = schema.ParseGroupResource(resource).WithVersion("")
+
+			ctx.Log.Infof("got \"no matches\" error when trying to resolve the resource %s via discovery, use ParseGroupResource directly, gvr: %s", resource, gvr.String())
```
Comment (jenting) [inline internal/delete/delete_item_action_handler.go:92]: So, we can't use the gvr variable on line 81 directly, right?

File: changelogs/unreleased/4398-ywk253100 [hunk 2]
```diff
@@ -0,0 +1 @@
+Fix #4009: the backup cannot be deleted after the application in uninstalled
```
Comment (jenting) [inline changelogs/unreleased/4398-ywk253100:1]: Shouldn't the changelog be without the issue ID?

File: internal/delete/delete_item_action_handler.go (hunk 1 above)
Comment (ywk253100) [reply internal/delete/delete_item_action_handler.go:92]: Do you mean to replace `gvr, _, err := ctx.DiscoveryHelper.ResourceFor(schema.ParseGroupResource(resource).WithVersion(""))` with `gvr := schema.ParseGroupResource(resource).WithVersion("")` in line 81? 
I'm not sure whether the input `resource` is fully resolved or not. Handle this when getting errors may be more safe?

File: changelogs/unreleased/4398-ywk253100 (hunk 2 above)
Comment (ywk253100) [reply changelogs/unreleased/4398-ywk253100:1]: I'm not aware of this, will remove the issue ID. tks

File: internal/delete/delete_item_action_handler.go (hunk 1 above)
Comment (reasonerjt) [reply internal/delete/delete_item_action_handler.go:92]: I have the same question, @ywk253100 could you please check with Nolan.
Seems the resources in the backup tarball should be resolved already?

**Comment by ywk253100** [comment]
@reasonerjt @jenting Confirm the fix with @nrb, please take a look again

**Review by jenting — APPROVED** [review]

**Comment by reasonerjt** [comment]
I think the code change makes sense to me, but the commit message no longer matches the code change?  
It's currently skip doing any resolution, instead of ignoring the errors.

**Review by jenting — APPROVED** [review]
LGTM

**Review by reasonerjt — APPROVED** [review]
