### PR TITLE
fix race condition in waiting for restic restores to complete

### LINKED ISSUE #2121: Restic podvolumerestore failure not causing restore to fail
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
A restore was created which attempted to write 1 GB of data to a 1MB volume from restic. Restic errors out since it runs out of space to write data to, and the podvolumerestore fails. However, the associated Velero `restore` is in a `Completed` state even though the restic restore failed.

```
[dymurray@pups ~]$ velero describe restore 050d6c20-1c18-11ea-9119-372282f2cae3-9c4pb -n openshift-migration --details
Name:         050d6c20-1c18-11ea-9119-372282f2cae3-9c4pb
Namespace:    openshift-migration
Labels:       app.kubernetes.io/part-of=openshift-migration
              migmigration=0525ece0-1c18-11ea-8753-02bddcc5316e
              migration-stage-restore=0525ece0-1c18-11ea-8753-02bddcc5316e
Annotations:  openshift.io/migrate-copy-phase=final
              openshift.io/migration-registry=172.30.63.96:5000
              openshift.io/migration-registry-dir=/bz-reproduce-registry-e3380ad4-1c17-11ea-8753-02bddcc5316e

Backup:  050d6c20-1c18-11ea-9119-372282f2cae3-jxvcq

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  true

Phase:  Completed

Validation errors:  <none>

Warnings:  <none>
Errors:    <none>

Restic Restores:
  Failed:
    ocp-24659-mysql/mysql-1-8msj8-stage: mysql-data
```
**What did you expect to happen:**
I expected the Velero restore to fail.

**Output of podvolumerestore**
```
Restic Restores:
  Failed:
    ocp-24659-mysql/mysql-1-8msj8-stage: mysql-data
(failed reverse-i-search)`oc hg': ^C status
[dymurray@pups ~]$ oc get pods^C
(failed reverse-i-search)`podvolum': oc get ^Cds
[dymurray@pups ~]$ oc get podvolumerestores -o yaml 050d6c20-1c18-11ea-9119-372282f2cae3-9c4pb-v8qld 
apiVersion: velero.io/v1
kind: PodVolumeRestore
metadata:
  creationTimestamp: 2019-12-11T13:14:21Z
  generateName: 050d6c20-1c18-11ea-9119-372282f2cae3-9c4pb-
  generation: 3
  labels:
    velero.io/pod-uid: 241be6be-1c18-11ea-9b29-06135bb47b3a
    velero.io/restore-name: 050d6c20-1c18-11ea-9119-372282f2cae3-9c4pb
    velero.io/restore-uid: 239e691b-1c18-11ea-8bf6-0aae074dc220
  name: 050d6c20-1c18-11ea-9119-372282f2cae3-9c4pb-v8qld
  namespace: openshift-migration
  ownerReferences:
  - apiVersion: velero.io/v1
    controller: true
    kind: Restore
    name: 050d6c20-1c18-11ea-9119-372282f2cae3-9c4pb
    uid: 239e691b-1c18-11ea-8bf6-0aae074dc220
  resourceVersion: "663274"
  selfLink: /apis/velero.io/v1/namespaces/openshift-migration/podvolumerestores/050d6c20-1c18-11ea-9119-372282f2cae3-9c4pb-v8qld
  uid: 2549751e-1c18-11ea-9b29-06135bb47b3a
spec:
  backupStorageLocation: migstorage-default-b4g7n
  pod:
    kind: Pod
    name: mysql-1-8msj8-stage
    namespace: ocp-24659-mysql
    uid: 241be6be-1c18-11ea-9b29-06135bb47b3a
  repoIdentifier: s3:http://ae7b5152f1b6511ea97df06135bb47b3-1758046785.us-east-2.elb.amazonaws.com/mig-storage/velero/restic/ocp-24659-mysql
  snapshotID: 571a36a8
  volume: mysql-data
status:
  completionTimestamp: 2019-12-11T13:14:45Z
  message: 'error restoring volume: error creating .velero directory for done file:
    mkdir /host_pods/241be6be-1c18-11ea-9b29-06135bb47b3a/volumes/kubernetes.io~csi/pvc-2401a0d1-1c18-11ea-9b29-06135bb47b3a/mount/.velero:
    no space left on device'
  phase: Failed
  startTimestamp: 2019-12-11T13:14:42Z
```

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

closes #2121 

cc @dymurray

Basic validation on this looks good, but I'd like to do some more testing before merging so leaving in draft status.

### CODE REVIEW

**Comment by skriss** [comment]
looked good to me in testing, ready for review here.

File: pkg/restore/restore.go [hunk 1]
```diff
@@ -454,17 +456,27 @@ func (ctx *context) execute() (Result, Result) {
 		}
 	}
 
-	// TODO timeout?
-	ctx.log.Debug("Waiting on global wait group")
-	waitErrs := ctx.globalWaitGroup.Wait()
-	ctx.log.Debug("Done waiting on global wait group")
+	ctx.log.Info("Waiting for all restic restores to complete")
```
Comment (ashish-amarnath) [inline pkg/restore/restore.go]: suggest moving this log message into the `go func` that is doing the waiting.

Comment (skriss) [reply pkg/restore/restore.go]: done
