### PR TITLE
Fix restic backup volume snapshot to the second location failed

### LINKED ISSUE #2192: restic backup failed when backup locations HA + snapshot location
**What steps did you take and what happened:**

Deploy 2 external minio servers as 2 backup locations (HA: master and slave) and 1 snapshot location (master).

```
$ velero backup-location get
NAME      PROVIDER   BUCKET/PREFIX   ACCESS MODE
default   aws        velero          ReadWrite
slave     aws        velero          ReadWrite

$ velero snapshot-location get
NAME      PROVIDER
default   aws

$ velero backup create backup2default --storage-location default
$ velero backup create backup2slave --storage-location slave
```

During backup to the slave, the restic backup failed and the error message is
```
time="2020-01-07T03:46:01Z" level=error msg="Error backing up item" backup=kube-system/backup2slave error="pod volume backup failed: error running restic backup, stderr     =Fatal: invalid id \"90f30016\": no matching ID found\n: unable to find summary in restic backup command output" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/     restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=elasticsearch-master-0 namespace= resource=pods
```

**What did you expect to happen:**

The slave backup should succeed without failures.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
```
time="2020-01-14T08:12:10Z" level=info msg="Setting log-level to INFO"
time="2020-01-14T08:12:10Z" level=info msg="Starting Velero restic server v1.2.0 (5d008491bbf681658d3e372da1a9d3a21ca4c03c)" logSource="pkg/cmd/cli/restic/server.go:62"
time="2020-01-14T08:12:10Z" level=info msg="Starting controllers" logSource="pkg/cmd/cli/restic/server.go:156"
time="2020-01-14T08:12:10Z" level=info msg="Controllers started successfully" logSource="pkg/cmd/cli/restic/server.go:199"
time="2020-01-14T08:12:10Z" level=info msg="Starting controller" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:76"
time="2020-01-14T08:12:10Z" level=info msg="Waiting for caches to sync" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:79"
time="2020-01-14T08:12:10Z" level=info msg="Starting controller" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:76"
time="2020-01-14T08:12:10Z" level=info msg="Waiting for caches to sync" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:79"
time="2020-01-14T08:12:10Z" level=info msg="Caches are synced" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:83"
time="2020-01-14T08:12:10Z" level=info msg="Caches are synced" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:83"
time="2020-01-14T08:24:52Z" level=info msg="Backup starting" backup=kube-system/backup2default controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=backup2default-7p8vr namespace=kube-system
time="2020-01-14T08:24:52Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=kube-system/backup2default controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:301" name=backup2default-7p8vr namespace=kube-system pvcUID=233e035c-2cbe-4720-9248-9b77ed2cc278
time="2020-01-14T08:24:52Z" level=info msg="No completed pod volume backup found for PVC" backup=kube-system/backup2default controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:323" name=backup2default-7p8vr namespace=kube-system pvcUID=233e035c-2cbe-4720-9248-9b77ed2cc278
time="2020-01-14T08:24:52Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=kube-system/backup2default controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:247" name=backup2default-7p8vr namespace=kube-system
time="2020-01-14T08:24:54Z" level=info msg="Backup completed" backup=kube-system/backup2default controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:291" name=backup2default-7p8vr namespace=kube-system
time="2020-01-14T08:25:19Z" level=info msg="Backup starting" backup=kube-system/backup2slave controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=backup2slave-8bxx5 namespace=kube-system
time="2020-01-14T08:25:19Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=kube-system/backup2slave controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:301" name=backup2slave-8bxx5 namespace=kube-system pvcUID=233e035c-2cbe-4720-9248-9b77ed2cc278
time="2020-01-14T08:25:19Z" level=info msg="Found most recent completed pod volume backup for PVC" backup=kube-system/backup2slave controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:330" name=backup2slave-8bxx5 namespace=kube-system parentPodVolumeBackup=backup2default-7p8vr parentSnapshotID=bcf081e1 pvcUID=233e035c-2cbe-4720-9248-9b77ed2cc278
time="2020-01-14T08:25:19Z" level=info msg="Setting --parent flag for this backup" backup=kube-system/backup2slave controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:249" name=backup2slave-8bxx5 namespace=kube-system parentSnapshotID=bcf081e1
time="2020-01-14T08:25:19Z" level=error msg="Error running command=restic backup --repo=s3:http://10.86.1.172:9000/velero/restic/kube-system --password-file=/tmp/velero-restic-credentials-kube-system755988772 --cache-dir=/scratch/.cache/restic . --tag=pod=elasticsearch-master-2 --tag=pod-uid=70da4a2c-a470-473b-8962-8d904eb36bff --tag=pvc-uid=233e035c-2cbe-4720-9248-9b77ed2cc278 --tag=volume=elasticsearch-master --tag=backup=backup2slave --tag=backup-uid=bcaceae0-c485-42cb-a21a-6b5305027709 --tag=ns=kube-system --host=velero --json --parent=bcf081e1, stdout=, stderr=Fatal: invalid id \"bcf081e1\": no matching ID found\n" backup=kube-system/backup2slave controller=pod-volume-backup error="unable to find summary in restic backup command output" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/exec_commands.go:169" error.function=github.com/vmware-tanzu/velero/pkg/restic.getSummaryLine logSource="pkg/controller/pod_volume_backup_controller.go:261" name=backup2slave-8bxx5 namespace=kube-system
```

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
$ velero backup describe backup2slave
Name:         backup2slave
Namespace:    kube-system
Labels:       velero.io/storage-location=slave
Annotations:  <none>

Phase:  PartiallyFailed (run `velero backup logs backup2slave` for more information)

Errors:    3
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  slave

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-01-14 16:25:13 +0800 CST
Completed:  2020-01-14 16:25:27 +0800 CST

Expiration:  2020-02-13 16:25:13 +0800 CST

Persistent Volumes: <none included>

Restic Backups (specify --details for more information):
  Failed:  3
```

* `velero backup logs <backupname>`
```
$ velero backup logs backup2slave
time="2020-01-14T08:25:15Z" level=info msg="Backing up item" backup=kube-system/backup2slave group=v1 logSource="pkg/backup/item_backupper.go:169" name=pvc-15632487-c2c5-4bbb-8167-e5a710031ca9 namespace= resource=persistentvolumes
time="2020-01-14T08:25:15Z" level=info msg="Executing takePVSnapshot" backup=kube-system/backup2slave group=v1 logSource="pkg/backup/item_backupper.go:395" name=pvc-15632487-c2c5-4bbb-8167-e5a710031ca9 namespace= resource=persistentvolumes
time="2020-01-14T08:25:15Z" level=info msg="Skipping snapshot of persistent volume because volume is being backed up with restic." backup=kube-system/backup2slave group=v1 logSource="pkg/backup/item_backupper.go:413" name=pvc-15632487-c2c5-4bbb-8167-e5a710031ca9 namespace= persistentVolume=pvc-15632487-c2c5-4bbb-8167-e5a710031ca9 resource=persistentvolumes
time="2020-01-14T08:25:17Z" level=info msg="1 errors encountered backup up item" backup=kube-system/backup2slave group=v1 logSource="pkg/backup/resource_backupper.go:284" name=elasticsearch-master-0 namespace= resource=pods
time="2020-01-14T08:25:17Z" level=error msg="Error backing up item" backup=kube-system/backup2slave error="pod volume backup failed: error running restic backup, stderr=Fatal: invalid id \"6c7380c4\": no matching ID found\n: unable to find summary in restic backup command output" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=elasticsearch-master-0 namespace= resource=pods
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This scenario works on AWS. I created 2 S3 buckets (HA: master and slave) and 1 snapshot location.
I could successfully backup backups to 2 s3 buckets separately and 2 volume snapshots would generate in the same AWS region.

**Environment:**

- Velero version (use `velero version`): `1.2.0`
- Velero features (use `velero client config get features`): `<NOT SET>`
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-28T12:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Kubernetes installer & version:
  K8s `1.16.2`
- Cloud provider or hardware configuration:
  On-Premise Openstack
- OS (e.g. from `/etc/os-release`):
  ```
  NAME="SLES"
  VERSION="15-SP1"
  VERSION_ID="15.1"
  PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
  ID="sles"
  ID_LIKE="suse"
  ANSI_COLOR="0;32"
  CPE_NAME="cpe:/o:suse:sles:15:sp1"
  ```

### LINKED ISSUE #2241: Unable to backup persistentvolumeclaims to multiple storage locations
**What steps did you take and what happened:**
An annotated persistent volume claim mount volume fails to backup to a secondary storage location after successfully backing up to a primary storage location.  The same backup job to the primary storage location can be performed again successfully.

$ kubectl -n <NAMESPACE> annotate po <POD> backup.velero.io/backup-volumes=<PVC-MOUNT-VOLUME>
$ velero backup create backup-job-1 --include-namespace <NAMESPACE> --storage-location s3-bucket-1 (success)
$ velero backup create backup-job-2 --include-namespace <NAMESPACE> --storage-location s3-bucket-2 (PartiallyFailed (1 error))
$ velero backup describe backup create backup-job-2 --details | grep persistentvolumeclaims
time="2020-02-04T13:50:47Z" level=info msg="Skipping item because it's already been backup." backup=velero/backup-job-2 group=v1 logSource="pkg/backup/item_backupper.go:163" name=<NAME> namespace=<NAMESPACE> resource=persistentvolumeclaims

**What did you expect to happen:**
Backup persistentvolumeclaim to a second storage location after backing up to primary storage location.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version: v1.2.0
- Velero features: <NOT SET>
- Kubernetes Client version: v1.15.3
- Kubernetes Server version: v1.14.6
- Cloud provider or hardware configuration: aws
- OS: Ubuntu 18.04.3 LTS

### PR DESCRIPTION
**Pull request by jenting**
fix #2192
fix #2241 
related PR #1807

## Description
Backup files _should_ supports HA scenario. Schedule create backups to different object storage location with volume snapshot by resic.

## Root Cause
The current restic pass `--parent` flag to restic to support incremental backup.
When backup to the second storage location, it find the first storage location's parent snapshot ID and this cause restic backup volume failed since restic cannot find this parent snapshot ID.

## Solution
Add the backup location check when finding restic parent snapshot ID in PodVolumeBackup CRD.

Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>

### CODE REVIEW

**Comment by skriss** [comment]
@jenting thanks for this - at first glance it looks reasonable to me! I'll review later on, but could you remove `go.mod`, `go.sum`, and `credentials-velero` from this PR? Thanks!

**Comment by jenting** [comment]
> @jenting thanks for this - at first glance it looks reasonable to me! I'll review later on, but could you remove `go.mod`, `go.sum`, and `credentials-velero` from this PR? Thanks!

Sorry, enter too fast with `git add .`, updated!

File: pkg/controller/pod_volume_backup_controller.go [hunk 1]
```diff
@@ -320,7 +320,12 @@ func getParentSnapshot(log logrus.FieldLogger, pvcUID string, podVolumeBackupLis
 			continue
 		}
 
-		if mostRecentBackup == nil || backup.Status.StartTimestamp.After(mostRecentBackup.Status.StartTimestamp.Time) {
+		if (mostRecentBackup == nil || backup.Status.StartTimestamp.After(mostRecentBackup.Status.StartTimestamp.Time)) &&
+			// Check the backup storage location is the same as spec in order to support backup to multiple backup-locations.
+			// Otherwise, there exist a case that backup volume snapshot to the second location would failed, since the founded
+			// parent ID is valid for the first backup location, not the second backup location.
+			// Also, the second backup should not use first backup parent ID since eachthe parent ID is for the first backup location only.
+			(backupStorageLocation == backup.Spec.BackupStorageLocation) {
```
Comment (skriss) [inline pkg/controller/pod_volume_backup_controller.go]: I'd prefer to move this new check into its own guard condition just above L323, so basically:

```go
if backup.Spec.BackupStorageLocation != backupStorageLocation {
    continue
}
```

This should make it a little easier to read.

It would also be nice to add a unit test here, but I'm not going to block merge on it given that we don't already have one in place to easily add new case to.

Comment (jenting) [reply pkg/controller/pod_volume_backup_controller.go]: Update for easier to read.

**Comment by skriss** [comment]
@jenting this LGTM, though I would have preferred to keep the comment that you had in the first commit around! If you can add it back, that'd be great. I'll approve it now regardless.

**Comment by skriss** [comment]
@carlisia @nrb @ashish-amarnath PTAL!

**Comment by jenting** [comment]
> thanks for adding the comment back!

Done!

**Comment by skriss** [comment]
I'd be fine getting this in for 1.3, especially since we may end up releasing another beta anyway. So fine merging if other reviewers LGTM.

**Comment by a4nowgh** [comment]
Deployed velero binary v1.3.0-beta.2 and still backups result in Partially Fails where the MountVol associated with the Persistent Volume fails.

Tested backing up the same K8S cluster with a Persistent Volume:
(Step 1) velero backup create <jobName>  (successfully backs up to Server A/S3 bucket)
(Step 2) velero backup create <jobName> --storage-location minio (Restic fails backing up annotated MountVol associated with a Persistent Volume to Server B/S3 bucket)

My originally issue submitted:
https://github.com/vmware-tanzu/velero/issues/2241

Should I have to do anything special to make this work??

**Comment by skriss** [comment]
@a4nowgh perhaps we misdiagnosed your issue. Let's take this discussion back to #2241 - could you paste the error that you're getting on Step 2 verbatim in there?

**Comment by a4nowgh** [comment]
Just a note, we are using this product in a closed network.
---------------------------------------------------------------------------kubectl -n velero describe deployments velero
Name: veleroNamespace: velero....Containers: velero:  Image: velero/velero:v1.3.0-beta.2...
---------------------------------------------------------------------------
velero backup logs <2ndjobName> | grep -i error
time=<DATESTAMP>" level=info msg="1 errors encountered backup item" backup=velero/<2ndjobName> group=v1 logSource="pkg/backup/resource_backupper.go:283" name=<NAME> namespace=<NAMESPACE> resource=podstime=<DATESTAMP>" level=errormsg="Errorsbacking up item" backup=velero/<2ndjobName> error="pod volume backup failed: error running restic backup, stderr=Fatal: invalid id \"7b027ec9\": no matching ID found\n: unable to find summary in restic backup command output" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:287" name=<NAME> namespace=<NAMESPACE>

---------------------------------------------------------------------------
velero backup describe <2ndjobName> --details
Name:  <2ndjobName>Namespace: velero....Failed:  <NAMESPACE>/<PERSISTENT_VOLUME_CLAIM_REFERENCE>: <MOUNTVOL>

---------------------------------------------------------------------------

    On Tuesday, February 25, 2020, 3:34:17 PM EST, Steve Kriss <notifications@github.com> wrote:  
 
 
@a4nowgh perhaps we misdiagnosed your issue. Let's take this discussion back to #2241 - could you paste the error that you're getting on Step 2 verbatim in there?
