### PR TITLE
Check the PVB status via podvolume Backupper rather than calling API server to avoid API server issue

### LINKED ISSUE #8587: failed to wait PVBs - 1.15.1 - Backup
**What steps did you take and what happened:**
Any creation of backup Manually or with Schedule.

Errors:
  Velero:    message: /failed to wait PVBs processed for the ItemBlock error: /failed to list PVBs: the server was unable to return a response in the time allotted, but may still be processing the request (get podvolumebackups.velero.io)

**What did you expect to happen:**
a Completed status and not PartiallyFailed.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.15.1
        Git commit: 32499fc287815058802c1bc46ef620799cca7392
Server:
        Version: v1.15.1
```
- Velero features (use `velero client config get features`): 
`features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
```
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.1
```
- Cloud provider or hardware configuration:
OVH Managed Kubernetes, Bucket S3 OVH and Scaleway

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by ywk253100**
Check the PVB status via podvolume Backupper rather than calling API server to avoid API server issue

Fixes #8587

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by Lyndon-Li — DISMISSED** [review]

**Review by blackpiglet — DISMISSED** [review]

File: pkg/backup/backup.go [hunk 1]
```diff
@@ -742,36 +741,23 @@ func (kb *kubernetesBackupper) handleItemBlockPostHooks(ctx context.Context, ite
...
-		if pvb.Status.Phase == velerov1api.PodVolumeBackupPhaseCompleted ||
-			pvb.Status.Phase == velerov1api.PodVolumeBackupPhaseFailed {
-			processed = true
+		for _, pvb := range pvbs {
+			processed := false
+			if pvb.Status.Phase == velerov1api.PodVolumeBackupPhaseCompleted ||
+				pvb.Status.Phase == velerov1api.PodVolumeBackupPhaseFailed {
+				processed = true
+			}
+			pvbMap[pvb] = processed
```
Comment (reasonerjt) [inline pkg/backup/backup.go:759]: trivial, but the variable `processed` is not needed:
```
pvbMap[pvb] = pvb.Status.Phase == velerov1api.PodVolumeBackupPhaseCompleted ||
				pvb.Status.Phase == velerov1api.PodVolumeBackupPhaseFailed
```

File: pkg/podvolume/backupper.go [hunk 2]
```diff
@@ -312,6 +336,12 @@ func (b *backupper) BackupPodVolumes(backup *velerov1api.Backup, pod *corev1api.
 			continue
 		}
 		b.wg.Add(1)
+
+		if err := b.pvbIndexer.Add(volumeBackup); err != nil {
+			errs = append(errs, errors.Wrapf(err, "failed to create PodVolumeBackup for pvc %s", pvc.Spec.VolumeName))
```
Comment (reasonerjt) [inline pkg/podvolume/backupper.go:341]: is it the write error message?

Shouldn't it be `failed to create indexer for pvb` and with the pvb information.  It seems there will be an error only when the input param is not a valid k8s object

File: pkg/podvolume/backupper.go [hunk 3]
```diff
@@ -337,7 +367,8 @@ func (b *backupper) WaitAllPodVolumesProcessed(log logrus.FieldLogger) []*velero
 	case <-b.ctx.Done():
 		log.Error("timed out waiting for all PodVolumeBackups to complete")
 	case <-done:
-		for _, pvb := range b.result {
+		for _, obj := range b.pvbIndexer.List() {
+			pvb := obj.(*velerov1api.PodVolumeBackup)
```
Comment (reasonerjt) [inline pkg/podvolume/backupper.go:371]: Is there a risk for panic?  Maybe we should be a little more defensive to log an error and continue?

File: pkg/podvolume/backupper.go [hunk 4]
```diff
@@ -347,6 +378,29 @@ func (b *backupper) WaitAllPodVolumesProcessed(log logrus.FieldLogger) []*velero
...
 
+func (b *backupper) GetPodVolumeBackup(namespace, name string) (*velerov1api.PodVolumeBackup, error) {
+	obj, exist, err := b.pvbIndexer.GetByKey(cache.NewObjectName(namespace, name).String())
+	if err != nil {
+		return nil, err
+	}
+	if !exist {
+		return nil, nil
+	}
+	return obj.(*velerov1api.PodVolumeBackup), nil
```
Comment (reasonerjt) [inline pkg/podvolume/backupper.go:389]: risk for panic?

File: pkg/podvolume/backupper.go [hunk 5]
```diff
@@ -347,6 +378,29 @@ func (b *backupper) WaitAllPodVolumesProcessed(log logrus.FieldLogger) []*velero
...
+}
+
+func (b *backupper) ListPodVolumeBackupsByPod(podNamespace, podName string) ([]*velerov1api.PodVolumeBackup, error) {
+	objs, err := b.pvbIndexer.ByIndex(indexNamePod, cache.NewObjectName(podNamespace, podName).String())
+	if err != nil {
+		return nil, err
+	}
+	var pvbs []*velerov1api.PodVolumeBackup
+	for _, obj := range objs {
+		pvbs = append(pvbs, obj.(*velerov1api.PodVolumeBackup))
```
Comment (reasonerjt) [inline pkg/podvolume/backupper.go:399]: risk for panic?

**Review by blackpiglet — APPROVED** [review]

**Review by Lyndon-Li — APPROVED** [review]
