### PR TITLE
[fix] Add regional PV support for GKE

### LINKED ISSUE #4663: velero-plugin-for-gcp v1.4.0 regional storage class: Error attempting to get volume ID for persistent volume
I am getting following error while backup up the regional storage pvc on velero-plugin-for-gcp v1.4.0 where as its working fine in v1.2.0

Error attempting to get volume ID for persistent volume" backup=velero/backup-4 error="rpc error: code = Unknown desc = invalid volumeHandle for CSI driver:pd.csi.storage.gke.io, expected projects/{project}/zones/{zone}/disks/{name}, got projects/sw-gcp/regions/us-west1/disks/pvc-3a5edee8-6e5b-4d3c-8c97-529efc5e101c" logSource="pkg/backup/item_backupper.go:449" name=pvc-3a5edee8-6e5b-4d3c-8c97-529efc5e101c namespace= persistentVolume=pvc-3a5edee8-6e5b-4d3c-8c97-529efc5e101c resource=persistentvolumes volumeSnapshotLocation=default

How ever its taking pvc snapshots.

kubectl describe sc standard-rwo-dup
Name:                  standard-rwo
IsDefaultClass:        Yes
Annotations:           storageclass.kubernetes.io/is-default-class=true
Provisioner:           pd.csi.storage.gke.io
Parameters:            replication-type=regional-pd,type=pd-balanced
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Retain
VolumeBindingMode:     WaitForFirstConsumer
AllowedTopologies:
  Term 0:              topology.gke.io/zone in [us-west1-b, us-west1-a]
Events:                <none>

### PR DESCRIPTION
**Pull request by blackpiglet**
fix #4663.
For GKE pv, when create backup, return all zones retrived from node affinity.

Signed-off-by: Xun Jiang <jxun@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/backup/item_backupper_test.go [hunk 1]
```diff
@@ -131,6 +131,21 @@ func Test_zoneFromPVNodeAffinity(t *testing.T) {
 			wantKey:   "topology.disk.csi.azure.com/zone",
 			wantValue: "us-central",
 		},
+		{
+			name: "Volume with multiple valid keys, and provider is gke, returns the all match", // it should never happen
```
Comment (reasonerjt) [inline pkg/backup/item_backupper_test.go:135]: The comment is misleading, instead you should provide the concrete use case when testing the regional disk?

File: pkg/backup/item_backupper.go [hunk 2]
```diff
@@ -384,6 +385,7 @@ const (
 	awsEbsCsiZoneKey = "topology.ebs.csi.aws.com/zone"
 	azureCsiZoneKey  = "topology.disk.csi.azure.com/zone"
 	gkeCsiZoneKey    = "topology.gke.io/zone"
+	zoneSeparator    = "__"
```
Comment (reasonerjt) [inline pkg/backup/item_backupper.go:388]: is the zone separator for gcp only or all cloud providers?

Comment (blackpiglet) [reply pkg/backup/item_backupper.go:388]: GKE only. I will update

**Review by reasonerjt — APPROVED** [review]

**Review by ywk253100 — APPROVED** [review]
