### PR TITLE
Check for empty ns list before checking nslist[0]

### LINKED ISSUE #5235: If namespace includes/excludes evaluates to an empty list, velero server panics on backup
**What steps did you take and what happened:**
Create a backup where the particular combination of namespaces includes/excludes results in an empty list. The result was a velero srever panic:
```
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/remote-source/velero/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x22b7ec0, 0xc000ce15a8)
	/usr/lib/golang/src/runtime/panic.go:965 +0x1b9
github.com/vmware-tanzu/velero/pkg/backup.(*itemCollector).getResourceItems(0xc00098ced8, 0x27ec470, 0xc0001b3960, 0x0, 0x0, 0xc000a939a8, 0x2, 0xc000fcc420, 0xa, 0x0, ...)
	/remote-source/src/github.com/vmware-tanzu/velero/pkg/backup/item_collector.go:227 +0x30f6
github.com/vmware-tanzu/velero/pkg/backup.(*itemCollector).getGroupItems(0xc00098ced8, 0x27ec470, 0xc0001d4af0, 0xc001094780, 0xc00098c8f0, 0x48a2bb, 0x8, 0x102, 0xffffffffffffff9c)
	/remote-source/src/github.com/vmware-tanzu/velero/pkg/backup/item_collector.go:96 +0x278
github.com/vmware-tanzu/velero/pkg/backup.(*itemCollector).getAllItems(0xc00098ced8, 0x4, 0x0, 0x0)
	/remote-source/src/github.com/vmware-tanzu/velero/pkg/backup/item_collector.go:65 +0xde
github.com/vmware-tanzu/velero/pkg/backup.(*kubernetesBackupper).Backup(0xc0001a9500, 0x27ec470, 0xc0001d4af0, 0xc0004a6000, 0x2777d60, 0xc000407150, 0xc000f34b00, 0xb, 0xb, 0x7f087207cc40, ...)
	/remote-source/src/github.com/vmware-tanzu/velero/pkg/backup/backup.go:281 +0xb4c
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).runBackup(0xc0001fa6c0, 0xc0004a6000, 0x0, 0x0)
	/remote-source/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:590 +0x975
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).processBackup(0xc0001fa6c0, 0xc000398230, 0x42, 0x0, 0x0)
	/remote-source/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:274 +0x78a
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).processNextWorkItem(0xc0009f4840, 0x203000)
	/remote-source/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:132 +0xf7
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).runWorker(...)
	/remote-source/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:119
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0007bffa0)
	/remote-source/velero/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00098dfa0, 0x2776f80, 0xc00015c720, 0xc000981d01, 0xc000cc5bc0)
	/remote-source/velero/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007bffa0, 0x3b9aca00, 0x0, 0x442701, 0xc000cc5bc0)
	/remote-source/velero/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/remote-source/velero/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:90
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run.func2(0xc0009f4840, 0x27bf398, 0xc000981d80, 0xc0008c66d0)
	/remote-source/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:92 +0x85
created by github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run
	/remote-source/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:91 +0x1f7
```
(line numbers won't match up to current code, as this was initially observed on Velero 1.7.1, but I just reproduced it on 1.9.1.
Here's the example that I reproduced it, snippet from Velero backup CR spec:
```
spec:
  excludedNamespaces:
  - mysql-*
  includedNamespaces:
  - mysql-persistent
```
Starting with a single namespace "mysql-persistent", removing "mysql-*" results in an empty list. Code in item_collector references emptyList[0] which crashes Velero.

**What did you expect to happen:**

Backup to succeed with no namespaced resources included
**The following information will help us better understand what's going on**:

**Anything else you would like to add:**
Fix PR forthcoming

**Environment:**

- Velero version (use `velero version`): 1.9.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.23
- Kubernetes installer & version:
- Cloud provider or hardware configuration: OpenShift 4.10 on AWS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by sseago**
In determining whether a backup includes all namespaces, item_collector
checks for an empty string in the first element of the ns list. If processing
includes+excludes results in an empty list, treat this as another case
of a not-all-namespaces backup rather than crashing velero.

Signed-off-by: Scott Seago <sseago@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change
In determining whether a backup includes all namespaces, item_collector
checks for an empty string in the first element of the ns list. If processing
includes+excludes results in an empty list, treat this as another case
of a not-all-namespaces backup rather than crashing velero.

# Does your change fix a particular issue?

Fixes #5235

# Please indicate you've done the following:

- [x ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/backup/item_collector.go [hunk 1]
```diff
@@ -226,7 +226,7 @@ func (r *itemCollector) getResourceItems(log logrus.FieldLogger, gv schema.Group
 	namespacesToList := getNamespacesToList(r.backupRequest.NamespaceIncludesExcludes)
 
 	// Check if we're backing up namespaces, and only certain ones
-	if gr == kuberesource.Namespaces && namespacesToList[0] != "" {
+	if gr == kuberesource.Namespaces && (len(namespacesToList) == 0 || namespacesToList[0] != "") {
```
Comment (reasonerjt) [inline pkg/backup/item_collector.go:229]: Would it be more explicit if it's like `gr == kuberesource.Namespaces && len(namespacesToList) > 0 &&  namespacesToList[0] != ""` ?

Comment (sseago) [reply pkg/backup/item_collector.go:229]: @reasonerjt No, that would introduce incorrect logic. This block should be executed when the resource is "Namespaces" *and* "we're not backing up the whole cluster". a slice value of `[""]` is what we're looking for to skip. This means "All namespaces", so we skip the block. If it's an empty slice, this means that the includes minus the excludes leaves us with zero namespaces, meaning this is a less-than-whole-cluster backup, so we run the block. If it's non-empty with values other than `""`, this is also a less-than-whole-cluster backup and we run the block -- that's why I have the embedded or clause. The alternative suggestion would have us skipping the block and going on where there are no namespaces, which could result in stuff being done that we don't want done here.

Comment (reasonerjt) [reply pkg/backup/item_collector.go:229]: Could you please update the comment in line 228, to explain the case when the first item is an empty string， the phrase `only certain ones` makes people think the the block after if should not be executed if the `namespaceToList` is empty.

Comment (sseago) [reply pkg/backup/item_collector.go:232]: @reasonerjt done

**Review by reasonerjt — APPROVED** [review]

**Review by qiuming-best — APPROVED** [review]
