### PR TITLE
Fix statefulsets volumeClaimTemplates storageClassName after use Changing PV/PVC Storage Classes

### LINKED ISSUE #4373: volumeClaimTemplates storageClassName in statefulsets incorrect after use Changing PV/PVC Storage Classes .
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
when i used Changing PV/PVC Storage Classes function during restore，volumeClaimTemplates storageClassName in statefulsets not change. I get the volumeClaimTemplates storageClassName in the restored sts after restore completed,
i find It's still the old storageClassName.

**What did you expect to happen:**
when use Changing PV/PVC Storage Classes function, volumeClaimTemplates storageClassName in statefulsets  should also be changed to use the new storageClassName .

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
kubectl get sts -n my-example web -oyaml ---> 
`  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: a-storage
      volumeMode: Filesystem`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (v1.7.0): 
- Velero features (<NOT SET>): 
- Kubernetes version (v1.20.9):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by Box-Cube**
Signed-off-by: Box-Cube <64300761+Box-Cube@users.noreply.github.com>

Thank you for contributing to Velero!

# Please add a summary of your change
Change STS volumeClaimTemplates storageClassName to the new storageClass when using Changing PV/PVC Storage Classes function.

# Does your change fix a particular issue?

Fixes #4373

# Please indicate you've done the following:

- [ ] Added handling StatefulSets volumeClaimTemplates storageClassName updated with the new storageClass
- [ ] Added unit tests for change_storageclass_action_test.go

### CODE REVIEW

**Comment by reasonerjt** [comment]
The change should be made in the plugin `ChangeStorageClassAction`

**Review by reasonerjt — CHANGES_REQUESTED** [review]
The change should be made in the plugin `ChangeStorageClassAction`, not in the restore flow

**Comment by Box-Cube** [comment]
> The change should be made in the plugin `ChangeStorageClassAction`, not in the restore flow

But ChangeStorageClassAction execute for the kind PersistentVolumeClaim object,  It seems unlikely that the StatefulSet storageclassName can be changed in ChangeStorageClassAction.

**Comment by ywk253100** [comment]
> > The change should be made in the plugin `ChangeStorageClassAction`, not in the restore flow
> 
> But ChangeStorageClassAction execute for the kind PersistentVolumeClaim object, It seems unlikely that the StatefulSet storageclassName can be changed in ChangeStorageClassAction.

We can extend the `ChangeStorageClassAction` to handle `StatefulSet` as well

File: pkg/restore/change_storageclass_action.go [hunk 1]
```diff
@@ -87,32 +89,55 @@ func (a *ChangeStorageClassAction) Execute(input *velero.RestoreItemActionExecut
...
-	if _, err := a.storageClassClient.Get(context.TODO(), newStorageClass, metav1.GetOptions{}); err != nil {
-		return nil, errors.Wrapf(err, "error getting storage class %s from API", newStorageClass)
-	}
-
-	log.Infof("Updating item's storage class name to %s", newStorageClass)
-
-	if err := unstructured.SetNestedField(obj.UnstructuredContent(), newStorageClass, "spec", "storageClassName"); err != nil {
-		return nil, errors.Wrap(err, "unable to set item's spec.storageClassName")
+	// change sts volumeClaimTemplates storageClassName
+	if obj.GetKind() == "StatefulSet" {
```
Comment (ywk253100) [inline pkg/restore/change_storageclass_action.go:93]: Could you add unit tests for this new code path?

File: pkg/restore/change_storageclass_action.go [hunk 2]
```diff
@@ -87,33 +91,73 @@ func (a *ChangeStorageClassAction) Execute(input *velero.RestoreItemActionExecut
...
+
+		if err := unstructured.SetNestedField(obj.UnstructuredContent(), newStorageClass, "spec", "storageClassName"); err != nil {
+			return nil, errors.Wrap(err, "unable to set item's spec.storageClassName")
+		}
 	}
+
+	return velero.NewRestoreItemActionExecuteOutput(obj), nil
+}
+
+func (a *ChangeStorageClassAction) isStorageClassExist(storageClass string, cm *corev1.ConfigMap) (warn string, err error, newStorageClass string) {
```
Comment (ywk253100) [inline pkg/restore/change_storageclass_action.go:147]: I'm a little confused about the function. Usually, if a function called `isXXXExist`, it returns a boolean value to indicate whether the resource exists or not.
Seems the returning `warn` here is only used to print some debug logs, how about logging the debug message inside the function directly and change the return values of the function to `(exists bool, newStorageClass string, err error)`?
If the function returns an error during the calling, returns the error directly. If an error is nil and exists is false, do continue, otherwise do the actual work

Comment (Box-Cube) [reply pkg/restore/change_storageclass_action.go:147]: Because I want `logSource` field to be on an optimal path when I need to print debug logs.
Your suggestion is a better way to deal with it, I will change the `isStorageClassExist` function.

Comment (Box-Cube) [reply pkg/restore/change_storageclass_action.go:147]: Because I want `logSource` field to be on an optimal path when I need to print debug logs.
Your suggestion is a better way to deal with it, I will change the `isStorageClassExist` function.

**Review by ywk253100 — APPROVED** [review]
Thanks a lot!

**Comment by ywk253100** [comment]
@Box-Cube Could you please take a look at the CI checking failure?

**Comment by Box-Cube** [comment]
> 



> @Box-Cube Could you please take a look at the CI checking failure?

**Comment by Box-Cube** [comment]
> @Box-Cube Could you please take a look at the CI checking failure?

The previous commit did not follow the community import format，now has been modified.

**Review by sseago — APPROVED** [review]

**Review by ywk253100 — APPROVED** [review]
