### PR TITLE
Check for nil before logging DefaultVolumesToRestic value

### LINKED ISSUE #4617: Info log in backup package causes nil pointer dereference panic due to backupRequest.Backup.Spec.DefaultVolumesToRestic not being set
**What steps did you take and what happened:**

It has been reported that while doing a backup, sometimes a panic occurs due to nil dereference while logging at the info level. The panic causes the Velero pod to crash and restart.

Here is the error:

```bash
time="2022-02-02T11:43:21Z" level=info msg="Including namespaces: agreement-foundation" backup=velero/agreement-foundation-v2 logSource="pkg/backup/backup.go:218"
time="2022-02-02T11:43:21Z" level=info msg="Excluding namespaces: <none>" backup=velero/agreement-foundation-v2 logSource="pkg/backup/backup.go:219"
time="2022-02-02T11:43:21Z" level=info msg="Including resources: *" backup=velero/agreement-foundation-v2 logSource="pkg/backup/backup.go:222"
time="2022-02-02T11:43:21Z" level=info msg="Excluding resources: <none>" backup=velero/agreement-foundation-v2 logSource="pkg/backup/backup.go:223"
E0202 11:43:21.118242       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 732 [running]:

k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d66c20, 0x30e4420)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.12/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.12/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1d66c20, 0x30e4420)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/vmware-tanzu/velero/pkg/backup.(*kubernetesBackupper).Backup(0xc000269920, 0x2371ce0, 0xc0003d88c0, 0xc0004e8280, 0x22f9be0, 0xc0003565e8, 0xc000b6ab00, 0x4, 0x4, 0x7f0240fde848, ...)
        /go/src/github.com/vmware-tanzu/velero/pkg/backup/backup.go:224 +0x71e
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).runBackup(0xc000c790e0, 0xc0004e8280, 0x0, 0x0)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:590 +0x959
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).processBackup(0xc000c790e0, 0xc0007062c0, 0x1e, 0x0, 0x0)
```

The problem was reported for Velero 1.6.0. However, I see the same code that can cause the error in the main branch (latest release was v1.7.1). 

**What did you expect to happen:**

Backup should complete successfully without panics and pod crashes.

**The following information will help us better understand what's going on**:

Although it was reported, I have not been able to reproduce the problem and **have no logs**. However, there is certainly a flaw in the code logic that needs to be fixed.

**Anything else you would like to add:**

Here is the [section of code](https://github.com/vmware-tanzu/velero/blob/v1.6.0/pkg/backup/backup.go#L224) that panics:

```go
log.Infof("Backing up all pod volumes using restic: %t", *backupRequest.Backup.Spec.DefaultVolumesToRestic)
```

I believe the solution that can provide the most information in the logs is

```go
if backupRequest.Backup.Spec.DefaultVolumesToRestic != nil {
    log.Infof("Backing up all pod volumes using Restic: %t", *backupRequest.Backup.Spec.DefaultVolumesToRestic)
} else {
    log.Infof("DefaultVolumesToRestic for backing up all pod volumes using Restic is %v", backupRequest.Backup.Spec.DefaultVolumesToRestic)
}
```

**Environment:**

- Velero version (use `velero version`): 1.6.0 - 1.7.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by codegold79**
Signed-off-by: F. Gold <fgold@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

Check for nil value for `backupRequest.Backup.Spec.DefaultVolumesToRestic` (a pointer to a boolean) before dereferencing. Although I could not reproduce the problem, panics have been reported to have happened due to attempting to do an info log with the pointer value.

# Does your change fix a particular issue?

Fixes #4617

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: pkg/backup/backup.go [hunk 1]
```diff
@@ -200,7 +200,11 @@ func (kb *kubernetesBackupper) BackupWithResolvers(log logrus.FieldLogger,
 	backupRequest.ResourceIncludesExcludes = collections.GetResourceIncludesExcludes(kb.discoveryHelper, backupRequest.Spec.IncludedResources, backupRequest.Spec.ExcludedResources)
 	log.Infof("Including resources: %s", backupRequest.ResourceIncludesExcludes.IncludesString())
 	log.Infof("Excluding resources: %s", backupRequest.ResourceIncludesExcludes.ExcludesString())
-	log.Infof("Backing up all pod volumes using restic: %t", *backupRequest.Backup.Spec.DefaultVolumesToRestic)
+	if backupRequest.Backup.Spec.DefaultVolumesToRestic != nil {
```
Comment (ywk253100) [inline pkg/backup/backup.go:203]: There is [a utility function](https://github.com/vmware-tanzu/velero/blob/main/pkg/util/boolptr/boolptr.go#L20) that we can use to determine the value of a boolean pointer.

Comment (codegold79) [reply pkg/backup/backup.go:203]: Would you prefer the following over what I have? 

```go
if boolptr.IsSetToTrue(backupRequest.Backup.Spec.DefaultVolumesToRestic) || boolptr.IsSetToFalse(backupRequest.Backup.Spec.DefaultVolumesToRestic) {
    log.Infof("Backing up all pod volumes using Restic: %t", *backupRequest.Backup.Spec.DefaultVolumesToRestic)
} else {
    log.Infof("DefaultVolumesToRestic for backing up all pod volumes using Restic is %v", backupRequest.Backup.Spec.DefaultVolumesToRestic)
}
```

Another alternative is add a Print() function to the utility function. Something like,
```go
package boolptr
...
// Print prints the value of the bool pointer.
func Print(b *bool) string {
    if b == nil {
        return "<nil>"
    } else {
        return fmt.Sprint("%t", *b)
    }
}
```

I'm liking adding another utility function, Print. What do you think @ywk253100?

Comment (ywk253100) [reply pkg/backup/backup.go:203]: The `nil` value of `backupRequest.Backup.Spec.DefaultVolumesToRestic` can be regarded as `false`. I saw some other similar usages for the function, e.g. https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/item_backupper.go#L145

Comment (codegold79) [reply pkg/backup/backup.go]: I didn't want to assume `nil` was the same as `false`, but I think you're right--here it can be treated as false.

If `nil` is always treated the same as `false`, I don't think a boolean pointer is needed; we could just use a boolean variable. But I think that is outside the scope of the reported issue.

I have made the change to use the boolptr utility function and removed the if/else blocks. Now, only a single line is used for logging.

**Review by ywk253100 — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]
