### PR TITLE
bug fix: fix int/float conversion issue with CRD type in restore plugin

### LINKED ISSUE #2319: Error: unable to convert unstructured item to a v1 CRD: cannot convert int64 to float64
**What steps did you take and what happened:**

Run a full backup of cluster using Restic

**What did you expect to happen:**

No fail during backup

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
```
Found 2 pods, using pod/restic-sgkfd
time="2020-03-04T17:44:27Z" level=info msg="Setting log-level to INFO"
time="2020-03-04T17:44:27Z" level=info msg="Starting Velero restic server v1.3.0 (8fec8ed7fb8b4776b191753497eafeb47f2f9136)" logSource="pkg/cmd/cli/restic/server.go:62"
time="2020-03-04T17:44:28Z" level=info msg="Starting controllers" logSource="pkg/cmd/cli/restic/server.go:156"
time="2020-03-04T17:44:28Z" level=info msg="Controllers started successfully" logSource="pkg/cmd/cli/restic/server.go:199"
time="2020-03-04T17:44:28Z" level=info msg="Starting controller" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:76"
time="2020-03-04T17:44:28Z" level=info msg="Waiting for caches to sync" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:79"
time="2020-03-04T17:44:28Z" level=info msg="Starting controller" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:76"
time="2020-03-04T17:44:28Z" level=info msg="Waiting for caches to sync" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:79"
time="2020-03-04T17:44:28Z" level=info msg="Caches are synced" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:83"
time="2020-03-04T17:44:28Z" level=info msg="Caches are synced" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:83"
time="2020-03-04T17:45:04Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-f6rzx namespace=velero
time="2020-03-04T17:45:05Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-f6rzx namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-04T17:45:05Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-f6rzx namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-04T17:45:05Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-f6rzx namespace=velero
time="2020-03-04T17:45:12Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-f6rzx namespace=velero
time="2020-03-05T11:04:12Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-gc2nt namespace=velero
time="2020-03-05T11:04:16Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-gc2nt namespace=velero
time="2020-03-05T11:04:16Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-d5272 namespace=velero
time="2020-03-05T11:04:16Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-d5272 namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:04:16Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-d5272 namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:04:16Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-d5272 namespace=velero
time="2020-03-05T11:04:20Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-d5272 namespace=velero
time="2020-03-05T11:04:20Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-ct92z namespace=velero
time="2020-03-05T11:04:20Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-ct92z namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:04:20Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-ct92z namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:04:20Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-ct92z namespace=velero
time="2020-03-05T11:04:36Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-ct92z namespace=velero
time="2020-03-05T11:04:37Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-5swgr namespace=velero
time="2020-03-05T11:04:37Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-5swgr namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:04:37Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-5swgr namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:04:37Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-5swgr namespace=velero
time="2020-03-05T11:04:40Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-5swgr namespace=velero
time="2020-03-05T11:14:52Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-544n5 namespace=velero
time="2020-03-05T11:14:52Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-544n5 namespace=velero pvcUID=ca3ef62f-3ecf-4527-a565-32e779cd5920
time="2020-03-05T11:14:52Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-544n5 namespace=velero pvcUID=ca3ef62f-3ecf-4527-a565-32e779cd5920
time="2020-03-05T11:14:52Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-544n5 namespace=velero
time="2020-03-05T11:17:12Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-544n5 namespace=velero
time="2020-03-05T11:17:12Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-c9c5p namespace=velero
time="2020-03-05T11:17:12Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-c9c5p namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:17:12Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-c9c5p namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:17:12Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-c9c5p namespace=velero
time="2020-03-05T11:17:16Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-c9c5p namespace=velero
time="2020-03-05T11:17:16Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-psrrr namespace=velero
time="2020-03-05T11:17:16Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-psrrr namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:17:16Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-psrrr namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:17:16Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-psrrr namespace=velero
time="2020-03-05T11:17:25Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-psrrr namespace=velero
time="2020-03-05T11:17:25Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-zwdt8 namespace=velero
time="2020-03-05T11:17:25Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-zwdt8 namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:17:25Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-zwdt8 namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:17:25Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-zwdt8 namespace=velero
time="2020-03-05T11:17:28Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-zwdt8 namespace=velero
time="2020-03-05T11:27:23Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-nn7h8 namespace=velero
time="2020-03-05T11:27:23Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-nn7h8 namespace=velero pvcUID=ca3ef62f-3ecf-4527-a565-32e779cd5920
time="2020-03-05T11:27:23Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-nn7h8 namespace=velero pvcUID=ca3ef62f-3ecf-4527-a565-32e779cd5920
time="2020-03-05T11:27:23Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-nn7h8 namespace=velero
time="2020-03-05T11:28:20Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-nn7h8 namespace=velero
time="2020-03-05T11:28:21Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-p7nn7 namespace=velero
time="2020-03-05T11:28:21Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-p7nn7 namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:28:21Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-p7nn7 namespace=velero pvcUID=34c79b4b-3f7f-41e4-97a4-636945cf9815
time="2020-03-05T11:28:21Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-p7nn7 namespace=velero
time="2020-03-05T11:28:25Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-p7nn7 namespace=velero
time="2020-03-05T11:28:25Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-sb8bh namespace=velero
time="2020-03-05T11:28:25Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-sb8bh namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:28:25Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-sb8bh namespace=velero pvcUID=369483b4-92d3-41a6-9bb5-50b03d05eaf7
time="2020-03-05T11:28:25Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-sb8bh namespace=velero
time="2020-03-05T11:28:38Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-sb8bh namespace=velero
time="2020-03-05T11:28:38Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-5llwt namespace=velero
time="2020-03-05T11:28:38Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-5llwt namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:28:38Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-5llwt namespace=velero pvcUID=627f2cdc-df81-4d4d-b3a8-6dea4501dbb9
time="2020-03-05T11:28:38Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-5llwt namespace=velero
time="2020-03-05T11:28:42Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-5llwt namespace=velero
time="2020-03-05T11:28:45Z" level=info msg="Backup starting" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:178" name=test-backup-926tt namespace=velero
time="2020-03-05T11:28:45Z" level=info msg="Looking for most recent completed pod volume backup for this PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:307" name=test-backup-926tt namespace=velero pvcUID=5e733400-e696-4f2a-85f4-4ee1458bb664
time="2020-03-05T11:28:45Z" level=info msg="No completed pod volume backup found for PVC" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:337" name=test-backup-926tt namespace=velero pvcUID=5e733400-e696-4f2a-85f4-4ee1458bb664
time="2020-03-05T11:28:45Z" level=info msg="No parent snapshot found for PVC, not using --parent flag for this backup" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:253" name=test-backup-926tt namespace=velero
time="2020-03-05T11:30:48Z" level=info msg="Backup completed" backup=velero/test-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:297" name=test-backup-926tt namespace=velero
```

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

```
Name:         test-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  PartiallyFailed (run `velero backup logs test-backup` for more information)

Errors:    1
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-03-05 12:27:08 +0100 CET
Completed:  2020-03-05 12:30:54 +0100 CET

Expiration:  2020-04-04 13:27:08 +0200 CEST

Persistent Volumes: <none included>

Restic Backups (specify --details for more information):
  Completed:  5
```

* `velero backup logs <backupname>`

```
[...]
resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=resticrepositories.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=resticrepositories.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=restores.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=restores.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=schedules.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=schedules.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=serverstatusrequests.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=serverstatusrequests.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=volumesnapshotclasses.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=volumesnapshotclasses.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="1 errors encountered backup up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:283" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions
time="2020-03-05T11:30:53Z" level=error msg="Error backing up item" backup=velero/test-backup error="error executing custom action (groupResource=customresourcedefinitions.apiextensions.k8s.io, namespace=, name=volumesnapshotcontents.snapshot.storage.k8s.io): rpc error: code = Unknown desc = unable to convert unstructured item to a v1 CRD: cannot convert int64 to float64" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:334" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*defaultItemBackupper).executeActions" group=apiextensions.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:287" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=volumesnapshotlocations.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=volumesnapshotlocations.velero.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=volumesnapshots.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing custom action" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/item_backupper.go:330" name=volumesnapshots.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions.apiextensions.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-backup cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:50" pluginName=velero
time="2020-03-05T11:30:53Z" level=info msg="Backing up group" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/group_backupper.go:101"
time="2020-03-05T11:30:53Z" level=info msg="Backing up resource" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:105" resource=priorityclasses
time="2020-03-05T11:30:53Z" level=info msg="Listing items" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:226" namespace= resource=priorityclasses
time="2020-03-05T11:30:53Z" level=info msg="Retrieved 2 items" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:240" namespace= resource=priorityclasses
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=system-cluster-critical namespace= resource=priorityclasses.scheduling.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Backing up item" backup=velero/test-backup group=scheduling.k8s.io/v1 logSource="pkg/backup/item_backupper.go:169" name=system-node-critical namespace= resource=priorityclasses.scheduling.k8s.io
time="2020-03-05T11:30:53Z" level=info msg="Backing up group" backup=velero/test-backup group=coordination.k8s.io/v1 logSource="pkg/backup/group_backupper.go:101"
time="2020-03-05T11:30:53Z" level=info msg="Backing up resource" backup=velero/test-backup group=coordination.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:105" resource=leases
time="2020-03-05T11:30:53Z" level=info msg="Listing items" backup=velero/test-backup group=coordination.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:226" namespace= resource=leases
time="2020-03-05T11:30:53Z" level=info msg="Retrieved 5 items" backup=velero/test-backup group=coordination.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:240" namespace= resource=leases
[...]
```

* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**

```
time="2020-03-05T11:30:53Z" level=info msg="1 errors encountered backup up item" backup=velero/test-backup group=apiextensions.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:283" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions
time="2020-03-05T11:30:53Z" level=error msg="Error backing up item" backup=velero/test-backup error="error executing custom action (groupResource=customresourcedefinitions.apiextensions.k8s.io, namespace=, name=volumesnapshotcontents.snapshot.storage.k8s.io): rpc error: code = Unknown desc = unable to convert unstructured item to a v1 CRD: cannot convert int64 to float64" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:334" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*defaultItemBackupper).executeActions" group=apiextensions.k8s.io/v1 logSource="pkg/backup/resource_backupper.go:287" name=volumesnapshotcontents.snapshot.storage.k8s.io namespace= resource=customresourcedefinitions
```

**Environment:**

- Velero version (use `velero version`): v1.3.0
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Scaleway
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

closes #2319 

The unit test failed before the fix, and passes afterwards, but I haven't done manual testing beyond that. I'll use the reported CRDs with issues in a running cluster to verify, and I'll potentially add the `v1` representations of them as test cases to the unit test as well.

### CODE REVIEW

**Comment by skriss** [comment]
OK, was able to repro the bug with one of the provided CRDs, and then verify that it restored correctly with this fix.

Given that the reported CRD has the exact same field (an integer Maximum) as the simpler CRD that's currently constructed in the unit test, I don't really see a need to add the real CRD as a test, but let me know if you think otherwise.

File: pkg/restore/crd_v1_preserve_unknown_fields_action.go [hunk 1]
```diff
@@ -101,3 +106,18 @@ func (c *CRDV1PreserveUnknownFieldsAction) Execute(input *velero.RestoreItemActi
 		UpdatedItem: &unstructured.Unstructured{Object: res},
 	}, nil
 }
+
+func fromUnstructured(unstructured map[string]interface{}) (*apiextv1.CustomResourceDefinition, error) {
```
Comment (nrb) [inline pkg/restore/crd_v1_preserve_unknown_fields_action.go:110]: Would it make sense to put this function in a shared location, since the JSON marshaling is also done on the back up side?

Comment (skriss) [reply pkg/restore/crd_v1_preserve_unknown_fields_action.go:110]: I can do that if you prefer; I considered it but didn't bother since it's such a small function. If you want me to do that, any particular package you have in mind? `pkg/util/kube` is really the only one that comes to mind.

**Comment by skriss** [comment]
> The comments are very helpful, thank you!

Thank @nrb, those are copied from existing code :)

File: pkg/restore/crd_v1_preserve_unknown_fields_action.go (hunk 1 above)
Comment (nrb) [reply pkg/restore/crd_v1_preserve_unknown_fields_action.go:110]: I don't think it's a blocker for this PR - I could move it in mine, too.

I also agree that it would probably end up in that package.
