### PR TITLE
Mark in-progress CRs as failed when starting the server

### LINKED ISSUE #4953: The Backup/Restore/PVB/PBR may be marked as failed by mistake during the backup/restore
We introduced a logic in PR https://github.com/vmware-tanzu/velero/pull/4833 and https://github.com/vmware-tanzu/velero/pull/4893 that the backup/restore/PVB/PVR controllers will try to mark the CRs as failed if any of them is in progress when the controllers pick up the CRs.

We thought the in-progress CRs only appear when the Velero server restarts, so we mark these CRs as failed to avoid hanging issues, but it isn't in some corner cases and the in-progress CRs may appear during the normal running of Velero server and the controllers will mark them as failed by mistake. 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by ywk253100**
Mark in-progress CRs as failed when starting the server

Fixes #4953

Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by sseago — APPROVED** [review]

File: pkg/cmd/cli/restic/server.go [hunk 1]
```diff
@@ -259,3 +270,83 @@ func (s *resticServer) validatePodVolumesHostPath(client kubernetes.Interface) e
 
 	return nil
 }
+
+// if there is a restarting during the reconciling of pvbs/pvrs/etc, these CRs may be stuck in progress status
+// markInProgressCRsFailed tries to mark the in progress CRs as failed when starting the server to avoid the issue
+func (s *resticServer) markInProgressCRsFailed() {
```
Comment (blackpiglet) [inline pkg/cmd/cli/restic/server.go:276]: Better to use different function name for this function in pkg/cmd/cli/restic/server.go and pkg/cmd/server/server.go

**Review by blackpiglet — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]
