### PR TITLE
Reduces ~140 indirect imports for plugin/framework importers

### LINKED ISSUE #8157: New dependencies relates to aws and azure sdk on Velero 1.14
**What steps did you take and what happened:**

Trying to use "install.VeleroOptions" to generate the velero option struct, then passing this as a parameter to the "install.Install" function. I was trying use the "install.Install" function to install Velero 1.14 on kubernetes cluster. 
https://github.com/vmware-tanzu/velero/blob/main/pkg/install/install.go

On the Velero 1.12, this method works for installing velero. But on Velero 1.14, it involves in lots of new dependency of "`github.com/aws/aws-sdk-go-v2`" and "`github.com/Azure/azure-sdk-for-go/sdk`". And the building does not work. Since we don't have this dependency on our repository yet.
https://github.com/vmware-tanzu/velero/blob/main/go.mod#L13

**What did you expect to happen:**
The Velero 1.14 server should install successfully using this package. 

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

Here is the reason I found. The install package has dependency with these sdk.
`go mod why github.com/aws/aws-sdk-go-v2/credentials`
   `github.com/aws/aws-sdk-go-v2/credentials`
   `github.com/vmware-tanzu/velero/pkg/install`
   `github.com/vmware-tanzu/velero/pkg/repository`
   `github.com/vmware-tanzu/velero/pkg/repository/provider`
   `github.com/vmware-tanzu/velero/pkg/repository/config`
   `github.com/aws/aws-sdk-go-v2/credentials`

I knew in this release, Velero 1.14 including new features relates to aws and azure sdk. But on our dev side, I don't want to add too many new dependencies relates to these sdk for now. Any way to fix it or temporarily workaround? Thanks.

**Environment:**

- Velero version (use `velero version`): v1.14.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): Kubernetes v1.27.0
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): SUSE Linux Enterprise Server 15 SP4

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### LINKED ISSUE #8207: pkg/plugin/framework imported by external plugins should not result in cloud provider indirect dependencies.
**What steps did you take and what happened:**

Follow up to #8157 which removes `pkg/install` dependency on velero plugin framework package.
plugin framework should not have many unrelated dependencies.

This would help a ton with avoiding CVEs impacting plugins unnecessarily.

current list. Perhaps anything prefixed with k8s.io/client-go is acceptable.

Due to server.go import of `"github.com/vmware-tanzu/velero/pkg/cmd/server/config"`
Due to github.com/vmware-tanzu/velero/pkg/cmd/server/config/config.go import of `pkg/podvolume`
Due to pkg/volume/ `❯ find ./pkg/podvolume | xargs -I {} sh -c "echo && echo && echo {} && go list -f {{.Deps}} {} | sed 's/ /\n/g' | grep -E 'aws|azure|gcp|s3'"`
- restorer.go
- backupper.go
- util.go
- restorer_factory.go
- backupper_factory.go
- mocks/restorer.go

due to their imports of
- "github.com/vmware-tanzu/velero/pkg/repository"

due to pkg/repository/manager.go `❯ find pkg/repository -maxdepth 1 | xargs -I {} sh -c "echo && echo && echo {} && go list -f {{.Deps}} {} | sed 's/ /\n/g' | grep -E 'aws|azure|gcp|s3'"`

due to manager.go import of
- pkg/repository/udmrepo/kopialib/ due to lib_repo.go && repo_init.go importing "github.com/kopia/kopia/*"
- pkg/repository/restic due to repository.go importing pkg/restic/common.go importing `"github.com/vmware-tanzu/velero/pkg/repository/config"` which have aws.go, azure.go etc...

```
~/git/velero unit-test-dependency-installpkg
❯ go list -f {{.Deps}} ./pkg/plugin/framework/server.go | sed 's/ /\n/g' | grep -E 'aws|azure|gcp|s3'
github.com/Azure/azure-sdk-for-go/sdk/azcore
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/internal/resource
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/policy
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/runtime
github.com/Azure/azure-sdk-for-go/sdk/azcore/cloud
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/log
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/async
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/body
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/fake
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/loc
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/op
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared
github.com/Azure/azure-sdk-for-go/sdk/azcore/log
github.com/Azure/azure-sdk-for-go/sdk/azcore/policy
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime
github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming
github.com/Azure/azure-sdk-for-go/sdk/azcore/to
github.com/Azure/azure-sdk-for-go/sdk/azcore/tracing
github.com/Azure/azure-sdk-for-go/sdk/azidentity
github.com/Azure/azure-sdk-for-go/sdk/azidentity/internal
github.com/Azure/azure-sdk-for-go/sdk/internal/diag
github.com/Azure/azure-sdk-for-go/sdk/internal/errorinfo
github.com/Azure/azure-sdk-for-go/sdk/internal/exported
github.com/Azure/azure-sdk-for-go/sdk/internal/log
github.com/Azure/azure-sdk-for-go/sdk/internal/poller
github.com/Azure/azure-sdk-for-go/sdk/internal/temporal
github.com/Azure/azure-sdk-for-go/sdk/internal/uuid
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/appendblob
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/bloberror
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/container
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/base
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/exported
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/generated
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/pageblob
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/sas
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/service
github.com/aws/aws-sdk-go-v2/aws
github.com/aws/aws-sdk-go-v2/aws/arn
github.com/aws/aws-sdk-go-v2/aws/defaults
github.com/aws/aws-sdk-go-v2/aws/middleware
github.com/aws/aws-sdk-go-v2/aws/middleware/private/metrics
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream/eventstreamapi
github.com/aws/aws-sdk-go-v2/aws/protocol/query
github.com/aws/aws-sdk-go-v2/aws/protocol/restjson
github.com/aws/aws-sdk-go-v2/aws/protocol/xml
github.com/aws/aws-sdk-go-v2/aws/ratelimit
github.com/aws/aws-sdk-go-v2/aws/retry
github.com/aws/aws-sdk-go-v2/aws/signer/internal/v4
github.com/aws/aws-sdk-go-v2/aws/signer/v4
github.com/aws/aws-sdk-go-v2/aws/transport/http
github.com/aws/aws-sdk-go-v2/config
github.com/aws/aws-sdk-go-v2/credentials
github.com/aws/aws-sdk-go-v2/credentials/ec2rolecreds
github.com/aws/aws-sdk-go-v2/credentials/endpointcreds
github.com/aws/aws-sdk-go-v2/credentials/endpointcreds/internal/client
github.com/aws/aws-sdk-go-v2/credentials/processcreds
github.com/aws/aws-sdk-go-v2/credentials/ssocreds
github.com/aws/aws-sdk-go-v2/credentials/stscreds
github.com/aws/aws-sdk-go-v2/feature/ec2/imds
github.com/aws/aws-sdk-go-v2/feature/ec2/imds/internal/config
github.com/aws/aws-sdk-go-v2/feature/s3/manager
github.com/aws/aws-sdk-go-v2/internal/auth
github.com/aws/aws-sdk-go-v2/internal/auth/smithy
github.com/aws/aws-sdk-go-v2/internal/awsutil
github.com/aws/aws-sdk-go-v2/internal/configsources
github.com/aws/aws-sdk-go-v2/internal/context
github.com/aws/aws-sdk-go-v2/internal/endpoints
github.com/aws/aws-sdk-go-v2/internal/endpoints/awsrulesfn
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2
github.com/aws/aws-sdk-go-v2/internal/ini
github.com/aws/aws-sdk-go-v2/internal/rand
github.com/aws/aws-sdk-go-v2/internal/sdk
github.com/aws/aws-sdk-go-v2/internal/sdkio
github.com/aws/aws-sdk-go-v2/internal/shareddefaults
github.com/aws/aws-sdk-go-v2/internal/strings
github.com/aws/aws-sdk-go-v2/internal/sync/singleflight
github.com/aws/aws-sdk-go-v2/internal/timeconv
github.com/aws/aws-sdk-go-v2/internal/v4a
github.com/aws/aws-sdk-go-v2/internal/v4a/internal/crypto
github.com/aws/aws-sdk-go-v2/internal/v4a/internal/v4
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding
github.com/aws/aws-sdk-go-v2/service/internal/checksum
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url
github.com/aws/aws-sdk-go-v2/service/internal/s3shared
github.com/aws/aws-sdk-go-v2/service/internal/s3shared/arn
github.com/aws/aws-sdk-go-v2/service/internal/s3shared/config
github.com/aws/aws-sdk-go-v2/service/s3
github.com/aws/aws-sdk-go-v2/service/s3/internal/arn
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations
github.com/aws/aws-sdk-go-v2/service/s3/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/s3/types
github.com/aws/aws-sdk-go-v2/service/sso
github.com/aws/aws-sdk-go-v2/service/sso/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/sso/types
github.com/aws/aws-sdk-go-v2/service/ssooidc
github.com/aws/aws-sdk-go-v2/service/ssooidc/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/ssooidc/types
github.com/aws/aws-sdk-go-v2/service/sts
github.com/aws/aws-sdk-go-v2/service/sts/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/sts/types
github.com/aws/smithy-go
github.com/aws/smithy-go/auth
github.com/aws/smithy-go/auth/bearer
github.com/aws/smithy-go/container/private/cache
github.com/aws/smithy-go/container/private/cache/lru
github.com/aws/smithy-go/context
github.com/aws/smithy-go/document
github.com/aws/smithy-go/encoding
github.com/aws/smithy-go/encoding/httpbinding
github.com/aws/smithy-go/encoding/json
github.com/aws/smithy-go/encoding/xml
github.com/aws/smithy-go/endpoints
github.com/aws/smithy-go/endpoints/private/rulesfn
github.com/aws/smithy-go/internal/sync/singleflight
github.com/aws/smithy-go/io
github.com/aws/smithy-go/logging
github.com/aws/smithy-go/middleware
github.com/aws/smithy-go/private/requestcompression
github.com/aws/smithy-go/ptr
github.com/aws/smithy-go/rand
github.com/aws/smithy-go/sync
github.com/aws/smithy-go/time
github.com/aws/smithy-go/transport/http
github.com/aws/smithy-go/transport/http/internal/io
github.com/aws/smithy-go/waiter
github.com/kopia/kopia/repo/blob/azure
github.com/kopia/kopia/repo/blob/s3
github.com/minio/minio-go/v7/pkg/s3utils
github.com/vmware-tanzu/velero/pkg/repository/udmrepo/kopialib/backend/azure
github.com/vmware-tanzu/velero/pkg/util/azure
google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp
k8s.io/client-go/plugin/pkg/client/auth/azure
k8s.io/client-go/plugin/pkg/client/auth/gcp
```

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by kaovilai**
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change
Refactor struct imports to avoid framework importers from needing cloud provider imports.
Moving repository/manager.go to repository/manager/manager.go

This would help a ton with avoiding CVEs false alarms for unrelated plugin.

This change can supplement or replace https://github.com/vmware-tanzu/velero/pull/8180
# Does your change fix a particular issue?

Fixes #8207
Fixes #8157

Problem Demo: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/252/commits/7e31b61f9c7d009331d16c023887a41be377b4dd
Fix Demo: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/252/commits/64ea9027b7f2c4bd2ab95096811b0c21a9c25d75
Problem Demo2: https://github.com/kubevirt/kubevirt-velero-plugin/pull/284/commits/faf981584e8532b0ef9d2a73ec7679d7c77ad4fa
Fix Demo2: https://github.com/kubevirt/kubevirt-velero-plugin/pull/284/commits/2c0e171d44b446d9153abe9202caa27ebf0861fc
<details><summary>Before</summary>
<p>

```
❯ git fetch upstream && git checkout upstream/main && go list -f {{.Deps}} ./pkg/install/... | sed 's/ /\n/g' | grep -E 'aws|azure|gcp|s3'  
HEAD is now at 7c9b7c1ba Merge pull request #8144 from Lyndon-Li/data-mover-ms-doc
github.com/Azure/azure-sdk-for-go/sdk/azcore
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/internal/resource
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/policy
github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/runtime
github.com/Azure/azure-sdk-for-go/sdk/azcore/cloud
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/log
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/async
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/body
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/fake
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/loc
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/pollers/op
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared
github.com/Azure/azure-sdk-for-go/sdk/azcore/log
github.com/Azure/azure-sdk-for-go/sdk/azcore/policy
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime
github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming
github.com/Azure/azure-sdk-for-go/sdk/azcore/to
github.com/Azure/azure-sdk-for-go/sdk/azcore/tracing
github.com/Azure/azure-sdk-for-go/sdk/azidentity
github.com/Azure/azure-sdk-for-go/sdk/azidentity/internal
github.com/Azure/azure-sdk-for-go/sdk/internal/diag
github.com/Azure/azure-sdk-for-go/sdk/internal/errorinfo
github.com/Azure/azure-sdk-for-go/sdk/internal/exported
github.com/Azure/azure-sdk-for-go/sdk/internal/log
github.com/Azure/azure-sdk-for-go/sdk/internal/poller
github.com/Azure/azure-sdk-for-go/sdk/internal/temporal
github.com/Azure/azure-sdk-for-go/sdk/internal/uuid
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/appendblob
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/bloberror
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/container
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/base
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/exported
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/generated
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/pageblob
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/sas
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/service
github.com/aws/aws-sdk-go-v2/aws
github.com/aws/aws-sdk-go-v2/aws/arn
github.com/aws/aws-sdk-go-v2/aws/defaults
github.com/aws/aws-sdk-go-v2/aws/middleware
github.com/aws/aws-sdk-go-v2/aws/middleware/private/metrics
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream/eventstreamapi
github.com/aws/aws-sdk-go-v2/aws/protocol/query
github.com/aws/aws-sdk-go-v2/aws/protocol/restjson
github.com/aws/aws-sdk-go-v2/aws/protocol/xml
github.com/aws/aws-sdk-go-v2/aws/ratelimit
github.com/aws/aws-sdk-go-v2/aws/retry
github.com/aws/aws-sdk-go-v2/aws/signer/internal/v4
github.com/aws/aws-sdk-go-v2/aws/signer/v4
github.com/aws/aws-sdk-go-v2/aws/transport/http
github.com/aws/aws-sdk-go-v2/config
github.com/aws/aws-sdk-go-v2/credentials
github.com/aws/aws-sdk-go-v2/credentials/ec2rolecreds
github.com/aws/aws-sdk-go-v2/credentials/endpointcreds
github.com/aws/aws-sdk-go-v2/credentials/endpointcreds/internal/client
github.com/aws/aws-sdk-go-v2/credentials/processcreds
github.com/aws/aws-sdk-go-v2/credentials/ssocreds
github.com/aws/aws-sdk-go-v2/credentials/stscreds
github.com/aws/aws-sdk-go-v2/feature/ec2/imds
github.com/aws/aws-sdk-go-v2/feature/ec2/imds/internal/config
github.com/aws/aws-sdk-go-v2/feature/s3/manager
github.com/aws/aws-sdk-go-v2/internal/auth
github.com/aws/aws-sdk-go-v2/internal/auth/smithy
github.com/aws/aws-sdk-go-v2/internal/awsutil
github.com/aws/aws-sdk-go-v2/internal/configsources
github.com/aws/aws-sdk-go-v2/internal/context
github.com/aws/aws-sdk-go-v2/internal/endpoints
github.com/aws/aws-sdk-go-v2/internal/endpoints/awsrulesfn
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2
github.com/aws/aws-sdk-go-v2/internal/ini
github.com/aws/aws-sdk-go-v2/internal/rand
github.com/aws/aws-sdk-go-v2/internal/sdk
github.com/aws/aws-sdk-go-v2/internal/sdkio
github.com/aws/aws-sdk-go-v2/internal/shareddefaults
github.com/aws/aws-sdk-go-v2/internal/strings
github.com/aws/aws-sdk-go-v2/internal/sync/singleflight
github.com/aws/aws-sdk-go-v2/internal/timeconv
github.com/aws/aws-sdk-go-v2/internal/v4a
github.com/aws/aws-sdk-go-v2/internal/v4a/internal/crypto
github.com/aws/aws-sdk-go-v2/internal/v4a/internal/v4
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding
github.com/aws/aws-sdk-go-v2/service/internal/checksum
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url
github.com/aws/aws-sdk-go-v2/service/internal/s3shared
github.com/aws/aws-sdk-go-v2/service/internal/s3shared/arn
github.com/aws/aws-sdk-go-v2/service/internal/s3shared/config
github.com/aws/aws-sdk-go-v2/service/s3
github.com/aws/aws-sdk-go-v2/service/s3/internal/arn
github.com/aws/aws-sdk-go-v2/service/s3/internal/customizations
github.com/aws/aws-sdk-go-v2/service/s3/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/s3/types
github.com/aws/aws-sdk-go-v2/service/sso
github.com/aws/aws-sdk-go-v2/service/sso/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/sso/types
github.com/aws/aws-sdk-go-v2/service/ssooidc
github.com/aws/aws-sdk-go-v2/service/ssooidc/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/ssooidc/types
github.com/aws/aws-sdk-go-v2/service/sts
github.com/aws/aws-sdk-go-v2/service/sts/internal/endpoints
github.com/aws/aws-sdk-go-v2/service/sts/types
github.com/aws/smithy-go
github.com/aws/smithy-go/auth
github.com/aws/smithy-go/auth/bearer
github.com/aws/smithy-go/container/private/cache
github.com/aws/smithy-go/container/private/cache/lru
github.com/aws/smithy-go/context
github.com/aws/smithy-go/document
github.com/aws/smithy-go/encoding
github.com/aws/smithy-go/encoding/httpbinding
github.com/aws/smithy-go/encoding/json
github.com/aws/smithy-go/encoding/xml
github.com/aws/smithy-go/endpoints
github.com/aws/smithy-go/endpoints/private/rulesfn
github.com/aws/smithy-go/internal/sync/singleflight
github.com/aws/smithy-go/io
github.com/aws/smithy-go/logging
github.com/aws/smithy-go/middleware
github.com/aws/smithy-go/private/requestcompression
github.com/aws/smithy-go/ptr
github.com/aws/smithy-go/rand
github.com/aws/smithy-go/sync
github.com/aws/smithy-go/time
github.com/aws/smithy-go/transport/http
github.com/aws/smithy-go/transport/http/internal/io
github.com/aws/smithy-go/waiter
github.com/kopia/kopia/repo/blob/azure
github.com/kopia/kopia/repo/blob/s3
github.com/minio/minio-go/v7/pkg/s3utils
github.com/vmware-tanzu/velero/pkg/repository/udmrepo/kopialib/backend/azure
github.com/vmware-tanzu/velero/pkg/util/azure
google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp
k8s.io/client-go/plugin/pkg/client/auth/azure
k8s.io/client-go/plugin/pkg/client/auth/gcp
```
</p>
</details> 

**After**
```
❯ go list -f {{.Deps}} ./pkg/install/... | sed 's/ /\n/g' | grep -E 'aws|azure|gcp|s3'  

k8s.io/client-go/plugin/pkg/client/auth/azure
k8s.io/client-go/plugin/pkg/client/auth/gcp
```

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

Related: https://github.com/vmware-tanzu/velero/pull/6484

### CODE REVIEW

**Review by ywk253100 — APPROVED** [review]

File: pkg/repository/manager/manager.go [hunk 1]
```diff
@@ -32,42 +32,14 @@ import (
...
 	"github.com/vmware-tanzu/velero/pkg/repository/provider"
 	"github.com/vmware-tanzu/velero/pkg/util/filesystem"
 	"github.com/vmware-tanzu/velero/pkg/util/kube"
 	"github.com/vmware-tanzu/velero/pkg/util/logging"
 	veleroutil "github.com/vmware-tanzu/velero/pkg/util/velero"
 )
 
-// SnapshotIdentifier uniquely identifies a snapshot
-// taken by Velero.
-type SnapshotIdentifier struct {
```
Comment (Lyndon-Li) [inline pkg/repository/manager/manager.go:44]: If we only move `SnapshotIdentifier` to `types` folder, but keep `manager.go` as is in the `repository` folder, does that work?
The current changes look good to me, just curious why `manager.go` is moved as well.

Comment (kaovilai) [reply pkg/repository/manager/manager.go:44]: Per #8207

manager.go also import following which ultimately add cloud provider dependencies.

> due to manager.go import of
>
>pkg/repository/udmrepo/kopialib/ due to lib_repo.go && repo_init.go importing "github.com/kopia/kopia/*"
>pkg/repository/restic due to repository.go importing pkg/restic/common.go importing "github.com/vmware-tanzu/velero/pkg/repository/config" which have aws.go, azure.go etc...

Comment (kaovilai) [reply pkg/repository/manager/manager.go:44]: I'll double check again

Comment (kaovilai) [reply pkg/repository/manager/manager.go:44]: Moving only snapshotidentifier still result in dep in framework package.
pkg/plugin/framework/server.go depends on 
"github.com/vmware-tanzu/velero/pkg/cmd/server/config" where config.go depend on
"github.com/vmware-tanzu/velero/pkg/podvolume" which have files that import 
"github.com/vmware-tanzu/velero/pkg/repository" where manager.go imports
"github.com/vmware-tanzu/velero/pkg/repository/provider" which has imports to cloud deps via pkg/repository/provider/restic.go and pkg/repository/provider/unified_repo.go

So manager.go has to also move.. or refactor unified_repo.go & restic.go

**Review by sseago — DISMISSED** [review]

File: pkg/repository/manager/manager.go (hunk 1 above)
Comment (kaovilai) [reply pkg/repository/manager/manager.go:44]: https://github.com/kaovilai/velero/tree/snapshotIdentifierOnly in case you wanna check. and run

```
❯ find ./pkg/plugin/framework/ -maxdepth 1 -type f | grep .go | xargs -I {} sh -c "echo && echo && echo {} && go list -f {{.Deps}} {} | sed 's/ /\n/g' | grep -E 'aws|azure|gcp|s3'"
```
while making changes. The only change there is only moving snapshotIdentifier. The deps issue isn't resolved.

**Review by sseago — APPROVED** [review]

File: pkg/repository/manager/manager.go (hunk 1 above)
Comment (Lyndon-Li) [reply pkg/repository/manager/manager.go:44]: First of all, I agree on moving manager.go to a dedicate package.
Secondly, I will see it is not enough if the dependency chain is like this:
```
pkg/plugin/framework/server.go depends on
"github.com/vmware-tanzu/velero/pkg/cmd/server/config" where config.go depend on
"github.com/vmware-tanzu/velero/pkg/podvolume" which have files that import
```

`server/config` is a package to expose configs, but `podvolume` is a package to hold PVB/PVR code where uploader and repository packages must be imported there. So it is not rational to import such a heavy package just because of a config.
And as you can see why `podvolume` is required by `server/config`, it just because it requires definition of `podvolume.DefaultVolumesToFsBackup`.
Therefore, I think we need to remove the dependency of this:
```
"github.com/vmware-tanzu/velero/pkg/cmd/server/config" where config.go depend on
"github.com/vmware-tanzu/velero/pkg/podvolume" which have files that import
```

Comment (kaovilai) [reply pkg/repository/manager/manager.go:44]: ok sounds good.

Comment (kaovilai) [reply pkg/repository/manager/manager.go:44]: will see/try remove github.com/vmware-tanzu/velero/pkg/podvolume from `github.com/vmware-tanzu/velero/pkg/cmd/server/config`

Comment (kaovilai) [reply pkg/repository/manager/manager.go:44]: done. moved the default var to its own package `github.com/vmware-tanzu/velero/pkg/podvolume/defaults`
```
❯ find ./pkg/cmd/server/config -maxdepth 1 -type f | grep .go | xargs -I {} sh -c "echo && echo && echo {} && go list -f {{.Deps}} {} | sed 's/ /\n/g' | grep -E 'github.com/vmware-tanzu/velero/pkg/podvolume'" 


./pkg/cmd/server/config/config.go
github.com/vmware-tanzu/velero/pkg/podvolume/defaults
```

File: pkg/podvolume/defaults/defaults.go [hunk 2]
```diff
@@ -0,0 +1,5 @@
+package defaults
```
Comment (Lyndon-Li) [inline pkg/podvolume/defaults/defaults.go:1]: This package name looks too narrow to hold other codes, can we just add pkg/podvolume/configs/configs.go and put `PVCNameAnnotation` and `DefaultVolumesToFsBackup` to it?

Comment (kaovilai) [reply pkg/podvolume/defaults/defaults.go:1]: Sure thing

**Review by Lyndon-Li — DISMISSED** [review]

**Comment by kaovilai** [comment]
rebasing against https://github.com/vmware-tanzu/velero/pull/8201

**Review by sseago — APPROVED** [review]

**Review by ywk253100 — APPROVED** [review]
