### PR TITLE
Roll back pkg client code for Velero server

### LINKED ISSUE #5896: Kubecontext flag missing from versions >1.9.5
**What steps did you take and what happened:**

We upgraded velero from v1.9.5 to 1.10.1 and existing processes using the `--kubecontext` flag began failing

```
unknown flag: --kubecontext
```

**What did you expect to happen:**

The flag to exist still.

Looks like it may have been removed inadvertently by https://github.com/vmware-tanzu/velero/pull/5124 specifically this commented out line: https://github.com/vmware-tanzu/velero/pull/5124/files#diff-ba8260b29909b6c7324036b886b8ed4b021d782bd3f8e94e160b5a2a872e6762R100

### PR DESCRIPTION
**Pull request by danfengliu**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #5896

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by blackpiglet — APPROVED** [review]

File: test/e2e/pkg/client/auth_providers.go [hunk 1]
```diff
@@ -0,0 +1,25 @@
+/*
```
Comment (Lyndon-Li) [inline test/e2e/pkg/client/auth_providers.go:1]: I see quite some files from pkg/client are copied from production to E2E test. Do we need to copy all of them in case some files are not changed in E2E at all?
Alternatively, we can copy the files that need to be changed for E2E, and still refer to the shared ones in the production?

Comment (Lyndon-Li) [reply test/e2e/pkg/client/auth_providers.go:1]: Discussed with @danfengliu, there are two unchanged files only, we will keep monitoring it, if more sharing files are required, we come back to change it together.

**Review by Lyndon-Li — APPROVED** [review]
