### PR TITLE
Use hookIndex for recording multiple restore exec hooks.

### LINKED ISSUE #9359: platform: arm64 velero version:1.17.0. restore status always block at Finalizing
**What steps did you take and what happened:**

restore with pv and hooks .  retore always block at Finalizing

**What did you expect to happen:**
restore success

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

here is logs of "kubectl logs deployment/velero -n velero "

```
"pkg/controller/restore_finalizer_controller.go:473" restore=d69592eb-1530-4151-99fc-b3a1859b3398
time="2025-10-21T11:49:04+08:00" level=info msg="running exec hook" hookCommand="[/bin/echo restore-post1--------------]" hookContainer=nginx hookName=default-recovery-hook hookOnError=Fail hookPhase=post hookSource=spec hookTimeout="{5m0s}" hookType=exec pod=nginx-example2/nginx-deployment-69574f8c7d-hwzt9 restore=d69592eb-1530-4151-99fc-b3a1859b3398
time="2025-10-21T11:49:04+08:00" level=info msg="stdout: restore-post1--------------\n" hookCommand="[/bin/echo restore-post1--------------]" hookContainer=nginx hookName=default-recovery-hook hookOnError=Fail hookPhase=post hookSource=spec hookTimeout="{5m0s}" hookType=exec pod=nginx-example2/nginx-deployment-69574f8c7d-hwzt9 restore=d69592eb-1530-4151-99fc-b3a1859b3398
time="2025-10-21T11:49:04+08:00" level=info msg="stderr: " hookCommand="[/bin/echo restore-post1--------------]" hookContainer=nginx hookName=default-recovery-hook hookOnError=Fail hookPhase=post hookSource=spec hookTimeout="{5m0s}" hookType=exec pod=nginx-example2/nginx-deployment-69574f8c7d-hwzt9 restore=d69592eb-1530-4151-99fc-b3a1859b3398


time="2025-10-21T11:49:04+08:00" level=warning msg="Error recording the hook in hook tracker" error="hook not exist in hook tracker, hook: {podNamespace:nginx-example2 podName:nginx-deployment-69574f8c7d-hwzt9 hookPhase: hookName:default-recovery-hook hookSource:spec container:nginx hookIndex:0}" hookPhase=post hookSource=spec hookType=exec pod=nginx-example2/nginx-deployment-69574f8c7d-hwzt9 restore=d69592eb-1530-4151-99fc-b3a1859b3398


time="2025-10-21T11:49:04+08:00" level=info msg="running exec hook" hookCommand="[/bin/echo restore-post1--------------]" hookContainer=nginx hookName=default-recovery-hook hookOnError=Fail hookPhase=post hookSource=spec hookTimeout="{5m0s}" hookType=exec pod=nginx-example2/nginx-deployment-69574f8c7d-hwzt9 restore=d69592eb-1530-4151-99fc-b3a1859b3398
time="2025-10-21T11:49:04+08:00" level=info msg="stdout: restore-post1--------------\n" hookCommand="[/bin/echo restore-post1--------------]" hookContainer=nginx hookName=default-recovery-hook hookOnError=Fail hookPhase=post hookSource=spec hookTimeout="{5m0s}" hookType=exec pod=nginx-example2/nginx-deployment-69574f8c7d-hwzt9 restore=d69592eb-1530-4151-99fc-b3a1859b3398
time="2025-10-21T11:49:04+08:00" level=info msg="stderr: " hookCommand="[/bin/echo restore-post1--------------]" hookContainer=nginx hookName=default-recovery-hook hookOnError=Fail hookPhase=post hookSource=spec hookTimeout="{5m0s}" hookType=exec pod=nginx-example2/nginx-deployment-69574f8c7d-hwzt9 restore=d69592eb-1530-4151-99fc-b3a1859b3398
time="2025-10-21T11:49:04+08:00" level=debug msg="Checking the progress of hooks execution: attempted=2 failed=0, restore name=d69592eb-1530-4151-99fc-b3a1859b3398" logSource="pkg/controller/restore_finalizer_controller.go:473" restore=d69592eb-1530-4151-99fc-b3a1859b3398
```

**Anything else you would like to add:**

I change i to hook.hookIndex
the follow is my code fix, In my environment , it could work, Please help me to confirm this fix
```
--- a/internal/hook/wait_exec_hook_handler.go
+++ b/internal/hook/wait_exec_hook_handler.go
@@ -169,7 +169,11 @@ func (e *DefaultWaitExecHookHandler) HandleHooks(
                                        hookLog.Error(err)
                                        errors = append(errors, err)

-                                       errTracker := multiHookTracker.Record(restoreName, newPod.Namespace, newPod.Name, hook.Hook.Container, hook.HookSource, hook.HookName, HookPhase(""), i, true, err)
+                                       // Debug: log loop index and original hook index to help diagnose mismatches
+                                       logrus.Debugf("Recording timeout: loopIndex=%d originalHookIndex=%d pod=%s", i, hook.hookIndex, kube.NamespaceAndName(newPod))
+                                       // Use the original hook index (hook.hookIndex) when recording so the key
+                                       // matches the one created by GroupRestoreExecHooks/Add.
+                                       errTracker := multiHookTracker.Record(restoreName, newPod.Namespace, newPod.Name, hook.Hook.Container, hook.HookSource, hook.HookName, HookPhase(""), hook.hookIndex, true, err)
                                        if errTracker != nil {
                                                hookLog.WithError(errTracker).Warn("Error recording the hook in hook tracker")
                                        }
@@ -195,7 +199,11 @@ func (e *DefaultWaitExecHookHandler) HandleHooks(
                                        hookFailed = true
                                }
....
....
....
```

**Environment:**

- Velero version (use `velero version`): v1.17.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):v1.33.4
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):Kylin Linux Advanced Server V10 , platform arm64

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by blackpiglet**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #9359

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

File: internal/hook/wait_exec_hook_handler_test.go
Comment (kaovilai) [inline internal/hook/wait_exec_hook_handler_test.go:1]: The test should simulate the exact failure scenario from issue #9359:
```go
  {
      name: "Multiple hooks with non-sequential indices (bug #9359)",
      byContainer: map[string][]PodExecRestoreHook{
          "nginx": {
              {
                  HookName:   "first-hook",
                  HookSource: HookSourceSpec,
                  Hook: velerov1api.ExecRestoreHook{
                      Container:   "nginx",
                      Command:     []string{"/usr/bin/foo"},
                  },
                  hookIndex: 0,  // Original position
              },
              {
                  HookName:   "second-hook",
                  HookSource: HookSourceSpec,
                  Hook: velerov1api.ExecRestoreHook{
                      Container:   "nginx",
                      Command:     []string{"/usr/bin/bar"},
                  },
                  hookIndex: 2,  // Skipped index 1 (was for different container)
              },
              {
                  HookName:   "third-hook",
                  HookSource: HookSourceSpec,
                  Hook: velerov1api.ExecRestoreHook{
                      Container:   "nginx",
                      Command:     []string{"/usr/bin/baz"},
                  },
                  hookIndex: 4,  // Skipped index 3
              },

```

**Comment by blackpiglet** [comment]
@kaovilai 
Addressed the comments. Please take another look.

**Review by shubham-pampattiwar — APPROVED** [review]
