### PR TITLE
Override logrus.ErrorKey when json logging is enabled

### LINKED ISSUE #2829: Irreconcilable error, error.file and error.function logging fields
**What steps did you take and what happened:**
Enabled structured logging (`log.format=json`) to index Velero logs in Elasticsearch. This produces mapping exceptions such as:

```json
{
  "type":"illegal_argument_exception",
  "reason":"Can't merge a non object mapping [json.error] with an object mapping [json.error]"
}
```

**What did you expect to happen:**
Velero log event fields should be consistent with each other and allow a JSON representation compatible with Elasticsearch to exist.

**Anything else you would like to add:**
This is similar to a previous issue I reported and fixed -- see #2795.

The problem is is in the logrus hook for errors (`error_location_hook.go`) which contains the following field name constants:

```go
const (
	errorFileField     = "error.file"
	errorFunctionField = "error.function"
)
```

Since an error _also_ produces a message and stores it underfield `error`, we end up with:

```json
{
  "error": "the message",
  "error.file": "file.go",
  "error.function": "foo"
}
```

Now, this is valid JSON, but recent Elasticsearch versions (7.x ?) no longer support dots in field names and automatically expand to nested objects:

```json
{
  "error": {
    "file": "file.go",
    "function": "foo",
  }
}
```

The problem, at this point, is that field `error` cannot be a string and an object at the same time, so Elasticsearch throws an error:

> Can't merge a non object mapping [json.error] with an object mapping [json.error]"

**Environment:**
master (c663ce15ab468b21a19336dcc38acf3280853361)

### PR DESCRIPTION
**Pull request by bgagnon**
When JSON logging format is enabled, set `logrus.ErrorKey` module var to `"error.message"` instead of `"error"`.

Fixes #2829

### CODE REVIEW

File: pkg/util/logging/default_logger.go [hunk 1]
```diff
@@ -38,6 +38,23 @@ func DefaultLogger(level logrus.Level, format Format) *logrus.Logger {
...
+		// field "error" cannot be both a string and an object at the same
+		// time.
+		//
+		// ELK being a popular choice for log ingestion and a common reason
+		// for enabling JSON logging in the first place, we avoid this mapping
+		// problem by nesting the error's message at "error.message".
+		//
+		// This also follows the Elastic Common Schema (ECS) recommendation.
+		// https://www.elastic.co/guide/en/ecs/current/ecs-error.html
+		logrus.ErrorKey = "error.message"
```
Comment (ashish-amarnath) [inline pkg/util/logging/default_logger.go:55]: For the benefit of other reviewers.
Using `--log-format=json`
Current log messages are like:
```json
{
  "backupLocation": "default",
  "controller": "backup-sync",
  "error": "rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Get https://192.168.0.100/velero?delimiter=%2F&list-type=2&prefix=backups%2F: x509: certificate signed by unknown authority",
  "error.file": "/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:331",
  "error.function": "main.(*ObjectStore).ListCommonPrefixes",
  "level": "error",
  "logSource": "pkg/controller/backup_sync_controller.go:175",
  "msg": "Error listing backups in backup store",
  "time": "2020-08-17T22:42:00Z"
}
```
The changes in this PR proposes this to be like
```
{
  "backupLocation": "default",
  "controller": "backup-sync",
  "error.file": "/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:331",
  "error.function": "main.(*ObjectStore).ListCommonPrefixes",
  "error.message": "rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Get https://192.168.0.100/velero?delimiter=%2F&list-type=2&prefix=backups%2F: x509: certificate signed by unknown authority",
  "level": "error",
  "logSource": "pkg/controller/backup_sync_controller.go:175",
  "msg": "Error listing backups in backup store",
  "time": "2020-08-17T22:40:34Z"
}
```

This is a reasonable change and I am OK with this.

**Comment by bgagnon** [comment]
I'm a little uneasy with the mutation of global variables, but I don't see any better way given the logrus API.
